import { ALPHAPILOT_API_BASE } from '@/lib/alphaPilotApi';

export type CommoditySymbol = 'CRUDEOIL' | 'NATURALGAS';
export const COMMODITY_SCAN_EVENT = 'alphapilot:commodity-scan';

export interface CommodityContract { underlying?:string; root_symbol?:string; exchange?:string; segment?:string; trading_symbol?:string; groww_symbol?:string; expiry?:string|null; expiry_date?:string|null; lot_size?:number|null; tick_size?:number|null; [key:string]:any; }
export interface CommodityProbeResponse { symbol:CommoditySymbol|string; provider?:string; ready_for_phase1:boolean; contract?:CommodityContract|null; quote?:any; candles?:any[]; candle_count?:number; quote_ok?:boolean; candles_ok?:boolean; checks?:Record<string,boolean>; errors?:Record<string,string>|string[]; [key:string]:any; }
export interface CommodityTimeframeResult { symbol:string; status:string; signal:'BUY'|'SELL'|'NO TRADE'|string; alpha_score?:number; price?:number; latest_candle_at?:string; fresh?:boolean; age_minutes?:number|null; rsi14?:number; market_structure?:string; entry?:number; stop_loss?:number; target1?:number; target2?:number; risk_reward?:number; [key:string]:any; }
export interface CommodityScanResponse { provider:string; mode:string; symbol:CommoditySymbol|string; contract:CommodityContract; market_session:{status:string;is_open:boolean;checked_at:string}; timeframes:Record<string,CommodityTimeframeResult>; action:'BUY'|'SELL'|'NO TRADE'|string; alpha_score:number; fresh_market_data?:boolean|null; live_price?:number|null; entry_drift_r?:number|null; max_entry_drift_r?:number|null; live_price_guard_passed?:boolean|null; execution_ready:boolean; status:string; entry?:number|null; stop_loss?:number|null; target1?:number|null; target2?:number|null; risk_reward?:number|null; blockers?:string[]; }
export interface CommodityNewsItem { headline:string; source:string; published_at?:string|null; url?:string|null; sentiment:'BULLISH'|'BEARISH'|'NEUTRAL'|string; preferred_source?:boolean; event_tags?:string[]; error?:string; }
export interface CommodityNewsResponse { provider:string; symbol:CommoditySymbol|string; generated_at:string; event_tags:string[]; items:CommodityNewsItem[]; }

export interface CommodityBacktestSummary { trades:number; resolved:number; wins:number; losses:number; win_rate_pct:number; t1_hits:number; t2_hits:number; t2_touched?:number; sl_hits:number; ambiguous:number; open:number; expectancy_r:number; profit_factor:number|null; net_r:number; max_drawdown_r:number; max_consecutive_losses:number; }
export interface CommodityBacktestResponse { mode:string; symbol:CommoditySymbol|string; contract:CommodityContract; requested_days:number; coverage:{start?:string|null;end?:string|null;candles:Record<string,number>}; rules:Record<string,any>; summary:CommodityBacktestSummary; by_action:{BUY:CommodityBacktestSummary;SELL:CommodityBacktestSummary}; trades:Array<Record<string,any>>; limitations:string[]; }
export interface CommodityContinuousBacktestResponse { mode:string; rollover_method?:'EXPIRY_BOUNDARY_FRONT_MONTH'|string; classification:'VALID_CONTINUOUS_ROLLOVER'|'SINGLE_CONTRACT_EXTENDED_HISTORY'|'INSUFFICIENT_HISTORY'|string; rollover_valid:boolean; coverage_confidence:'HIGH'|'MEDIUM'|'LOW'|string; symbol:CommoditySymbol|string; requested_days:number; requested_start:string; requested_end:string; actual_start?:string|null; actual_end?:string|null; coverage_days:number; coverage_ratio_pct:number; historical_coverage_days?:number; historical_coverage_pct?:number; requested_weekdays?:number; observed_session_days?:number; contracts_discovered:number; contracts_selected:number; contracts_used:Array<{contract:string;expiry:string;window_start:string;window_end:string;effective_start?:string|null;effective_end?:string|null;effective_days?:number;observed_session_days?:number;candles:Record<string,number>;trades:number}>; contracts_skipped:Array<{contract:string;expiry:string;reason:string}>; summary:CommodityBacktestSummary; by_action:{BUY:CommodityBacktestSummary;SELL:CommodityBacktestSummary}; trades:Array<Record<string,any>>; limitations:string[]; }

async function commodityRequest<T>(path:string, init?:RequestInit):Promise<T>{ const response=await fetch(`${ALPHAPILOT_API_BASE}${path}`,{headers:{Accept:'application/json','Content-Type':'application/json',...(init?.headers||{})},...init}); if(!response.ok){const detail=await response.text().catch(()=>'');throw new Error(`Commodity API ${response.status}: ${detail||response.statusText}`);} return response.json() as Promise<T>; }
export function getCommodityProbe(symbol:CommoditySymbol){return commodityRequest<CommodityProbeResponse>(`/v1/commodity/probe/${encodeURIComponent(symbol)}`);}
export function getCommodityContract(symbol:CommoditySymbol){return commodityRequest<CommodityContract>(`/v1/commodity/contract/${encodeURIComponent(symbol)}`);}
export function getCommodityQuote(symbol:CommoditySymbol){return commodityRequest<any>(`/v1/commodity/quote/${encodeURIComponent(symbol)}`);}
export function getCommodityCandles(symbol:CommoditySymbol,timeframe='5m'){const params=new URLSearchParams({timeframe});return commodityRequest<any>(`/v1/commodity/candles/${encodeURIComponent(symbol)}?${params.toString()}`);}
export async function scanCommodity(symbol:CommoditySymbol,minRiskReward=1.5){const params=new URLSearchParams({min_risk_reward:String(minRiskReward)});const result=await commodityRequest<CommodityScanResponse>(`/v1/commodity/scan/${encodeURIComponent(symbol)}?${params.toString()}`);if(typeof window!=='undefined')window.dispatchEvent(new CustomEvent(COMMODITY_SCAN_EVENT,{detail:{...result,captured_at:new Date().toISOString()}}));return result;}
export function getCommodityNews(symbol:CommoditySymbol,limit=4){const params=new URLSearchParams({limit:String(Math.max(1,Math.min(limit,6)))});return commodityRequest<CommodityNewsResponse>(`/v1/commodity/news/${encodeURIComponent(symbol)}?${params.toString()}`);}
const backtestBody=(args:{symbol:CommoditySymbol;days:number;min_risk_reward?:number;strength_threshold?:number;slippage_bps?:number;cost_bps?:number})=>JSON.stringify({symbol:args.symbol,days:args.days,min_risk_reward:args.min_risk_reward??1.5,strength_threshold:args.strength_threshold??65,slippage_bps:args.slippage_bps??2,cost_bps:args.cost_bps??2});
export function runCommodityBacktest(args:{symbol:CommoditySymbol;days:number;min_risk_reward?:number;strength_threshold?:number;slippage_bps?:number;cost_bps?:number}){return commodityRequest<CommodityBacktestResponse>('/v1/commodity/backtest',{method:'POST',body:backtestBody(args)});}
export function runContinuousCommodityBacktest(args:{symbol:CommoditySymbol;days:number;min_risk_reward?:number;strength_threshold?:number;slippage_bps?:number;cost_bps?:number}){return commodityRequest<CommodityContinuousBacktestResponse>('/v1/commodity/backtest/continuous',{method:'POST',body:backtestBody(args)});}
