import { ALPHAPILOT_API_BASE } from '@/lib/alphaPilotApi';
export type IntelligenceItem={headline:string;source:string;published_at?:string|null;url?:string|null;sentiment:string;topic:string;impact:string;source_tier?:string;affected?:string[]};
export type OfficialSignalItem={headline:string;source:string;published_at?:string|null;url?:string|null;sentiment:string;group:string;source_type:string;confidence:string;novelty:string;affected:string[];primary_source_preferred:boolean};
export type OfficialSignalsResponse={mode:string;generated_at:string;research_only:boolean;production_rules_changed:boolean;groups:Record<string,OfficialSignalItem[]>;items:OfficialSignalItem[];method_note:string};
export type CrossAssetItem={status:string;label:string;ticker:string;value?:number;change_pct?:number;bias:string;source:string;exchange_timezone?:string;market_state?:string;fetched_at:string;research_only:boolean;error?:string};
export type CrossAssetAgreement={state:string;risk_on:number;risk_off:number;neutral:number;usable:number;score:number;research_only:boolean;method_note:string};
export type CrossAssetSnapshot={status:string;available:number;total:number;assets:Record<string,CrossAssetItem>;agreement?:CrossAssetAgreement;method_note:string};
export type GiftNiftyResearch={status:string;source:string;source_url?:string;ltp?:number;change?:number;change_pct?:number;expiry?:string;bias:string;fetched_at:string;research_only:boolean;production_rules_changed:boolean;attempts?:{source:string;url?:string;error:string}[];warning:string};
export type GrowwGiftMatch={exchange?:string;trading_symbol?:string;groww_symbol?:string;name?:string;instrument_type?:string;segment?:string;underlying_symbol?:string;expiry_date?:string;buy_allowed?:string;sell_allowed?:string};
export type GrowwGiftDiscovery={status:string;supported:boolean;matches:GrowwGiftMatch[];source:string;source_url:string;checked_at:string;research_only:boolean;production_rules_changed:boolean;note?:string;error?:string};
export type GlobalIntelligenceResponse={mode:string;research_only:boolean;production_rules_changed:boolean;generated_at:string;risk_state:string;risk_score?:number;topics:Record<string,IntelligenceItem[]>;high_impact:IntelligenceItem[];official_signals?:OfficialSignalsResponse;cross_assets?:CrossAssetSnapshot;gift_nifty_research?:GiftNiftyResearch;groww_gift_discovery?:GrowwGiftDiscovery;quality?:Record<string,number>;method_note:string};
export async function fetchGlobalIntelligence(limit=5):Promise<GlobalIntelligenceResponse>{const r=await fetch(`${ALPHAPILOT_API_BASE}/v1/market/global-intelligence?limit=${limit}`);if(!r.ok)throw new Error(`Global Intelligence API ${r.status}`);return r.json()}
