import { ALPHAPILOT_API_BASE } from '@/lib/alphaPilotApi';
import { fetchGlobalIntelligence, type GlobalIntelligenceResponse } from '@/lib/globalIntelligenceApi';

export type BreadthRow={symbol:string;sector:string;change_pct:number;above_vwap:boolean;volume_ratio:number;trend:string;status:string;latest_candle_at?:string;freshness?:string;phase?:string};
export type SectorBreadth={sector:string;advancers:number;decliners:number;flat:number;above_vwap:number;total:number;score:number;state:string};
export type MarketBrainV2Result={generated_at:string;research_only:true;production_rules_changed:false;breadth:{advancers:number;decliners:number;flat:number;above_vwap:number;total:number;coverage:number;score:number;state:string;rows:BreadthRow[];sectors:SectorBreadth[]};index_context:{nifty?:BreadthRow;banknifty?:BreadthRow};flow:{state:string;score:number;strong_volume_names:string[]};data_quality:{state:string;fresh:number;delayed:number;stale:number;unavailable:number;coverage:number};cross_asset:{gift_nifty:{status:string;bias:string;change_pct?:number;source?:string};unavailable:string[]};event_context:{state:string;high_impact_count:number;items:{headline:string;topic:string;impact:string;source:string}[]};composite:{state:string;score:number;confidence:number};limitations:string[]};

const SECTOR:Record<string,string>={
  NIFTY:'INDEX',BANKNIFTY:'INDEX',
  HDFCBANK:'FINANCIALS',ICICIBANK:'FINANCIALS',SBIN:'FINANCIALS',AXISBANK:'FINANCIALS',KOTAKBANK:'FINANCIALS',BAJFINANCE:'FINANCIALS',
  TCS:'IT',INFY:'IT',HCLTECH:'IT',WIPRO:'IT',
  RELIANCE:'ENERGY',ONGC:'ENERGY',NTPC:'POWER',POWERGRID:'POWER',
  TATASTEEL:'METALS',JSWSTEEL:'METALS',HINDALCO:'METALS',
  MARUTI:'AUTO','M&M':'AUTO',TATAMOTORS:'AUTO',
  SUNPHARMA:'PHARMA',DRREDDY:'PHARMA',CIPLA:'PHARMA',
  ITC:'CONSUMER',TITAN:'CONSUMER',ASIANPAINT:'CONSUMER',
  LT:'INDUSTRIALS',ADANIPORTS:'INDUSTRIALS',ULTRACEMCO:'MATERIALS',BHARTIARTL:'TELECOM',
};
const SYMBOLS=['NIFTY','BANKNIFTY','RELIANCE','HDFCBANK','ICICIBANK','SBIN','AXISBANK','KOTAKBANK','BAJFINANCE','TCS','INFY','HCLTECH','WIPRO','ONGC','NTPC','POWERGRID','TATASTEEL','JSWSTEEL','HINDALCO','MARUTI','M&M','TATAMOTORS','SUNPHARMA','DRREDDY','CIPLA','ITC','TITAN','ASIANPAINT','LT','ADANIPORTS','ULTRACEMCO','BHARTIARTL'];
const STOCK_COUNT=SYMBOLS.length-2;
function n(v:any,d=0){const x=Number(v);return Number.isFinite(x)?x:d}
function parseCandles(raw:any):any[]{return Array.isArray(raw?.candles)?raw.candles:[]}
function day(ts:any){return String(ts).slice(0,10)} function slot(ts:any){return String(ts).slice(11,16)}
function parseMarketTs(ts:any){const s=String(ts).trim();if(!s)return NaN;if(/[zZ]$|[+-]\d\d:?\d\d$/.test(s))return new Date(s).getTime();const normalized=s.replace(' ','T');return new Date(`${normalized}+05:30`).getTime()}
function phase(change:number,trend:string){if(change>.05&&trend==='UP')return'ALIGNED_UP';if(change<-.05&&trend==='DOWN')return'ALIGNED_DOWN';if(change<-.05&&trend==='UP')return'RECOVERY';if(change>.05&&trend==='DOWN')return'FADE';return'MIXED'}
function summarize(symbol:string,candles:any[]):BreadthRow|null{
  const raw=candles.filter(x=>Array.isArray(x)&&x.length>=6&&n(x[4])>0); if(raw.length<3)return null;
  const activeIndex=[...raw].map((x,i)=>({x,i})).reverse().find(z=>n(z.x[5])>0)?.i ?? raw.length-1;
  const c=raw.slice(0,activeIndex+1),last=c[c.length-1],lastClose=n(last[4]),lastDay=day(last[0]),session=c.filter(x=>day(x[0])===lastDay); if(!session.length)return null;
  const prior=c.filter(x=>day(x[0])<lastDay),priorClose=prior.length?n(prior[prior.length-1][4]):n(session[0][1]),change=priorClose?((lastClose/priorClose)-1)*100:0;
  const vv=session.reduce((s,x)=>s+n(x[5]),0),pv=session.reduce((s,x)=>s+(((n(x[2])+n(x[3])+n(x[4]))/3)*n(x[5])),0),vwap=vv?pv/vv:lastClose;
  const currentSlot=slot(last[0]),peerVols=prior.filter(x=>slot(x[0])===currentSlot&&n(x[5])>0).slice(-12).map(x=>n(x[5]));
  const fallback=c.slice(-25,-1).map(x=>n(x[5])).filter(x=>x>0),base=peerVols.length>=3?peerVols:fallback,avg=base.length?base.reduce((a,b)=>a+b,0)/base.length:0,vr=avg?n(last[5])/avg:1;
  const sessionLookback=session.length>5?n(session[session.length-6][4]):n(session[0][1]),trend=lastClose>sessionLookback?'UP':lastClose<sessionLookback?'DOWN':'FLAT';
  const latest=String(last[0]); let freshness='UNKNOWN'; const marketTs=parseMarketTs(latest);if(Number.isFinite(marketTs)){const age=(Date.now()-marketTs)/60000;freshness=age<=30?'FRESH':age<=24*60?'DELAYED':'STALE'}
  const rounded=Number(change.toFixed(2));
  return {symbol,sector:SECTOR[symbol]??'OTHER',change_pct:rounded,above_vwap:lastClose>=vwap,volume_ratio:Number(vr.toFixed(2)),trend,status:'AVAILABLE',latest_candle_at:latest,freshness,phase:phase(rounded,trend)};
}
async function getCandles(symbol:string){const r=await fetch(`${ALPHAPILOT_API_BASE}/v1/candles/${encodeURIComponent(symbol)}?timeframe=15m`);if(!r.ok)throw new Error(`${symbol} candles ${r.status}`);return parseCandles(await r.json())}
async function loadRows(){const out:BreadthRow[]=[];for(let i=0;i<SYMBOLS.length;i+=4){const batch=SYMBOLS.slice(i,i+4);const settled=await Promise.allSettled(batch.map(async s=>summarize(s,await getCandles(s))));settled.forEach((x,j)=>{const s=batch[j];out.push(x.status==='fulfilled'&&x.value?x.value:{symbol:s,sector:SECTOR[s]??'OTHER',change_pct:0,above_vwap:false,volume_ratio:0,trend:'UNKNOWN',status:'UNAVAILABLE',freshness:'UNKNOWN',phase:'UNKNOWN'})})}return out}
async function getExternal(){const r=await fetch(`${ALPHAPILOT_API_BASE}/v1/context/external/RELIANCE`);if(!r.ok)throw new Error(`external context ${r.status}`);return r.json()}
function eventSnapshot(gi:GlobalIntelligenceResponse){const rows=[...(gi.high_impact??[])];for(const items of Object.values(gi.topics??{}))for(const x of items){const t=x.headline.toLowerCase();if(/ahead|await|speech|meeting|decision|cpi|pce|inflation data|jobs|payroll|rbi|fed|ecb|boj|opec/.test(t))rows.push(x)}const seen=new Set<string>();const unique=rows.filter(x=>{const k=x.headline.toLowerCase();if(seen.has(k))return false;seen.add(k);return true}).slice(0,8);const high=unique.filter(x=>x.impact==='HIGH').length;return{state:high>=2?'ELEVATED_EVENT_RISK':unique.length>=3?'ACTIVE_EVENT_RISK':'LOW_EVENT_RISK',high_impact_count:high,items:unique.map(x=>({headline:x.headline,topic:x.topic,impact:x.impact,source:x.source}))}}
function sectorBreadth(stocks:BreadthRow[]):SectorBreadth[]{const groups=new Map<string,BreadthRow[]>();for(const x of stocks){const a=groups.get(x.sector)??[];a.push(x);groups.set(x.sector,a)}return [...groups.entries()].map(([sector,rows])=>{const adv=rows.filter(x=>x.change_pct>.05).length,dec=rows.filter(x=>x.change_pct<-.05).length,flat=rows.length-adv-dec,above=rows.filter(x=>x.above_vwap).length,score=rows.length?((adv-dec)/rows.length*50)+((above/rows.length)-.5)*50:0;return{sector,advancers:adv,decliners:dec,flat,above_vwap:above,total:rows.length,score:Number(score.toFixed(1)),state:score>=20?'LEADING':score<=-20?'LAGGING':'MIXED'}}).sort((a,b)=>b.score-a.score)}
export async function fetchMarketBrainV2():Promise<MarketBrainV2Result>{
  const rows=await loadRows(),stocks=rows.filter(x=>!['NIFTY','BANKNIFTY'].includes(x.symbol)&&x.status==='AVAILABLE'),adv=stocks.filter(x=>x.change_pct>.05).length,dec=stocks.filter(x=>x.change_pct<-.05).length,flat=stocks.length-adv-dec,above=stocks.filter(x=>x.above_vwap).length,coverage=stocks.length/STOCK_COUNT;
  const breadthScore=stocks.length?((adv-dec)/stocks.length*50)+((above/stocks.length)-.5)*50:0,breadthState=breadthScore>=20?'BROAD_RISK_ON':breadthScore<=-20?'BROAD_RISK_OFF':'MIXED';
  const strong=stocks.filter(x=>x.volume_ratio>=1.5).map(x=>x.symbol),flowScore=stocks.length?stocks.reduce((s,x)=>s+(x.change_pct>.05?1:x.change_pct<-.05?-1:0)*Math.min(x.volume_ratio,2),0)/stocks.length*25:0,flowState=flowScore>=15?'BUYING_PRESSURE':flowScore<=-15?'SELLING_PRESSURE':'BALANCED';
  let gift:any={status:'UNAVAILABLE',bias:'UNKNOWN'};try{const ext=await getExternal();gift=ext?.gift_nifty??gift}catch{}
  let gi:GlobalIntelligenceResponse|null=null;try{gi=await fetchGlobalIntelligence(4)}catch{}
  const event=gi?eventSnapshot(gi):{state:'UNAVAILABLE',high_impact_count:0,items:[]},nifty=rows.find(x=>x.symbol==='NIFTY'&&x.status==='AVAILABLE'),bank=rows.find(x=>x.symbol==='BANKNIFTY'&&x.status==='AVAILABLE');
  const dir=(x?:BreadthRow)=>!x?0:x.change_pct>.05?1:x.change_pct<-.05?-1:0,indexScore=dir(nifty)*12+dir(bank)*8+(nifty?(nifty.above_vwap?8:-4):0)+(bank?(bank.above_vwap?5:-3):0),giftScore=gift?.bias==='BULLISH'?10:gift?.bias==='BEARISH'?-10:0,newsScore=gi?.risk_state==='RISK_ON'?8:gi?.risk_state==='RISK_OFF'?-8:0,eventPenalty=event.state==='ELEVATED_EVENT_RISK'?8:0;
  const score=Math.max(-100,Math.min(100,Math.round(breadthScore*.35+flowScore*.25+indexScore+giftScore+newsScore))),state=score>=25?'SUPPORTIVE_LONG_CONTEXT':score<=-25?'SUPPORTIVE_SHORT_CONTEXT':'MIXED_CONTEXT';
  const available=rows.filter(x=>x.status==='AVAILABLE'),fresh=available.filter(x=>x.freshness==='FRESH').length,delayed=available.filter(x=>x.freshness==='DELAYED').length,stale=available.filter(x=>x.freshness==='STALE').length,unavailable=rows.length-available.length,dataCoverage=available.length/rows.length;
  const dqState=stale>available.length*.25?'STALE_CONTEXT':delayed+stale>available.length*.5?'DELAYED_CONTEXT':dataCoverage<.8?'PARTIAL_CONTEXT':'GOOD';
  let confidence=Math.max(0,Math.min(100,Math.round(55+Math.min(Math.abs(score),30)-eventPenalty-(coverage<.75?15:0))));if(dqState==='DELAYED_CONTEXT')confidence=Math.min(confidence,45);if(dqState==='STALE_CONTEXT')confidence=Math.min(confidence,30);if(dataCoverage<.8)confidence=Math.min(confidence,40);
  return {generated_at:new Date().toISOString(),research_only:true,production_rules_changed:false,breadth:{advancers:adv,decliners:dec,flat,above_vwap:above,total:stocks.length,coverage:Number(coverage.toFixed(2)),score:Number(breadthScore.toFixed(1)),state:breadthState,rows:stocks,sectors:sectorBreadth(stocks)},index_context:{nifty,banknifty:bank},flow:{state:flowState,score:Number(flowScore.toFixed(1)),strong_volume_names:strong},data_quality:{state:dqState,fresh,delayed,stale,unavailable,coverage:Number(dataCoverage.toFixed(2))},cross_asset:{gift_nifty:{status:gift?.status??'UNAVAILABLE',bias:gift?.bias??'UNKNOWN',change_pct:gift?.change_pct,source:gift?.source},unavailable:['INDIA_VIX','USDINR','DXY','US_10Y','BRENT','NASDAQ_FUTURES']},event_context:event,composite:{state,score,confidence},limitations:['v2.2.1 interprets timezone-less Groww candle timestamps as Asia/Kolkata before judging freshness; this prevents false STALE labels caused by browser UTC parsing.','v2.2 expands the research breadth proxy to 30 sector-balanced liquid NSE stocks. It is still not full-exchange breadth.','Session direction and short-term trend are kept separate: RECOVERY means negative session but rising recent bars; FADE means positive session but falling recent bars.','Data freshness is a first-class quality state; delayed/stale context caps confidence instead of masquerading as live evidence.','Candle requests are batched four at a time to respect the Groww/Render rate budget.','Additional cross-assets remain explicitly unavailable until a reliable research feed is connected.','All outputs are research context only and cannot authorize, veto, or modify production trades.']};
}
