import { useEffect, useState } from 'react';
import { AlertTriangle, CheckCircle2, Database, Download, RefreshCw, Trash2 } from 'lucide-react';
import { Badge, Button, Card, CardBody, CardHeader } from '@/components/ui';
import { COMMODITY_SCAN_EVENT, getCommodityCandles, type CommodityScanResponse, type CommoditySymbol } from '@/lib/commodityApi';

const DB_NAME='alphapilot-mcx-history';
const DB_VERSION=1;
const STORE='candles5m';
const SYMBOLS:CommoditySymbol[]=['CRUDEOIL','NATURALGAS'];
const FIVE_MIN=5*60_000;

type StoredCandle={id:string;symbol:CommoditySymbol;contract:string;timestamp:string;epoch_ms:number;open:number;high:number;low:number;close:number;volume:number|null;captured_at:string};
type Stats={count:number;first:string|null;last:string|null;contracts:number};
type Health={status:'HEALTHY'|'LAGGING'|'GAPS'|'MARKET CLOSED'|'AWAITING DATA';today:number;expected:number;missing:number;gap_count:number;duplicate_slots:number;latest_age_min:number|null;message:string};
const emptyStats=():Record<CommoditySymbol,Stats>=>({CRUDEOIL:{count:0,first:null,last:null,contracts:0},NATURALGAS:{count:0,first:null,last:null,contracts:0}});
const emptyHealth=():Record<CommoditySymbol,Health>=>({CRUDEOIL:{status:'AWAITING DATA',today:0,expected:0,missing:0,gap_count:0,duplicate_slots:0,latest_age_min:null,message:'No recorder health data yet.'},NATURALGAS:{status:'AWAITING DATA',today:0,expected:0,missing:0,gap_count:0,duplicate_slots:0,latest_age_min:null,message:'No recorder health data yet.'}});

function dbOpen():Promise<IDBDatabase>{return new Promise((resolve,reject)=>{const r=indexedDB.open(DB_NAME,DB_VERSION);r.onupgradeneeded=()=>{const db=r.result;if(!db.objectStoreNames.contains(STORE)){const s=db.createObjectStore(STORE,{keyPath:'id'});s.createIndex('symbol','symbol',{unique:false});s.createIndex('epoch_ms','epoch_ms',{unique:false});}};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
function parseTs(value:unknown){if(value==null)return null;let d:Date;if(typeof value==='number'||/^\d+(\.\d+)?$/.test(String(value))){let n=Number(value);if(n<1e12)n*=1000;d=new Date(n);}else d=new Date(String(value));return Number.isNaN(d.getTime())?null:d;}
function completed(row:any[],now=Date.now()){const d=parseTs(row?.[0]);return !!d&&d.getTime()+FIVE_MIN<=now;}
function normalize(symbol:CommoditySymbol,contract:string,row:any[]):StoredCandle|null{if(!Array.isArray(row)||row.length<5)return null;const d=parseTs(row[0]);if(!d)return null;const nums=[row[1],row[2],row[3],row[4]].map(Number);if(nums.some(n=>!Number.isFinite(n)||n<=0))return null;const v=Number(row[5]);return{id:`${symbol}|${contract}|${d.getTime()}`,symbol,contract,timestamp:d.toISOString(),epoch_ms:d.getTime(),open:nums[0],high:nums[1],low:nums[2],close:nums[3],volume:Number.isFinite(v)?v:null,captured_at:new Date().toISOString()};}
async function putMany(rows:StoredCandle[]){if(!rows.length)return 0;const db=await dbOpen();return new Promise<number>((resolve,reject)=>{const tx=db.transaction(STORE,'readwrite');const s=tx.objectStore(STORE);rows.forEach(r=>s.put(r));tx.oncomplete=()=>{db.close();resolve(rows.length)};tx.onerror=()=>{db.close();reject(tx.error)};});}
async function allRows(){const db=await dbOpen();return new Promise<StoredCandle[]>((resolve,reject)=>{const tx=db.transaction(STORE,'readonly');const r=tx.objectStore(STORE).getAll();r.onsuccess=()=>{db.close();resolve((r.result??[]) as StoredCandle[])};r.onerror=()=>{db.close();reject(r.error)};});}
async function clearDb(){const db=await dbOpen();return new Promise<void>((resolve,reject)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).clear();tx.oncomplete=()=>{db.close();resolve()};tx.onerror=()=>{db.close();reject(tx.error)};});}
function calcStats(rows:StoredCandle[]){const out=emptyStats();for(const sym of SYMBOLS){const r=rows.filter(x=>x.symbol===sym).sort((a,b)=>a.epoch_ms-b.epoch_ms);out[sym]={count:r.length,first:r[0]?.timestamp??null,last:r[r.length-1]?.timestamp??null,contracts:new Set(r.map(x=>x.contract)).size};}return out;}
function istParts(date=new Date()){const p=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kolkata',year:'numeric',month:'2-digit',day:'2-digit',weekday:'short',hour:'2-digit',minute:'2-digit',hour12:false}).formatToParts(date);const get=(t:string)=>p.find(x=>x.type===t)?.value??'';return{date:`${get('year')}-${get('month')}-${get('day')}`,weekday:get('weekday'),hour:Number(get('hour')),minute:Number(get('minute'))};}
function sameIstDay(epoch:number,dateKey:string){return istParts(new Date(epoch)).date===dateKey;}
function expectedToday(now=new Date()){const p=istParts(now);if(['Sat','Sun'].includes(p.weekday))return{date:p.date,expected:0,closed:true};const mins=p.hour*60+p.minute;const open=9*60,close=23*60+30;if(mins<open)return{date:p.date,expected:0,closed:true};const effective=Math.min(mins,close);const completed=Math.max(0,Math.floor((effective-open)/5));return{date:p.date,expected:completed,closed:mins>close};}
function dedupeHealthSlots(rows:StoredCandle[]){const byEpoch=new Map<number,StoredCandle>();for(const row of rows){const existing=byEpoch.get(row.epoch_ms);if(!existing||new Date(row.captured_at).getTime()>=new Date(existing.captured_at).getTime())byEpoch.set(row.epoch_ms,row);}return [...byEpoch.values()].sort((a,b)=>a.epoch_ms-b.epoch_ms);}
function calcHealth(rows:StoredCandle[]):Record<CommoditySymbol,Health>{const out=emptyHealth();const session=expectedToday();for(const sym of SYMBOLS){const all=rows.filter(x=>x.symbol===sym).sort((a,b)=>a.epoch_ms-b.epoch_ms);const rawToday=all.filter(x=>sameIstDay(x.epoch_ms,session.date));const today=dedupeHealthSlots(rawToday);const duplicateSlots=Math.max(0,rawToday.length-today.length);const latest=today[today.length-1]??all[all.length-1];const age=latest?Math.max(0,(Date.now()-latest.epoch_ms)/60_000):null;let gaps=0;for(let i=1;i<today.length;i++){const diff=today[i].epoch_ms-today[i-1].epoch_ms;if(diff>FIVE_MIN*1.5)gaps+=Math.max(1,Math.round(diff/FIVE_MIN)-1);}const missing=Math.max(0,session.expected-today.length);const rolloverNote=duplicateSlots?` ${duplicateSlots} overlapping rollover candle slot${duplicateSlots===1?' was':'s were'} deduplicated for health calculations.`:'';if(session.closed&&session.expected===0){out[sym]={status:'MARKET CLOSED',today:today.length,expected:0,missing:0,gap_count:gaps,duplicate_slots:duplicateSlots,latest_age_min:age==null?null:Math.round(age),message:`MCX is outside the standard weekday recording window.${rolloverNote}`};continue;}if(!today.length){out[sym]={status:'AWAITING DATA',today:0,expected:session.expected,missing:session.expected,gap_count:0,duplicate_slots:duplicateSlots,latest_age_min:age==null?null:Math.round(age),message:'No completed 5m candle has been recorded for the current session. Expected-count diagnostics use the standard weekday MCX window and are not an exchange holiday calendar.'};continue;}if(gaps>0){out[sym]={status:'GAPS',today:today.length,expected:session.expected,missing,gap_count:gaps,duplicate_slots:duplicateSlots,latest_age_min:age==null?null:Math.round(age),message:`${gaps} missing 5m slot${gaps===1?'':'s'} detected inside today’s unique timestamp sequence.${rolloverNote}`};continue;}if(missing>2||age!=null&&age>20){out[sym]={status:'LAGGING',today:today.length,expected:session.expected,missing,gap_count:0,duplicate_slots:duplicateSlots,latest_age_min:age==null?null:Math.round(age),message:`Recorder is behind the standard weekday-session expectation; run Sync Both Now. Exchange holidays/special sessions can also make this diagnostic conservative.${rolloverNote}`};continue;}const status=session.closed?'MARKET CLOSED':'HEALTHY';out[sym]={status,today:today.length,expected:session.expected,missing,gap_count:0,duplicate_slots:duplicateSlots,latest_age_min:age==null?null:Math.round(age),message:`${session.closed?'Session is closed and the':'Today’s'} completed 5m archive is current with no internal timestamp gaps detected.${rolloverNote}`};}return out;}

export function CommodityDataRecorder(){const[stats,setStats]=useState<Record<CommoditySymbol,Stats>>(emptyStats);const[health,setHealth]=useState<Record<CommoditySymbol,Health>>(emptyHealth);const[loading,setLoading]=useState(false);const[lastSync,setLastSync]=useState<string|null>(null);const[error,setError]=useState<string|null>(null);const[open,setOpen]=useState(false);
const refresh=async()=>{const rows=await allRows();setStats(calcStats(rows));setHealth(calcHealth(rows));};
useEffect(()=>{void refresh();const timer=window.setInterval(()=>void refresh(),60_000);const onScan=(event:Event)=>{const r=(event as CustomEvent<CommodityScanResponse>).detail;if(!r?.symbol||r.market_session?.is_open!==true||r.fresh_market_data!==true)return;const s=String(r.symbol) as CommoditySymbol;if(SYMBOLS.includes(s))void syncOne(s,r.contract?.trading_symbol??r.contract?.groww_symbol??'UNKNOWN',false);};window.addEventListener(COMMODITY_SCAN_EVENT,onScan);return()=>{window.clearInterval(timer);window.removeEventListener(COMMODITY_SCAN_EVENT,onScan)}},[]);
const syncOne=async(symbol:CommoditySymbol,contractHint?:string,surface=true)=>{try{if(surface){setLoading(true);setError(null)}const result=await getCommodityCandles(symbol,'5m');const contract=String(result?.contract?.trading_symbol??result?.contract?.groww_symbol??contractHint??'UNKNOWN');const source=Array.isArray(result?.candles)?result.candles:[];const rows=source.filter((x:any)=>completed(x)).map((x:any)=>normalize(symbol,contract,x)).filter(Boolean) as StoredCandle[];await putMany(rows);setLastSync(new Date().toISOString());await refresh();}catch(e){if(surface)setError(e instanceof Error?e.message:'Recorder sync failed.');}finally{if(surface)setLoading(false)}};
const syncBoth=async()=>{setLoading(true);setError(null);try{for(const s of SYMBOLS)await syncOne(s,undefined,false);setLastSync(new Date().toISOString());await refresh();}catch(e){setError(e instanceof Error?e.message:'Recorder sync failed.');}finally{setLoading(false)}};
const clear=async()=>{await clearDb();setStats(emptyStats());setHealth(emptyHealth());setLastSync(null)};
const exportCsv=async()=>{const rows=(await allRows()).sort((a,b)=>a.epoch_ms-b.epoch_ms);const header='symbol,contract,timestamp,open,high,low,close,volume,captured_at';const lines=rows.map(r=>[r.symbol,r.contract,r.timestamp,r.open,r.high,r.low,r.close,r.volume??'',r.captured_at].join(','));const blob=new Blob([[header,...lines].join('\n')],{type:'text/csv'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`alphapilot-mcx-5m-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(url);};
const total=stats.CRUDEOIL.count+stats.NATURALGAS.count;
return <Card><CardHeader title="MCX Historical Recorder" subtitle="Persistent browser archive of completed Groww 5m candles for future AlphaPilot research." action={<div className="flex items-center gap-2"><Badge variant="blue">{total} CANDLES</Badge><Button size="sm" variant="ghost" onClick={()=>setOpen(v=>!v)}>{open?'Collapse':'Expand'}</Button></div>}/>{open&&<CardBody className="space-y-4"><div className="rounded-lg border border-blue-200 dark:border-blue-900 p-3 text-xs text-slate-500"><Database size={14} className="inline mr-1"/>Stored in this browser's IndexedDB, not Render. Any fresh live MCX scan auto-syncs completed 5m candles; trade execution readiness is not required for recording.</div><div><p className="text-xs font-semibold mb-2">Recorder Health</p><div className="grid grid-cols-1 md:grid-cols-2 gap-3">{SYMBOLS.map(s=><HealthCard key={s} symbol={s} health={health[s]}/>)}</div></div><div className="grid grid-cols-1 md:grid-cols-2 gap-3">{SYMBOLS.map(s=><div key={s} className="rounded-lg border border-slate-200 dark:border-slate-800 p-3"><div className="flex justify-between gap-2"><b className="text-sm">{s}</b><Badge variant={stats[s].count?'green':'default'}>{stats[s].count}</Badge></div><p className="text-xs text-slate-500 mt-2">Contracts {stats[s].contracts} · First {fmt(stats[s].first)} · Latest {fmt(stats[s].last)}</p></div>)}</div>{error&&<p className="text-xs text-red-600">{error}</p>}<div className="flex flex-wrap items-center gap-2"><Button size="sm" variant="primary" onClick={()=>void syncBoth()} disabled={loading}><RefreshCw size={13} className={`inline mr-1 ${loading?'animate-spin':''}`}/>Sync Both Now</Button><Button size="sm" variant="ghost" onClick={()=>void exportCsv()} disabled={!total}><Download size={13} className="inline mr-1"/>Export CSV</Button><Button size="sm" variant="ghost" onClick={()=>void clear()} disabled={!total}><Trash2 size={13} className="inline mr-1"/>Clear Archive</Button>{lastSync&&<span className="text-xs text-slate-500">Last sync {fmt(lastSync)}</span>}</div><p className="text-xs text-amber-600">Keep this browser profile if you want the archive to accumulate. Clearing site data/private browsing will remove it; use Export CSV periodically for backup.</p></CardBody>}</Card>}
function HealthCard({symbol,health}:{symbol:CommoditySymbol;health:Health}){const good=health.status==='HEALTHY'||health.status==='MARKET CLOSED';const variant=health.status==='HEALTHY'?'green':health.status==='GAPS'||health.status==='LAGGING'?'amber':'default';return <div className="rounded-lg border border-slate-200 dark:border-slate-800 p-3"><div className="flex items-center justify-between gap-2"><div className="flex items-center gap-2">{good?<CheckCircle2 size={15} className="text-emerald-500"/>:<AlertTriangle size={15} className="text-amber-500"/>}<b className="text-sm">{symbol}</b></div><Badge variant={variant}>{health.status}</Badge></div><p className="text-xs text-slate-500 mt-2">Today {health.today}/{health.expected||'—'} expected · Missing {health.missing} · Gaps {health.gap_count} · Rollover duplicates {health.duplicate_slots}</p><p className="text-xs text-slate-500 mt-1">Latest age {health.latest_age_min==null?'—':`${health.latest_age_min} min`} · {health.message}</p></div>}
function fmt(v:string|null){if(!v)return'—';const d=new Date(v);return Number.isNaN(d.getTime())?v:d.toLocaleString('en-IN',{timeZone:'Asia/Kolkata',hour12:true});}
