import { useEffect, useMemo, useRef, useState } from 'react';
import { ChevronDown, ChevronUp, RefreshCw, Trash2 } from 'lucide-react';
import { Badge, Button, Card, CardBody, CardHeader } from '@/components/ui';
import { COMMODITY_SCAN_EVENT, getCommodityCandles, type CommodityScanResponse, type CommoditySymbol } from '@/lib/commodityApi';

const STORAGE_KEY='alphapilot.commodityOutcomes.v1';
const CHECK_INTERVAL_MS=5*60*1000;
type Outcome='OPEN'|'T1 HIT'|'T2 HIT'|'SL HIT'|'AMBIGUOUS';
type Tracked={id:string;symbol:CommoditySymbol;contract:string;action:'BUY'|'SELL';captured_at:string;entry:number;stop:number;target1:number;target2:number|null;strength:number;rr:number|null;outcome:Outcome;resolved_at:string|null;resolved_price:number|null;last_checked_at:string|null;note?:string};
function load():Tracked[]{if(typeof window==='undefined')return[];try{const raw=localStorage.getItem(STORAGE_KEY);const parsed=raw?JSON.parse(raw):[];return Array.isArray(parsed)?parsed:[]}catch{return[]}}
function save(rows:Tracked[]){localStorage.setItem(STORAGE_KEY,JSON.stringify(rows.slice(0,100)));}
function n(v:unknown){const x=Number(v);return Number.isFinite(x)?x:null}
function candleTime(v:unknown){if(v==null)return NaN;if(typeof v==='number'||/^\d+$/.test(String(v))){let x=Number(v);if(x>1e12)x/=1000;return x*1000;}const t=new Date(String(v)).getTime();return t;}
function toTracked(r:CommodityScanResponse):Tracked|null{if(r.execution_ready!==true)return null;const entry=n(r.entry),stop=n(r.stop_loss),t1=n(r.target1),t2=n(r.target2);if(entry==null||stop==null||t1==null)return null;const action=String(r.action).toUpperCase();if(action!=='BUY'&&action!=='SELL')return null;return{id:`${r.symbol}-${r.contract?.trading_symbol??''}-${Date.now()}`,symbol:String(r.symbol).toUpperCase() as CommoditySymbol,contract:String(r.contract?.trading_symbol??r.contract?.groww_symbol??''),action:action as 'BUY'|'SELL',captured_at:new Date().toISOString(),entry,stop,target1:t1,target2:t2,strength:Number(r.alpha_score??0),rr:n(r.risk_reward),outcome:'OPEN',resolved_at:null,resolved_price:null,last_checked_at:null};}
function duplicate(rows:Tracked[],x:Tracked){return rows.some(r=>r.outcome==='OPEN'&&r.symbol===x.symbol&&r.action===x.action&&r.contract===x.contract&&Math.abs(r.entry-x.entry)<1e-9&&Math.abs(r.stop-x.stop)<1e-9&&Math.abs(r.target1-x.target1)<1e-9)}
function resolve(row:Tracked,candles:any[]):Tracked{const start=new Date(row.captured_at).getTime();for(const c of candles){if(!Array.isArray(c)||c.length<5)continue;const ts=candleTime(c[0]);if(!Number.isFinite(ts)||ts<start)continue;const high=Number(c[2]),low=Number(c[3]);if(!Number.isFinite(high)||!Number.isFinite(low))continue;const stopHit=row.action==='BUY'?low<=row.stop:high>=row.stop;const t1Hit=row.action==='BUY'?high>=row.target1:low<=row.target1;const t2Hit=row.target2!=null&&(row.action==='BUY'?high>=row.target2:low<=row.target2);if(stopHit&&(t1Hit||t2Hit))return{...row,outcome:'AMBIGUOUS',resolved_at:new Date(ts).toISOString(),resolved_price:null,note:'One 5m candle touched both stop and target; intrabar order is unknown.'};if(t2Hit)return{...row,outcome:'T2 HIT',resolved_at:new Date(ts).toISOString(),resolved_price:row.target2};if(t1Hit)return{...row,outcome:'T1 HIT',resolved_at:new Date(ts).toISOString(),resolved_price:row.target1};if(stopHit)return{...row,outcome:'SL HIT',resolved_at:new Date(ts).toISOString(),resolved_price:row.stop};}return row;}

export function CommodityOutcomeTracker(){const[rows,setRows]=useState<Tracked[]>(()=>load());const[open,setOpen]=useState(false);const[checking,setChecking]=useState(false);const checkingRef=useRef(false);
useEffect(()=>{const onScan=(event:Event)=>{const r=(event as CustomEvent<CommodityScanResponse>).detail;if(!r)return;const x=toTracked(r);if(!x)return;setRows(prev=>{if(duplicate(prev,x))return prev;const next=[x,...prev].slice(0,100);save(next);return next;});};window.addEventListener(COMMODITY_SCAN_EVENT,onScan);return()=>window.removeEventListener(COMMODITY_SCAN_EVENT,onScan)},[]);
const checkOpen=async()=>{if(checkingRef.current)return;checkingRef.current=true;setChecking(true);try{const current=load();const next=[...current];for(let i=0;i<next.length;i++){const row=next[i];if(row.outcome!=='OPEN')continue;try{const data=await getCommodityCandles(row.symbol,'5m');const candles=Array.isArray(data?.candles)?data.candles:[];next[i]={...resolve(row,candles),last_checked_at:new Date().toISOString()};}catch{next[i]={...row,last_checked_at:new Date().toISOString(),note:row.note??'Outcome refresh failed; will retry.'};}}save(next);setRows(next);}finally{checkingRef.current=false;setChecking(false)}};
useEffect(()=>{void checkOpen();const timer=window.setInterval(()=>void checkOpen(),CHECK_INTERVAL_MS);return()=>window.clearInterval(timer)},[]);
const stats=useMemo(()=>({open:rows.filter(r=>r.outcome==='OPEN').length,t1:rows.filter(r=>r.outcome==='T1 HIT').length,t2:rows.filter(r=>r.outcome==='T2 HIT').length,sl:rows.filter(r=>r.outcome==='SL HIT').length,amb:rows.filter(r=>r.outcome==='AMBIGUOUS').length}),[rows]);
const clear=()=>{localStorage.removeItem(STORAGE_KEY);setRows([])};
return <Card><CardHeader title="Commodity Outcome Tracking" subtitle="Execution-ready MCX setups only. Outcomes are checked from subsequent 5m candle highs/lows every 5 minutes while AlphaPilot is open." action={<div className="flex items-center gap-2"><Badge variant="blue">{stats.open} OPEN</Badge><Button size="sm" variant="ghost" onClick={()=>void checkOpen()} disabled={checking}><RefreshCw size={13} className={`inline mr-1 ${checking?'animate-spin':''}`}/>Refresh</Button>{rows.length>0&&<Button size="sm" variant="ghost" onClick={clear}><Trash2 size={13} className="inline mr-1"/>Clear</Button>}<Button size="sm" variant="ghost" onClick={()=>setOpen(v=>!v)}>{open?<ChevronUp size={14} className="inline mr-1"/>:<ChevronDown size={14} className="inline mr-1"/>}{open?'Collapse':`Expand (${rows.length})`}</Button></div>}/>{open&&<CardBody className="space-y-3"><div className="grid grid-cols-2 md:grid-cols-5 gap-2"><Metric label="Open" value={stats.open}/><Metric label="T1" value={stats.t1}/><Metric label="T2" value={stats.t2}/><Metric label="SL" value={stats.sl}/><Metric label="Ambiguous" value={stats.amb}/></div><p className="text-xs text-slate-500">Closed-session snapshots and WATCH setups are never enrolled. If a single 5m candle touches both stop and target, AlphaPilot records AMBIGUOUS rather than assuming intrabar order.</p>{rows.length?rows.map(r=><Row key={r.id} row={r}/>):<p className="text-xs text-slate-500">No execution-ready commodity setup has been captured yet.</p>}</CardBody>}</Card>}
function Row({row}:{row:Tracked}){const variant=row.outcome==='SL HIT'?'red':row.outcome==='T1 HIT'||row.outcome==='T2 HIT'?'green':row.outcome==='AMBIGUOUS'?'amber':'blue';return <div className="rounded-lg border border-slate-200 dark:border-slate-800 p-3"><div className="flex flex-wrap justify-between gap-2"><div><div className="flex items-center gap-2"><b>{row.symbol}</b><Badge variant={row.action==='BUY'?'green':'red'}>{row.action}</Badge><Badge variant={variant as any}>{row.outcome}</Badge></div><p className="text-xs text-slate-500 mt-1">{fmt(row.captured_at)} · {row.contract||'MCX FUT'}</p></div><div className="text-right text-xs"><p>Entry <b>{money(row.entry)}</b> · SL <b>{money(row.stop)}</b></p><p>T1 <b>{money(row.target1)}</b>{row.target2!=null?<> · T2 <b>{money(row.target2)}</b></>:null}</p></div></div>{row.resolved_at&&<p className="text-xs mt-2 text-slate-500">Resolved {fmt(row.resolved_at)}{row.resolved_price!=null?` at ${money(row.resolved_price)}`:''}</p>}{row.note&&<p className="text-xs mt-1 text-amber-600">{row.note}</p>}</div>}
function Metric({label,value}:{label:string;value:number}){return <div className="rounded-md border border-slate-200 dark:border-slate-800 p-2"><p className="text-[10px] text-slate-500">{label}</p><p className="font-semibold">{value}</p></div>}
function money(v:number){return `₹${v.toFixed(2)}`}
function fmt(v:string){const d=new Date(v);return Number.isNaN(d.getTime())?v:d.toLocaleString('en-IN',{timeZone:'Asia/Kolkata',hour12:true})}
