import { useEffect, useMemo, useState } from 'react';
import { ChevronDown, ChevronUp, Trash2 } from 'lucide-react';
import { Badge, Button, Card, CardBody, CardHeader } from '@/components/ui';
import { COMMODITY_SCAN_EVENT, type CommodityScanResponse } from '@/lib/commodityApi';

const STORAGE_KEY='alphapilot.commodityValidation.v1';
const LATEST_COUNT=5;
type Entry={id:string;captured_at:string;symbol:string;action:string;strength:number;status:string;session:string;execution_ready:boolean;entry:number|null;stop:number|null;rr:number|null;blockers:string[];timeframes:Record<string,{signal:string;alpha:number|null;rsi:number|null;latest:string|null;fresh:boolean}>};
function load():Entry[]{if(typeof window==='undefined')return[];try{const raw=localStorage.getItem(STORAGE_KEY);const parsed=raw?JSON.parse(raw):[];return Array.isArray(parsed)?parsed:[]}catch{return[]}}
function save(entries:Entry[]){localStorage.setItem(STORAGE_KEY,JSON.stringify(entries.slice(0,100)));}
function toEntry(result:CommodityScanResponse,capturedAt?:string):Entry{return{id:`${Date.now()}-${result.symbol}`,captured_at:capturedAt??new Date().toISOString(),symbol:String(result.symbol),action:String(result.action??'NO TRADE'),strength:Number(result.alpha_score??0),status:String(result.status??'—'),session:String(result.market_session?.status??'—'),execution_ready:result.execution_ready===true,entry:num(result.entry),stop:num(result.stop_loss),rr:num(result.risk_reward),blockers:Array.isArray(result.blockers)?result.blockers.map(String):[],timeframes:Object.fromEntries(['5m','15m','1h'].map(tf=>{const row=result.timeframes?.[tf]??{};return[tf,{signal:String(row.signal??'NO TRADE'),alpha:num(row.alpha_score),rsi:num(row.rsi14),latest:row.latest_candle_at?String(row.latest_candle_at):null,fresh:row.fresh===true}]}) )}}
function sameSnapshot(a:Entry|undefined,b:Entry){if(!a||a.symbol!==b.symbol||a.action!==b.action||a.session!==b.session||a.strength!==b.strength)return false;return ['5m','15m','1h'].every(tf=>a.timeframes?.[tf]?.latest===b.timeframes?.[tf]?.latest)}

export function CommodityValidationLog(){const[entries,setEntries]=useState<Entry[]>(()=>load());const[latestOpen,setLatestOpen]=useState(false);const[historyOpen,setHistoryOpen]=useState(false);
useEffect(()=>{const onScan=(event:Event)=>{const detail=(event as CustomEvent<CommodityScanResponse&{captured_at?:string}>).detail;if(!detail?.symbol)return;setEntries(prev=>{const entry=toEntry(detail,detail.captured_at);if(sameSnapshot(prev[0],entry))return prev;const next=[entry,...prev].slice(0,100);save(next);return next})};window.addEventListener(COMMODITY_SCAN_EVENT,onScan);return()=>window.removeEventListener(COMMODITY_SCAN_EVENT,onScan)},[]);
const latest=useMemo(()=>entries.slice(0,LATEST_COUNT),[entries]);const history=useMemo(()=>entries.slice(LATEST_COUNT),[entries]);const clear=()=>{localStorage.removeItem(STORAGE_KEY);setEntries([])};
return <div className="space-y-3"><Card><CardHeader title="Commodity Live Validation" subtitle="Browser-local CRUDEOIL/NATURALGAS scan history. Closed-session duplicate snapshots are collapsed." action={<div className="flex items-center gap-2"><Badge variant="blue">{entries.length} SAVED</Badge>{entries.length>0&&<Button size="sm" variant="ghost" onClick={clear}><Trash2 size={13} className="inline mr-1"/>Clear</Button>}</div>}/><CardBody><p className="text-xs text-slate-500">Commodity validation is isolated from NSE F&O logs so performance evidence does not mix across markets.</p></CardBody></Card><Card><CardHeader title="Latest Commodity Scans" subtitle={`Newest ${latest.length} completed MCX scans.`} action={<Button size="sm" variant="ghost" onClick={()=>setLatestOpen(v=>!v)}>{latestOpen?<ChevronUp size={14} className="inline mr-1"/>:<ChevronDown size={14} className="inline mr-1"/>}{latestOpen?'Collapse':`Expand (${latest.length})`}</Button>}/>{latestOpen&&<CardBody className="space-y-2">{latest.length?latest.map(e=><Row key={e.id} entry={e}/>):<p className="text-xs text-slate-500">No commodity scans saved yet.</p>}</CardBody>}</Card><Card><CardHeader title="Saved Commodity History" subtitle={`${history.length} older commodity scan${history.length===1?'':'s'}.`} action={<Button size="sm" variant="ghost" onClick={()=>setHistoryOpen(v=>!v)}>{historyOpen?<ChevronUp size={14} className="inline mr-1"/>:<ChevronDown size={14} className="inline mr-1"/>}{historyOpen?'Collapse':`Expand (${history.length})`}</Button>}/>{historyOpen&&<CardBody className="space-y-2">{history.length?history.map(e=><Row key={e.id} entry={e}/>):<p className="text-xs text-slate-500">No older commodity scans yet.</p>}</CardBody>}</Card></div>}

function Row({entry}:{entry:Entry}){return <div className="rounded-lg border border-slate-200 dark:border-slate-800 p-3"><div className="flex flex-wrap items-center justify-between gap-2"><div><div className="flex items-center gap-2"><b>{entry.symbol}</b><Badge variant={entry.action==='BUY'?'green':entry.action==='SELL'?'red':'default'}>{entry.action}</Badge><Badge variant={entry.execution_ready?'green':'blue'}>{entry.execution_ready?'READY':entry.status}</Badge></div><p className="text-xs text-slate-500 mt-1">{formatTime(entry.captured_at)} · {entry.session}</p></div><div className="text-right"><p className="text-[10px] text-slate-500">Directional Strength</p><p className="font-semibold">{entry.strength.toFixed(1)}/100</p><p className="text-xs text-slate-500">R:R {entry.rr==null?'—':`${entry.rr.toFixed(2)}:1`}</p></div></div><div className="grid grid-cols-1 sm:grid-cols-3 gap-2 mt-3">{['5m','15m','1h'].map(tf=>{const row=entry.timeframes[tf];return <div key={tf} className="rounded-md bg-slate-50 dark:bg-slate-900/60 px-3 py-2 text-xs"><span className="text-slate-500">{tf}</span><p className="font-semibold mt-0.5">{row?.signal} · Raw Alpha {row?.alpha==null?'—':row.alpha.toFixed(1)}</p><p className="text-[11px] text-slate-500">RSI {row?.rsi==null?'—':row.rsi.toFixed(1)} · {row?.fresh?'FRESH':'SNAPSHOT'}</p></div>})}</div>{entry.blockers[0]&&<p className="text-xs text-amber-600 mt-2">Primary blocker: {entry.blockers[0]}</p>}</div>}
function num(value:unknown){const n=Number(value);return Number.isFinite(n)?n:null}
function formatTime(value:string|null|undefined){if(!value)return'—';const d=new Date(value);return Number.isNaN(d.getTime())?String(value):d.toLocaleString('en-IN',{timeZone:'Asia/Kolkata',hour12:true})}
