import { useEffect, useState } from 'react';
import { Activity, AlertTriangle, Download, MoonStar } from 'lucide-react';
import { Badge, Button, Card, CardBody, CardHeader } from '@/components/ui';
import { runCommodityNextSession, type CommodityNextSessionResponse, type CommodityNextSessionResult } from '@/lib/commodityApi';

const STORAGE_KEY='alphapilot:commodity-next-session-v1';
const FIXED_DATES={monday:'2026-08-24',tuesday:'2026-08-25',wednesday:'2026-08-26'};
type Ledger={backtest:CommodityNextSessionResponse;forecast:CommodityNextSessionResponse;saved_at:string};

export function CommodityNextSession(){
  const[ledger,setLedger]=useState<Ledger|null>(null);const[loading,setLoading]=useState(false);const[error,setError]=useState<string|null>(null);
  useEffect(()=>{try{const raw=localStorage.getItem(STORAGE_KEY);if(raw)setLedger(JSON.parse(raw) as Ledger)}catch{localStorage.removeItem(STORAGE_KEY)}},[]);
  const run=async()=>{setLoading(true);setError(null);try{
    const backtest=await runCommodityNextSession({observation_date:FIXED_DATES.monday,target_date:FIXED_DATES.tuesday,include_outcome:true,include_news:false});
    assertSafe(backtest);
    const forecast=await runCommodityNextSession({observation_date:FIXED_DATES.tuesday,target_date:FIXED_DATES.wednesday,include_outcome:false,include_news:true});
    assertSafe(forecast);
    const next={backtest,forecast,saved_at:new Date().toISOString()};localStorage.setItem(STORAGE_KEY,JSON.stringify(next));setLedger(next);
  }catch(e){setError(e instanceof Error?e.message:'Prototype run failed.')}finally{setLoading(false)}};
  const download=()=>{if(!ledger)return;const blob=new Blob([JSON.stringify(ledger,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`alphapilot-commodity-next-session-v1-${FIXED_DATES.wednesday}.json`;a.click();URL.revokeObjectURL(url)};
  return <div className="space-y-5"><div><h1 className="text-xl font-bold text-slate-900 dark:text-white">Commodity Next-Session Prototype</h1><p className="text-sm text-slate-500">Observe a complete MCX session, issue a BUY CE / BUY PE next-day plan or NO TRADE, then score the underlying direction without look-ahead.</p></div>
  <Card><CardHeader title="Tonight's Two-Step Validation" subtitle="Monday 24 Aug → Tuesday 25 Aug backtest, then Tuesday 25 Aug → Wednesday 26 Aug setup." action={<Badge variant="blue">BUY OPTIONS ONLY</Badge>}/><CardBody className="space-y-4"><div className="grid grid-cols-2 md:grid-cols-5 gap-3"><Metric label="Markets" value="Crude · Natural Gas"/><Metric label="Observation" value="09:00–23:30 IST"/><Metric label="Signal Gate" value="3 of 5 votes"/><Metric label="Target" value="1.5R"/><Metric label="Max Risk" value="1%"/></div><div className="rounded-lg border border-amber-200 dark:border-amber-900 p-3 text-xs text-slate-600 dark:text-slate-400"><b className="text-amber-600">Proxy limitation:</b> BUY CE/PE expresses direction only. Entry, stop, target and R are calculated on the underlying MCX future; commodity-option premium P&amp;L is not yet backtested. No selling is permitted.</div><div className="rounded-lg border border-amber-200 dark:border-amber-900 p-3 text-xs text-slate-600 dark:text-slate-400"><b className="text-amber-600">News integrity:</b> current headlines appear beside Wednesday's plan as risk context only. Monday's uncaptured news is marked unavailable and is never recreated after Tuesday's outcome.</div><div className="flex flex-wrap gap-2"><Button variant="primary" onClick={()=>void run()} disabled={loading}>{loading?<Activity size={14} className="inline mr-1 animate-spin"/>:<MoonStar size={14} className="inline mr-1"/>}{loading?'Running sequentially…':'Run Two-Step Prototype'}</Button>{ledger&&<Button variant="default" onClick={download}><Download size={14} className="inline mr-1"/>Export Evidence</Button>}</div>{error&&<div className="rounded-lg border border-red-200 dark:border-red-900 p-3 text-xs text-red-600">{error}</div>}</CardBody></Card>
  {ledger&&<><Cycle title="Monday → Tuesday Backtest" response={ledger.backtest}/><Cycle title="Tuesday → Wednesday Setup" response={ledger.forecast}/><p className="text-xs text-slate-500">Saved {formatDate(ledger.saved_at)} · Dormant F&O research remains unchanged and no commodity order is authorized.</p></>}
  </div>;
}

function assertSafe(value:CommodityNextSessionResponse){if(!value.research_only||value.production_rules_changed||value.paper_trading_permission_changed||value.live_execution_enabled)throw new Error('Backend safety metadata does not match the frozen research-only protocol.');}
function Cycle({title,response}:{title:string;response:CommodityNextSessionResponse}){return <Card><CardHeader title={title} subtitle={`${response.observation_date} observation · ${response.target_date} target`} action={<Badge variant={response.include_outcome?'default':'blue'}>{response.include_outcome?'OUTCOME SCORED':'PRE-SESSION PLAN'}</Badge>}/><CardBody className="space-y-3">{response.results.map(result=><ResultCard key={result.symbol} result={result}/>)}</CardBody></Card>}
function ResultCard({result}:{result:CommodityNextSessionResult}){const variant=result.status==='SETUP'?(result.action==='BUY CE'?'green':'red'):result.status==='NO_TRADE'?'default':'red';return <div className="rounded-lg border border-slate-200 dark:border-slate-800 p-4 space-y-3"><div className="flex flex-wrap justify-between gap-3"><div><div className="flex items-center gap-2"><b>{result.symbol}</b><Badge variant={variant}>{result.action}</Badge><Badge variant="default">{result.status.replaceAll('_',' ')}</Badge></div><p className="text-xs text-slate-500 mt-1">{result.contract?.trading_symbol??'Contract unavailable'} · {result.observed_candles} completed bars · score {result.features?.directional_score??'—'}/5</p></div><div className="text-right"><p className="text-sm font-semibold">{result.outcome?result.outcome.outcome.replaceAll('_',' '):'Awaiting target session'}</p><p className="text-xs text-slate-500">{result.outcome?`${Number(result.outcome.r_multiple).toFixed(2)}R proxy`:`Confidence ${Number(result.confidence_pct??0).toFixed(0)}%`}</p></div></div>
  {result.status==='SETUP'&&<div className="grid grid-cols-2 md:grid-cols-5 gap-2"><Metric label="Entry Trigger" value={price(result.entry)}/><Metric label="Stop" value={price(result.stop_loss)}/><Metric label="Target" value={price(result.target1)}/><Metric label="Risk" value={`${Number(result.risk_points??0).toFixed(2)} pts`}/><Metric label="R:R" value={`${Number(result.risk_reward??0).toFixed(1)}:1`}/></div>}
  {result.features&&<div className="grid grid-cols-2 md:grid-cols-5 gap-2"><Mini label="Session Return" value={`${result.features.session_return_pct.toFixed(2)}%`}/><Mini label="Close Location" value={`${result.features.close_location_pct.toFixed(0)}%`}/><Mini label="Last Hour" value={`${result.features.last_hour_return_pct.toFixed(2)}%`}/><Mini label="ATR" value={result.features.daily_atr.toFixed(2)}/><Mini label="Volume / 5d" value={result.features.volume_vs_prior_5==null?'Unavailable':`${result.features.volume_vs_prior_5.toFixed(2)}×`}/></div>}
  <p className="text-xs text-slate-500">{result.reason}</p><NewsContext result={result}/></div>}
function NewsContext({result}:{result:CommodityNextSessionResult}){const news=result.news_context;if(news.status==='UNAVAILABLE_NOT_RECONSTRUCTED')return <div className="flex gap-2 text-xs text-amber-600"><AlertTriangle size={14}/>{news.reason}</div>;return <div className="rounded-lg bg-slate-50 dark:bg-slate-900 p-3"><p className="text-xs font-semibold">News context · {news.status.replaceAll('_',' ')}</p>{news.event_tags?.length?<p className="text-xs text-slate-500 mt-1">Events: {news.event_tags.join(', ')}</p>:null}{news.items.slice(0,3).map((item,index)=><p key={`${item.url}-${index}`} className="text-xs text-slate-500 mt-1">• {item.sentiment}: {item.headline} ({item.source})</p>)}{!news.items.length&&news.reason?<p className="text-xs text-amber-600 mt-1">{news.reason}</p>:null}<p className="text-[10px] text-slate-400 mt-2">Context only; headlines cannot create, reverse, or authorize this setup.</p></div>}
function Metric({label,value}:{label:string;value:string}){return <div className="rounded-lg border border-slate-200 dark:border-slate-800 p-3"><p className="text-[10px] text-slate-500">{label}</p><p className="text-sm font-semibold mt-1">{value}</p></div>}
function Mini({label,value}:{label:string;value:string}){return <div><p className="text-[10px] text-slate-500">{label}</p><p className="text-sm font-semibold">{value}</p></div>}
function price(value?:number){return value==null?'—':`₹${value.toFixed(2)}`}
function formatDate(value:string){return new Date(value).toLocaleString('en-IN',{timeZone:'Asia/Kolkata',hour12:true})}
