import { useMemo, useState } from 'react';
import { AlertTriangle, CheckCircle2, Eye, EyeOff, RefreshCw, XCircle } from 'lucide-react';
import { Badge, Button, Card, CardBody, CardHeader, Input, Table, TableCell, TableRow } from '@/components/ui';
import { getCurrentMindDataIntegrity,getCurrentMindProviderParity,getCurrentMindReplayStatus,readCurrentMindToken,startCurrentMindReplay,storeCurrentMindToken,type CurrentMindReplay,type DataIntegrityAudit,type ProviderParityAudit,type ReplayDecisionRow } from '@/lib/currentMindAuditApi';

type BadgeTone='default'|'green'|'red'|'blue'|'amber'|'purple';
const decisionTone=(a?:string):BadgeTone=>a==='BUY_CE'?'green':a==='BUY_PE'?'red':a==='WAIT'?'amber':'default';
const outcomeTone=(o?:string):BadgeTone=>o==='TARGET'?'green':o==='STOP'?'red':o==='NO_ENTRY'||o==='SESSION_END'?'amber':'default';

export function CurrentMindAudit(){
 const[token,setToken]=useState(readCurrentMindToken);const[showToken,setShowToken]=useState(false);const[replay,setReplay]=useState<CurrentMindReplay|null>(null);const[data,setData]=useState<DataIntegrityAudit|null>(null);const[parity,setParity]=useState<ProviderParityAudit|null>(null);const[status,setStatus]=useState('NOT LOADED');const[loading,setLoading]=useState(false);const[error,setError]=useState<string|null>(null);const[actionFilter,setActionFilter]=useState('ALL');const[outcomeFilter,setOutcomeFilter]=useState('ALL');
 const saveToken=()=>{storeCurrentMindToken(token);setStatus(token.trim()?'TOKEN SAVED FOR THIS TAB':'TOKEN CLEARED')};
 const refresh=async()=>{setLoading(true);setError(null);try{storeCurrentMindToken(token);const[job,d,p]=await Promise.all([getCurrentMindReplayStatus(token),getCurrentMindDataIntegrity(token),getCurrentMindProviderParity(token)]);setStatus(job.status);setReplay(job.result??null);setData(d);setParity(p)}catch(e){setError(e instanceof Error?e.message:'Audit refresh failed.')}finally{setLoading(false)}};
 const start=async()=>{setLoading(true);setError(null);try{storeCurrentMindToken(token);const r=await startCurrentMindReplay(token);setStatus(r.status)}catch(e){setError(e instanceof Error?e.message:'Replay start failed.')}finally{setLoading(false)}};
 const rows=useMemo(()=>{const all=replay?.decisions??[];return all.filter(x=>(actionFilter==='ALL'||x.decision?.action===actionFilter)&&(outcomeFilter==='ALL'||(x.outcome?.result??(x.outcome?.future_move_without_setup?'MISSED_MOVE':'ABSTENTION'))===outcomeFilter))},[replay,actionFilter,outcomeFilter]);
 const allDataChecks=data?Object.values(data.checks).every(Boolean):false;const allParityChecks=parity?Object.values(parity.checks).every(Boolean):false;
 return <div className="space-y-5">
  <div className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="text-xl font-bold text-slate-900 dark:text-white">Copper Current Mind Audit</h1><p className="text-sm text-slate-500">Manual inspection of the frozen Current Mind v1 replay, data integrity and Groww parity.</p></div><div className="flex items-center gap-2"><Badge variant="purple">RESEARCH ONLY</Badge><Badge variant="blue">CURRENT MIND v1 FROZEN</Badge></div></div>
  <Card><CardHeader title="Internal Audit Access" subtitle="Token is kept only in this browser tab's sessionStorage; it is not written to the repository." action={<Badge variant={status==='COMPLETED'?'green':status==='FAILED'?'red':status==='RUNNING'?'amber':'default'}>{status}</Badge>}/><CardBody className="space-y-3"><div className="grid grid-cols-1 md:grid-cols-[1fr_auto] gap-3"><div className="relative"><Input label="Internal audit token" type={showToken?'text':'password'} value={token} onChange={setToken} placeholder="Paste COMMODITY_COLLECTOR_TOKEN"/><button className="absolute right-3 bottom-2 text-slate-400" onClick={()=>setShowToken(v=>!v)}>{showToken?<EyeOff size={16}/>:<Eye size={16}/>}</button></div><div className="flex items-end gap-2"><Button onClick={saveToken}>Save for tab</Button><Button variant="primary" onClick={()=>void refresh()} disabled={loading}>{loading?<RefreshCw size={14} className="inline mr-1 animate-spin"/>:<RefreshCw size={14} className="inline mr-1"/>}Refresh Audits</Button><Button variant="ghost" onClick={()=>void start()} disabled={loading}>Start Replay</Button></div></div>{error&&<div className="rounded-lg border border-red-200 dark:border-red-900 p-3 text-xs text-red-600">{error}</div>}<p className="text-xs text-slate-500">The UI never fabricates historical option premium, IV, Greeks or option P&amp;L. Replay expectancy shown below is underlying structural R only.</p></CardBody></Card>
  <div className="grid grid-cols-1 lg:grid-cols-2 gap-4"><AuditCard title="Stored Replay Data Integrity" ok={allDataChecks} loaded={Boolean(data)} lines={data?[['Raw / Clean',`${data.raw_candles} / ${data.clean_candles}`],['Complete Sessions',`${data.exact_100pct_complete_sessions} / ${data.complete_sessions}`],['Dropped / Duplicates',`${data.dropped_by_ohlcv_cleaning} / ${data.duplicate_timestamp_count}`],['Missing Bars / Outside Session',`${data.missing_bars_inside_primary_complete_sessions} / ${data.outside_session_bars}`],['Excluded',data.partial_or_ineligible_sessions.join(', ')||'None']]:[]}/><AuditCard title="Stored ↔ Groww Provider Parity" ok={allParityChecks} loaded={Boolean(parity)} lines={parity?[['Provider / Stored / Shared',`${parity.provider_rows} / ${parity.stored_rows} / ${parity.shared_rows}`],['Timestamp Extras',`${parity.provider_only_timestamps} provider · ${parity.stored_only_timestamps} stored`],['OHLC / Volume / OI mismatches',`${parity.ohlc_mismatch_count} / ${parity.volume_mismatch_count} / ${parity.oi_mismatch_count_when_both_present}`],['OHLC Hash',parity.provider_ohlc_digest===parity.stored_ohlc_digest?'IDENTICAL':'DIFFERENT'],['MCX Independent Certification','Not yet certified']]:[]}/></div>
  {replay?<><Card><CardHeader title="Frozen Replay Result" subtitle={`${replay.reference_contract} · ${replay.complete_sessions} complete sessions · partial Aug 27/28 excluded`} action={<Badge variant={replay.click_coverage_exact?'green':'red'}>{replay.scheduled_clicks}/{replay.evaluated_clicks} CLICKS</Badge>}/><CardBody className="space-y-4"><div className="grid grid-cols-2 md:grid-cols-5 lg:grid-cols-10 gap-3"><Metric label="BUY CE" value={String(replay.actions.BUY_CE??0)}/><Metric label="BUY PE" value={String(replay.actions.BUY_PE??0)}/><Metric label="WAIT" value={String(replay.actions.WAIT??0)}/><Metric label="NO TRADE" value={String(replay.actions.NO_TRADE??0)}/><Metric label="Targets" value={String(replay.targets)}/><Metric label="Stops" value={String(replay.stops)}/><Metric label="No Entry" value={String(replay.no_entry)}/><Metric label="Session End" value={String(replay.session_end)}/><Metric label="Expectancy" value={replay.expectancy_r_resolved==null?'—':`${replay.expectancy_r_resolved.toFixed(3)}R`}/><Metric label="Missed Moves" value={String(replay.missed_large_moves_after_abstention)}/></div><div className="rounded-lg border border-amber-200 dark:border-amber-900 p-3 text-xs text-slate-500"><AlertTriangle size={14} className="inline mr-1 text-amber-600"/>Market Brain forms the Copper underlying thesis. CE/PE here expresses directional intent only; genuine historical option premiums are unavailable for this window, so this is not option-profitability evidence.</div></CardBody></Card>
  <Card><CardHeader title="Decision Ledger" subtitle={`Showing ${rows.length} of ${replay.decisions.length} evaluated clicks`} action={<div className="flex gap-2"><select value={actionFilter} onChange={e=>setActionFilter(e.target.value)} className="text-xs rounded-lg border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-900 px-2 py-1"><option>ALL</option><option>BUY_CE</option><option>BUY_PE</option><option>WAIT</option><option>NO_TRADE</option></select><select value={outcomeFilter} onChange={e=>setOutcomeFilter(e.target.value)} className="text-xs rounded-lg border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-900 px-2 py-1"><option>ALL</option><option>TARGET</option><option>STOP</option><option>NO_ENTRY</option><option>SESSION_END</option><option>MISSED_MOVE</option><option>ABSTENTION</option></select></div>}/><CardBody className="p-0"><Table headers={['Click','Action','Reason','Direction','Entry / Stop / Target','Outcome','R','MFE / MAE','Evidence / Missing']} >{rows.map((r,i)=><DecisionRow key={`${r.click_timestamp}-${i}`} row={r}/>)}</Table></CardBody></Card></>:<Card><CardBody><p className="text-sm text-slate-500">Refresh audits after entering the token to load the latest completed replay and every click-level decision.</p></CardBody></Card>}
 </div>
}
function AuditCard({title,ok,loaded,lines}:{title:string;ok:boolean;loaded:boolean;lines:[string,string][]}){return <Card><CardHeader title={title} action={loaded?(ok?<Badge variant="green">PASS</Badge>:<Badge variant="red">REVIEW</Badge>):<Badge>NOT LOADED</Badge>}/><CardBody>{!loaded?<p className="text-xs text-slate-500">Refresh to load.</p>:<div className="space-y-2">{lines.map(([k,v])=><div key={k} className="flex justify-between gap-4 text-xs"><span className="text-slate-500">{k}</span><span className="font-semibold text-right break-all">{v}</span></div>)}<div className={`flex items-center gap-2 pt-2 text-xs font-semibold ${ok?'text-emerald-600':'text-red-600'}`}>{ok?<CheckCircle2 size={14}/>:<XCircle size={14}/>} {ok?'All automated checks passed':'One or more checks need review'}</div></div>}</CardBody></Card>}
function Metric({label,value}:{label:string;value:string}){return <div className="rounded-lg border border-slate-200 dark:border-slate-800 p-3"><p className="text-[10px] text-slate-500">{label}</p><p className="text-sm font-semibold mt-1">{value}</p></div>}
function DecisionRow({row}:{row:ReplayDecisionRow}){const d=row.decision??{},o=row.outcome??{},lv=d.replay_levels??{};const outcome=o.result??(o.future_move_without_setup?'MISSED_MOVE':'ABSTENTION');return <TableRow><TableCell>{fmt(row.click_timestamp)}</TableCell><TableCell><Badge variant={decisionTone(d.action)}>{d.action??'—'}</Badge></TableCell><TableCell className="max-w-[220px] whitespace-normal">{d.reason??'—'}</TableCell><TableCell>{d.direction??'—'}</TableCell><TableCell>{num(lv.entry)} / {num(lv.stop)} / {num(lv.target)}</TableCell><TableCell><Badge variant={outcomeTone(String(outcome))}>{String(outcome).replaceAll('_',' ')}</Badge></TableCell><TableCell>{o.realized_r==null?'—':`${Number(o.realized_r).toFixed(2)}R`}</TableCell><TableCell>{o.mfe_r==null?'—':`${Number(o.mfe_r).toFixed(2)} / ${Number(o.mae_r??0).toFixed(2)}R`}</TableCell><TableCell className="max-w-[260px] whitespace-normal text-xs">{[...(row.evidence?.contradictory_lanes??[]).map(x=>`Conflict: ${x}`),...(d.missing_context??[]).map(x=>`Missing: ${x}`)].join(' · ')||'—'}</TableCell></TableRow>}
function fmt(v:string){const d=new Date(v);return Number.isNaN(d.getTime())?v:d.toLocaleString('en-IN',{timeZone:'Asia/Kolkata',day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit',hour12:true})}
function num(v:unknown){const n=Number(v);return Number.isFinite(n)?n.toFixed(2):'—'}
