import { useEffect, useMemo, useState } from 'react';
import { ChevronDown, ChevronUp } from 'lucide-react';
import { Badge, Button, Card, CardBody, CardHeader } from '@/components/ui';
import { FNO_SCAN_EVENT, type FnoScanResponse } from '@/lib/alphaPilotApi';

const STORAGE_KEY='alphapilot.liveScanValidationLog.v1';
const MAX_ENTRIES=100,LATEST_COUNT=5,LIVE_TIMEFRAMES=['5m','15m','1h'];
type ValidationEntry={id:string;captured_at:string;symbol:string;decision:string;technical_score:number|null;fno_score:number|null;alpha_score:number|null;option_rr:number|null;execution_ready:boolean;blockers:string[];session_status:string;timeframes:Record<string,{state:string;alpha:number|null;latest_candle_at:string|null}>};
function loadEntries():ValidationEntry[]{if(typeof window==='undefined')return[];try{const raw=window.localStorage.getItem(STORAGE_KEY);const parsed=raw?JSON.parse(raw):[];return Array.isArray(parsed)?parsed:[]}catch{return[]}}
function optionRiskReward(result:FnoScanResponse){const o=result.recommended_option??{},entry=Number(o.option_entry??o.premium),stop=Number(o.option_stop_loss),target=Number(o.option_target1),risk=entry-stop,reward=target-entry;return [entry,stop,target,risk,reward].every(Number.isFinite)&&risk>0&&reward>0?reward/risk:null}
function optionState(value:unknown){const s=String(value??'—').toUpperCase();if(s==='LONG'||s==='BUY CE')return'BUY CE';if(s==='SHORT'||s==='BUY PE')return'BUY PE';if(['WATCH_LONG','WATCH LONG','WATCH BUY CE'].includes(s))return'WATCH BUY CE';if(['WATCH_SHORT','WATCH SHORT','WATCH BUY PE'].includes(s))return'WATCH BUY PE';if(s==='STRONG_LONG'||s==='STRONG LONG')return'STRONG BUY CE';if(s==='STRONG_SHORT'||s==='STRONG SHORT')return'STRONG BUY PE';if(s==='NO_TRADE'||s==='NO TRADE')return'NO TRADE';return String(value??'—').replaceAll('_',' ')}
function toEntry(result:FnoScanResponse):ValidationEntry{const tf=result.technical?.timeframes??{},frames:ValidationEntry['timeframes']={};for(const name of LIVE_TIMEFRAMES){const row=tf[name]??{};frames[name]={state:optionState(row.direction??row.signal??row.market_structure??row.status??'—'),alpha:Number.isFinite(Number(row.alpha_score))?Number(row.alpha_score):null,latest_candle_at:typeof row.latest_candle_at==='string'?row.latest_candle_at:null}}const ready=result.execution_ready===true;return{id:`${Date.now()}-${result.symbol}`,captured_at:new Date().toISOString(),symbol:result.symbol,decision:optionState(ready?result.signal??'READY':result.status==='SETUP'?'BLOCKED SETUP':result.signal??result.status??'WAIT'),technical_score:Number.isFinite(Number(result.technical_score))?Number(result.technical_score):null,fno_score:Number.isFinite(Number(result.fno_score))?Number(result.fno_score):null,alpha_score:Number.isFinite(Number(result.overall_alpha_score))?Number(result.overall_alpha_score):null,option_rr:optionRiskReward(result),execution_ready:ready,blockers:Array.isArray(result.execution_blockers)?result.execution_blockers.map(String):[],session_status:String(result.market_session?.status??result.market_session?.phase??(result.market_session?.is_open?'OPEN':'CLOSED')),timeframes:frames}}
function isOpenSession(status:string){const s=status.toUpperCase();return s==='OPEN'||s==='CONTINUOUS'}
function sameClosedSnapshot(a:ValidationEntry|undefined,b:ValidationEntry){if(!a||isOpenSession(b.session_status))return false;if(a.symbol!==b.symbol||a.session_status!==b.session_status)return false;if(optionState(a.decision)!==optionState(b.decision)||a.alpha_score!==b.alpha_score||a.technical_score!==b.technical_score||a.fno_score!==b.fno_score)return false;return LIVE_TIMEFRAMES.every(tf=>{const l=a.timeframes?.[tf],r=b.timeframes?.[tf];return l?.latest_candle_at===r?.latest_candle_at&&optionState(l?.state)===optionState(r?.state)&&l?.alpha===r?.alpha})}
export function LiveScanValidationLog(){const[entries,setEntries]=useState<ValidationEntry[]>(()=>loadEntries());const[logOpen,setLogOpen]=useState(false);const[latestOpen,setLatestOpen]=useState(false);const[historyOpen,setHistoryOpen]=useState(false);
useEffect(()=>{const onScan=(event:Event)=>{const result=(event as CustomEvent<FnoScanResponse>).detail;if(!result?.symbol)return;setEntries(previous=>{const entry=toEntry(result);if(sameClosedSnapshot(previous[0],entry))return previous;const next=[entry,...previous].slice(0,MAX_ENTRIES);window.localStorage.setItem(STORAGE_KEY,JSON.stringify(next));return next})};window.addEventListener(FNO_SCAN_EVENT,onScan);return()=>window.removeEventListener(FNO_SCAN_EVENT,onScan)},[]);
const latest=useMemo(()=>entries.slice(0,LATEST_COUNT),[entries]),history=useMemo(()=>entries.slice(LATEST_COUNT),[entries]);const clear=()=>{window.localStorage.removeItem(STORAGE_KEY);setEntries([]);setHistoryOpen(false)};
return <div className="space-y-4">
<Card><CardHeader title="Live Scan Validation Log" subtitle="Browser-local validation capture for completed F&O scans. Identical closed-session snapshots are collapsed automatically." action={<div className="flex items-center gap-2">{entries.length?<Button size="sm" variant="ghost" onClick={clear}>Clear log</Button>:null}<Button size="sm" variant="ghost" onClick={()=>setLogOpen(v=>!v)}>{logOpen?<ChevronUp size={14} className="inline mr-1"/>:<ChevronDown size={14} className="inline mr-1"/>}{logOpen?'Collapse':'Expand'}</Button></div>}/>{logOpen&&<CardBody>{!entries.length?<p className="text-sm text-slate-500">No scans saved yet. Run Single Symbol or Find Trade; completed F&O confirmations will appear automatically.</p>:<div className="flex flex-wrap items-center gap-2 text-xs text-slate-500"><span>{entries.length} scan{entries.length===1?'':'s'} saved</span><span>· {latest.length} latest</span><span>· {history.length} saved history</span><span>· browser-local storage</span></div>}</CardBody>}</Card>
<Card><CardHeader title="Latest Scans" subtitle={`Newest ${latest.length} F&O confirmation${latest.length===1?'':'s'}.`} action={<Button size="sm" variant="ghost" onClick={()=>setLatestOpen(v=>!v)}>{latestOpen?<ChevronUp size={14} className="inline mr-1"/>:<ChevronDown size={14} className="inline mr-1"/>}{latestOpen?'Collapse':`Expand (${latest.length})`}</Button>}/>{latestOpen&&<CardBody className="space-y-2">{latest.length?latest.map(e=><ScanRow key={e.id} entry={e}/>):<p className="text-sm text-slate-500">No latest scans yet.</p>}</CardBody>}</Card>
<Card><CardHeader title="Saved Scan History" subtitle={`${history.length} older scan${history.length===1?'':'s'} preserved, newest first.`} action={<Button size="sm" variant="ghost" onClick={()=>setHistoryOpen(v=>!v)}>{historyOpen?<ChevronUp size={14} className="inline mr-1"/>:<ChevronDown size={14} className="inline mr-1"/>}{historyOpen?'Collapse':`Expand (${history.length})`}</Button>}/>{historyOpen&&<CardBody className="space-y-2">{history.length?history.map(e=><ScanRow key={e.id} entry={e}/>):<p className="text-sm text-slate-500">No older saved scans yet.</p>}</CardBody>}</Card>
</div>}
function ScanRow({entry}:{entry:ValidationEntry}){return <div className="rounded-lg border border-slate-200 dark:border-slate-800 p-3"><div className="flex flex-col lg:flex-row lg:items-start lg:justify-between gap-2"><div><div className="flex items-center gap-2 flex-wrap"><b>{entry.symbol}</b><Badge variant={entry.execution_ready?'green':'blue'}>{entry.execution_ready?'READY':'WAIT'}</Badge><Badge variant={isOpenSession(entry.session_status)?'green':'red'}>{entry.session_status}</Badge></div><p className="text-xs text-slate-500 mt-1">{formatTime(entry.captured_at)} · {optionState(entry.decision)}</p></div><div className="grid grid-cols-4 gap-4 text-right text-xs"><Mini label="Technical" value={score(entry.technical_score)}/><Mini label="F&O" value={score(entry.fno_score)}/><Mini label="Alpha" value={score(entry.alpha_score)}/><Mini label="Option R:R" value={entry.option_rr==null?'—':`${entry.option_rr.toFixed(2)}:1`}/></div></div><div className="grid grid-cols-1 sm:grid-cols-3 gap-2 mt-3">{LIVE_TIMEFRAMES.map(tf=>{const row=entry.timeframes[tf];return <div key={tf} className="rounded-md bg-slate-50 dark:bg-slate-900/60 px-3 py-2 text-xs"><span className="text-slate-500">{tf}</span><p className="font-semibold mt-0.5">{optionState(row?.state)} · {score(row?.alpha??null)}</p><p className="text-[11px] text-slate-500 mt-0.5">{formatTime(row?.latest_candle_at)}</p></div>})}</div>{entry.blockers.length>0&&<p className="text-xs text-amber-600 mt-2">Primary blocker: {entry.blockers[0]}</p>}</div>}
function Mini({label,value}:{label:string;value:string}){return <div><p className="text-[10px] text-slate-500">{label}</p><p className="font-semibold whitespace-nowrap">{value}</p></div>}
function score(value:number|null){return value==null||!Number.isFinite(value)?'—':`${value.toFixed(1)}/100`}
function formatTime(value:string|null|undefined){if(!value)return'—';const date=new Date(value);if(Number.isNaN(date.getTime()))return value;return date.toLocaleString('en-IN',{timeZone:'Asia/Kolkata',hour12:true})}
