import { useMemo, useState } from 'react';
import { AlertCircle, ScanLine, ShieldCheck } from 'lucide-react';
import { useStore } from '@/store/StoreContext';
import { Badge, Button, Card, CardBody, CardHeader, Input } from '@/components/ui';
import { scanFno, scanMtf, type FnoScanResponse, type MtfScanItem } from '@/lib/alphaPilotApi';
import type { PageKey } from '@/components/Sidebar';

const DEFAULT_SYMBOL = 'RELIANCE';
const LIVE_TIMEFRAMES = ['5m', '15m', '1h'];
const FIND_TRADE_SYMBOLS = [
  'RELIANCE','TCS','INFY','HDFCBANK','ICICIBANK','SBIN','AXISBANK','KOTAKBANK','INDUSINDBK','BAJFINANCE','BAJAJFINSV','LT','BHARTIARTL','ITC','HINDUNILVR','MARUTI','M&M','TATAMOTORS','SUNPHARMA','DRREDDY','CIPLA','DIVISLAB','APOLLOHOSP','WIPRO','HCLTECH','TECHM','LTIM','TITAN','ASIANPAINT','ULTRACEMCO','TATASTEEL','JSWSTEEL','HINDALCO','COALINDIA','ONGC','NTPC','POWERGRID','ADANIENT','ADANIPORTS','GRASIM','NESTLEIND','BRITANNIA','EICHERMOT','HEROMOTOCO'
];
const SCAN_BATCH_SIZE = 6;
const AUTO_FNO_CONFIRMATIONS = 3;
const FINAL_STRENGTH_MIN = 65;

type ScannerMode = 'find' | 'single';
type CandidateGroup = 'Tradable Setup' | 'Watchlist' | 'No Trade';
type ConfirmedMap = Record<string, FnoScanResponse>;

export function TradeScanner({ onNavigate }: { onNavigate: (p: PageKey) => void }) {
  const { scannerFilters, setScannerFilters } = useStore();
  const [mode, setMode] = useState<ScannerMode>('find');
  const [symbol, setSymbol] = useState(DEFAULT_SYMBOL);
  const [result, setResult] = useState<FnoScanResponse | null>(null);
  const [ranked, setRanked] = useState<MtfScanItem[]>([]);
  const [confirmed, setConfirmed] = useState<ConfirmedMap>({});
  const [scanning, setScanning] = useState(false);
  const [confirming, setConfirming] = useState<string | null>(null);
  const [autoConfirming, setAutoConfirming] = useState(false);
  const [progress, setProgress] = useState('');
  const [error, setError] = useState<string | null>(null);

  const displayRanked = useMemo(() => [...ranked].sort((a,b)=>compareCandidatesWithFno(a,b,confirmed)), [ranked,confirmed]);
  const grouped = useMemo(()=>{const g:Record<CandidateGroup,MtfScanItem[]>={'Tradable Setup':[],Watchlist:[],'No Trade':[]};displayRanked.forEach(i=>g[candidateGroup(i)].push(i));return g;},[displayRanked]);
  const bestTrade = useMemo(()=>displayRanked.map(item=>({item,confirmation:confirmed[item.symbol]})).filter(x=>isExecutionQualified(x.item,x.confirmation,scannerFilters.minRiskReward)).sort((a,b)=>executionStrength(b.item,b.confirmation)-executionStrength(a.item,a.confirmation))[0]??null,[displayRanked,confirmed,scannerFilters.minRiskReward]);

  const handleSingleScan=async(requestedSymbol?:string)=>{const s=(requestedSymbol??symbol).trim().toUpperCase();if(!s)return;setScanning(!requestedSymbol);setConfirming(requestedSymbol?s:null);setError(null);try{const r=await scanFno(s,scannerFilters.minRiskReward,LIVE_TIMEFRAMES);setSymbol(s);setResult(r);setConfirmed(p=>({...p,[s]:r}));}catch(e){setResult(null);setError(e instanceof Error?e.message:'Unable to reach the AlphaPilot API.');}finally{setScanning(false);setConfirming(null);}};
  const autoConfirmShortlist=async(items:MtfScanItem[])=>{const setups=items.filter(i=>candidateGroup(i)==='Tradable Setup').sort(compareCandidates);const shortlist=setups.length?setups:items.filter(i=>candidateGroup(i)==='Watchlist').sort(compareCandidates).slice(0,AUTO_FNO_CONFIRMATIONS);if(!shortlist.length)return;setAutoConfirming(true);const u:ConfirmedMap={};for(let i=0;i<shortlist.length;i++){const item=shortlist[i];setProgress(`F&O confirming ${i+1}/${shortlist.length}: ${item.symbol}`);try{u[item.symbol]=await scanFno(item.symbol,scannerFilters.minRiskReward,LIVE_TIMEFRAMES);}catch{}}if(Object.keys(u).length)setConfirmed(p=>({...p,...u}));setAutoConfirming(false);setProgress('');};
  const handleFindTrade=async()=>{setScanning(true);setError(null);setResult(null);setConfirmed({});setRanked([]);const all:MtfScanItem[]=[];try{for(let i=0;i<FIND_TRADE_SYMBOLS.length;i+=SCAN_BATCH_SIZE){const batch=FIND_TRADE_SYMBOLS.slice(i,i+SCAN_BATCH_SIZE);setProgress(`Scanning ${Math.min(i+batch.length,FIND_TRADE_SYMBOLS.length)}/${FIND_TRADE_SYMBOLS.length} NSE F&O stocks...`);const r=await scanMtf(batch,scannerFilters.minRiskReward,LIVE_TIMEFRAMES);all.push(...(r.setups??[]),...(r.others??[]));setRanked([...all].filter(x=>x.status!=='ERROR').sort(compareCandidates));}const valid=all.filter(x=>x.status!=='ERROR').sort(compareCandidates);setRanked(valid);setScanning(false);setProgress('');await autoConfirmShortlist(valid);}catch(e){setError(e instanceof Error?e.message:'Unable to run the market scan.');setScanning(false);setProgress('');}};

  return <div className="space-y-5"><div className="flex items-center justify-between flex-wrap gap-3"><div><h1 className="text-xl font-bold text-slate-900 dark:text-white">Find Trade</h1><p className="text-sm text-slate-500">Broad NSE F&amp;O scan → shortlist → F&amp;O confirm → execution gate.</p></div><div className="flex gap-2"><Button variant={mode==='find'?'primary':'ghost'} onClick={()=>setMode('find')}>Find Trade</Button><Button variant={mode==='single'?'primary':'ghost'} onClick={()=>setMode('single')}>Single Symbol</Button></div></div>
  <Card><CardHeader title={mode==='find'?'NSE F&O Market Scanner':'Live Scanner'} subtitle="5m + 15m + 1h · batched to protect the Groww/Render API"/><CardBody><div className="grid grid-cols-1 md:grid-cols-3 gap-3 items-end">{mode==='single'?<Input label="Symbol" value={symbol} onChange={v=>setSymbol(v.toUpperCase())}/>:<div className="rounded-lg border border-slate-200 dark:border-slate-800 px-3 py-2"><p className="text-xs text-slate-500">Universe</p><p className="font-medium text-sm">{FIND_TRADE_SYMBOLS.length} liquid NSE F&amp;O stocks · batches of {SCAN_BATCH_SIZE}</p></div>}<Input label="Min Risk/Reward" type="number" value={String(scannerFilters.minRiskReward)} onChange={v=>setScannerFilters({minRiskReward:parseFloat(v)||0})}/><Button variant="primary" onClick={mode==='find'?handleFindTrade:()=>handleSingleScan()} disabled={scanning||autoConfirming||!!confirming}><ScanLine size={16} className="inline mr-1.5"/>{scanning?'Scanning...':autoConfirming?'Confirming F&O...':mode==='find'?'Scan F&O Universe':'Run Live Scan'}</Button></div></CardBody></Card>
  {error&&<Card><CardBody><div className="flex gap-3"><AlertCircle className="text-red-500"/><p className="text-sm text-red-600">{error}</p></div></CardBody></Card>}{(scanning||autoConfirming)&&<Card><CardBody className="text-center py-8"><ScanLine size={36} className="mx-auto text-blue-500 mb-2 animate-pulse"/><p className="text-sm font-medium">{progress||'Working...'}</p><p className="text-xs text-slate-500 mt-1">Every technical SETUP is F&amp;O-confirmed before the final trade is selected.</p></CardBody></Card>}
  {mode==='find'&&displayRanked.length>0&&!scanning&&!autoConfirming&&<><MarketSessionBanner confirmed={confirmed}/><ExecutionVerdict bestTrade={bestTrade} minRR={scannerFilters.minRiskReward} confirmed={confirmed} onView={()=>bestTrade&&handleSingleScan(bestTrade.item.symbol)}/><div className="grid grid-cols-1 md:grid-cols-3 gap-3"><SummaryCell label="Tradable Setup" value={grouped['Tradable Setup'].length} variant="green"/><SummaryCell label="Watchlist" value={grouped.Watchlist.length} variant="blue"/><SummaryCell label="No Trade" value={grouped['No Trade'].length} variant="slate"/></div>{(['Tradable Setup','Watchlist','No Trade'] as CandidateGroup[]).map(group=>grouped[group].length>0&&<Card key={group}><CardHeader title={group} subtitle={group==='Tradable Setup'?'Every technical setup is automatically F&O-confirmed before final ranking.':group==='Watchlist'?'Directional bias only; used as fallback only when there are no technical setups.':'Rejected by technical gate; F&O calls skipped.'}/><CardBody className="space-y-3">{grouped[group].map(item=><RankedCandidate key={item.symbol} item={item} rank={displayRanked.findIndex(x=>x.symbol===item.symbol)+1} confirmation={confirmed[item.symbol]} confirming={confirming===item.symbol} allowConfirm={candidateGroup(item)!=='No Trade'} onConfirm={()=>handleSingleScan(item.symbol)}/>)}</CardBody></Card>)}</>}
  {mode==='find'&&!scanning&&!autoConfirming&&!displayRanked.length&&!error&&<Card><CardBody className="text-center py-10"><p className="text-sm text-slate-500">Click “Scan F&amp;O Universe” to search {FIND_TRADE_SYMBOLS.length} stocks.</p></CardBody></Card>}{result&&!scanning&&<><MarketSessionBanner confirmed={{[result.symbol]:result}}/><LiveResultCard result={result} onNavigate={onNavigate}/></>}<p className="text-xs text-slate-400 text-center pb-4">BEST TRADE uses directional strength: LONG requires Final Alpha ≥ {FINAL_STRENGTH_MIN}; SHORT requires Final Alpha ≤ {100-FINAL_STRENGTH_MIN}. R:R must also be ≥ {scannerFilters.minRiskReward.toFixed(1)}, and the live execution gate must be ready.</p></div>;
}

function MarketSessionBanner({confirmed}:{confirmed:ConfirmedMap}){const values=Object.values(confirmed).filter(Boolean);const withSession=values.find(v=>v.market_session);if(!withSession)return null;const session=withSession.market_session??{};const isOpen=session.is_open===true;const blockers=Array.from(new Set(values.flatMap(v=>Array.isArray(v.execution_blockers)?v.execution_blockers:[])));return <Card><CardBody className="py-4"><div className="flex flex-col md:flex-row md:items-start md:justify-between gap-3"><div><div className="flex items-center gap-2"><Badge variant={isOpen?'green':'red'}>{isOpen?'MARKET OPEN':'MARKET CLOSED'}</Badge><span className="text-xs text-slate-500">{session.regular_hours??'09:15-15:30 IST, Monday-Friday'}</span></div><p className="text-sm text-slate-600 dark:text-slate-400 mt-2">Execution status is based on the backend market-session and option-contract checks.</p></div>{session.checked_at&&<p className="text-xs text-slate-500">Checked {formatSessionTime(session.checked_at)}</p>}</div>{blockers.length>0&&<div className="mt-3 rounded-lg border border-amber-200 dark:border-amber-900/60 bg-amber-50/60 dark:bg-amber-950/20 p-3"><p className="text-xs font-semibold text-amber-700 dark:text-amber-400">Execution blocker{blockers.length>1?'s':''}</p>{blockers.map((b,i)=><p key={i} className="text-xs text-slate-600 dark:text-slate-400 mt-1">• {b}</p>)}</div>}</CardBody></Card>}
function ExecutionVerdict({bestTrade,minRR,confirmed,onView}:{bestTrade:{item:MtfScanItem;confirmation:FnoScanResponse}|null;minRR:number;confirmed:ConfirmedMap;onView:()=>void}){if(!bestTrade){const blockers=Array.from(new Set(Object.values(confirmed).flatMap(v=>Array.isArray(v.execution_blockers)?v.execution_blockers:[])));return <Card><CardBody className="py-6"><div className="flex gap-3"><ShieldCheck className="text-amber-500" size={26}/><div><p className="text-lg font-bold">NO TRADE RIGHT NOW</p><p className="text-sm text-slate-500 mt-1">No candidate passed the complete technical + F&amp;O + market-context + live execution gate.</p>{blockers.length>0&&<p className="text-xs text-amber-700 dark:text-amber-400 mt-2">Primary blocker: {blockers[0]}</p>}</div></div></CardBody></Card>}const{item,confirmation}=bestTrade;const t=confirmation.technical??{},f=confirmation.fno??{},o=confirmation.recommended_option??{};const strength=executionStrength(item,confirmation);return <Card><CardHeader title={`BEST TRADE — ${item.symbol} ${confirmation.signal}`} action={<Badge variant="green">STRENGTH {formatScore(strength)}</Badge>}/><CardBody className="space-y-4">{o.contract_label&&<div className="rounded-lg border border-emerald-200 dark:border-emerald-900 bg-emerald-50/60 dark:bg-emerald-950/20 p-4"><p className="text-xs text-slate-500">Recommended option</p><p className="text-lg font-bold mt-1">{o.contract_label}</p><div className="grid grid-cols-2 md:grid-cols-5 gap-3 mt-3"><MetricCell label="Premium" value={formatPrice(o.premium)}/><MetricCell label="IV" value={o.iv==null?'—':`${formatNumber(o.iv)}%`}/><MetricCell label="OI" value={formatInteger(o.open_interest)}/><MetricCell label="Volume" value={formatInteger(o.volume)}/><MetricCell label="Expiry" value={String(o.expiry??'—')}/></div></div>}<div className="grid grid-cols-2 md:grid-cols-6 gap-3"><MetricCell label="Entry" value={formatPrice(t.entry??item.entry)}/><MetricCell label="Stop Loss" value={formatPrice(t.stop_loss??item.stop_loss)}/><MetricCell label="Target 1" value={formatPrice(t.target1??item.target1)}/><MetricCell label="R:R" value={`${formatNumber(t.risk_reward??item.risk_reward)} : 1`}/><MetricCell label="Final Alpha" value={formatScore(confirmation.overall_alpha_score)}/><MetricCell label="PCR" value={formatNumber(f.pcr_oi,3)}/></div><div className="flex justify-end"><Button size="sm" variant="primary" onClick={onView}>View Full F&amp;O</Button></div><p className="text-xs text-slate-500">Direction-aware execution gate: LONG ≥ {FINAL_STRENGTH_MIN}; SHORT ≤ {100-FINAL_STRENGTH_MIN}; R:R ≥ {minRR.toFixed(1)}; backend execution_ready must be true.</p></CardBody></Card>}
function RankedCandidate({item,rank,confirmation,confirming,allowConfirm,onConfirm}:{item:MtfScanItem;rank:number;confirmation?:FnoScanResponse;confirming:boolean;allowConfirm:boolean;onConfirm:()=>void}){const signal=confirmation?.signal??item.signal??'NO_TRADE',tf=item.timeframes?.['15m']??{},f=confirmation?.fno??{},m=confirmation?.market_context??{},blocked=confirmation?.execution_ready===false,blockers=Array.isArray(confirmation?.execution_blockers)?confirmation.execution_blockers:[];return <div className="rounded-lg border border-slate-200 dark:border-slate-800 p-4 space-y-3"><div className="flex flex-col lg:flex-row lg:items-center justify-between gap-4"><div className="flex gap-3"><div className="w-8 h-8 rounded-full bg-slate-100 dark:bg-slate-800 flex items-center justify-center font-bold text-sm">{rank}</div><div><div className="flex gap-2 flex-wrap"><b>{item.symbol}</b><Badge variant={item.status==='SETUP'?'green':'blue'}>{signal}</Badge>{confirmation&&<Badge variant="blue">F&amp;O CONFIRMED</Badge>}{blocked&&<Badge variant="red">EXECUTION BLOCKED</Badge>}</div><p className="text-xs text-slate-500 mt-1">15m: {tf.market_structure??'—'} · RSI {formatNumber(tf.rsi14)} · {item.reason??'Technical threshold met'}</p></div></div><div className="flex items-center gap-4"><div className="text-right"><p className="text-xs text-slate-500">MTF Alpha</p><b>{formatScore(item.multi_timeframe_score)}</b></div><div className="text-right"><p className="text-xs text-slate-500">Final Alpha</p><b>{confirmation?formatScore(confirmation.overall_alpha_score):allowConfirm?'Pending':'Not required'}</b></div>{confirmation&&<div className="text-right"><p className="text-xs text-slate-500">Strength</p><b>{formatScore(executionStrength(item,confirmation))}</b></div>}{allowConfirm&&<Button size="sm" variant="ghost" onClick={onConfirm} disabled={confirming}>{confirming?'Confirming...':confirmation?'View Full F&O':'Confirm F&O'}</Button>}</div></div>{confirmation&&<div className="grid grid-cols-2 md:grid-cols-4 gap-3 rounded-lg bg-slate-50 dark:bg-slate-900/60 p-3"><MetricCell label="PCR" value={formatNumber(f.pcr_oi,3)}/><MetricCell label="ATM IV" value={f.atm_iv==null?'—':`${formatNumber(f.atm_iv)}%`}/><MetricCell label="Call / Put Wall" value={`${formatPlain(f.call_resistance_strike)} / ${formatPlain(f.put_support_strike)}`}/><MetricCell label="NIFTY" value={`${m.bias??'—'} · ${formatScore(confirmation.market_score??m.market_score)}`}/></div>}{blockers.length>0&&<div className="rounded-lg border border-amber-200 dark:border-amber-900/60 bg-amber-50/60 dark:bg-amber-950/20 p-3">{blockers.map((b,i)=><p key={i} className="text-xs text-slate-600 dark:text-slate-400">• {b}</p>)}</div>}</div>}
function LiveResultCard({result,onNavigate}:{result:FnoScanResponse;onNavigate:(p:PageKey)=>void}){const t=result.technical??{},f=result.fno??{},m=result.market_context??{},tf=t.timeframes??{},o=result.recommended_option??{},blockers=Array.isArray(result.execution_blockers)?result.execution_blockers:[];return <Card><CardHeader title={`${result.symbol} — ${result.status}`} action={<div className="flex gap-2"><Badge variant={result.status==='SETUP'?'green':'blue'}>{result.signal}</Badge>{result.execution_ready===false&&<Badge variant="red">EXECUTION BLOCKED</Badge>}</div>}/><CardBody className="space-y-4">{o.contract_label&&<div className="rounded-lg border border-slate-200 dark:border-slate-800 p-3"><p className="text-xs text-slate-500">Recommended option</p><p className="font-bold mt-1">{o.contract_label}</p><p className="text-xs text-slate-500 mt-1">Premium {formatPrice(o.premium)} · IV {o.iv==null?'—':`${formatNumber(o.iv)}%`}</p></div>}<div className="grid grid-cols-2 lg:grid-cols-4 gap-3"><ScoreCell label="Overall Alpha" value={formatScore(result.overall_alpha_score)}/><ScoreCell label="Technical MTF" value={formatScore(result.technical_score)}/><ScoreCell label="F&O Context" value={formatScore(result.fno_score)}/><ScoreCell label="NIFTY Context" value={formatScore(result.market_score??m.market_score)}/></div><div className="grid grid-cols-1 md:grid-cols-3 gap-3">{LIVE_TIMEFRAMES.map(x=>{const d=tf[x]??{};return <div key={x} className="rounded-lg border p-3"><div className="flex justify-between"><b>{x}</b><Badge variant="blue">{d.signal??d.status??'—'}</Badge></div><p className="font-bold mt-2">{formatScore(d.alpha_score)}</p><p className="text-xs text-slate-500">{d.market_structure??'—'} · RSI {formatNumber(d.rsi14)}</p></div>})}</div><div className="grid grid-cols-2 lg:grid-cols-4 gap-3"><MetricCell label="PCR" value={formatNumber(f.pcr_oi,3)}/><MetricCell label="Call Resistance" value={formatPrice(f.call_resistance_strike)}/><MetricCell label="Put Support" value={formatPrice(f.put_support_strike)}/><MetricCell label="ATM IV" value={f.atm_iv==null?'—':`${formatNumber(f.atm_iv)}%`}/></div>{blockers.length>0&&<div className="rounded-lg border border-amber-200 dark:border-amber-900/60 bg-amber-50/60 dark:bg-amber-950/20 p-3"><p className="text-xs font-semibold text-amber-700 dark:text-amber-400">Execution blockers</p>{blockers.map((b,i)=><p key={i} className="text-xs text-slate-600 dark:text-slate-400 mt-1">• {b}</p>)}</div>}<div className="flex justify-end"><Button size="sm" variant="ghost" onClick={()=>onNavigate('position-sizing')}>Open Risk Calculator</Button></div></CardBody></Card>}
function executionStrength(i:MtfScanItem,c?:FnoScanResponse){const score=c?.overall_alpha_score;if(typeof score!=='number')return 0;const direction=c?.technical?.direction??i.direction??(c?.signal?.includes('SHORT')?'SHORT':'LONG');return direction==='SHORT'?100-score:score}
function isExecutionQualified(i:MtfScanItem,c?:FnoScanResponse,minRR=1.5){if(!c)return false;const rr=c.technical?.risk_reward??i.risk_reward;return i.status==='SETUP'&&c.status==='SETUP'&&c.execution_ready===true&&executionStrength(i,c)>=FINAL_STRENGTH_MIN&&typeof rr==='number'&&rr>=minRR}
function candidateGroup(i:MtfScanItem):CandidateGroup{if(i.status==='SETUP')return'Tradable Setup';if((i.signal??'').startsWith('WATCH_'))return'Watchlist';return'No Trade'}
function compareCandidates(a:MtfScanItem,b:MtfScanItem){const o:Record<CandidateGroup,number>={'Tradable Setup':0,Watchlist:1,'No Trade':2};return o[candidateGroup(a)]-o[candidateGroup(b)]||((b.multi_timeframe_score??0)-(a.multi_timeframe_score??0))}
function compareCandidatesWithFno(a:MtfScanItem,b:MtfScanItem,c:ConfirmedMap){const o:Record<CandidateGroup,number>={'Tradable Setup':0,Watchlist:1,'No Trade':2},d=o[candidateGroup(a)]-o[candidateGroup(b)];if(d)return d;const as=c[a.symbol],bs=c[b.symbol];if(as&&bs)return executionStrength(b,bs)-executionStrength(a,as);return(c[b.symbol]?.overall_alpha_score??b.multi_timeframe_score??0)-(c[a.symbol]?.overall_alpha_score??a.multi_timeframe_score??0)}
function SummaryCell({label,value,variant}:{label:string;value:number;variant:'green'|'blue'|'slate'}){const cls=variant==='green'?'text-emerald-600':variant==='blue'?'text-blue-600':'text-slate-600';return <Card><CardBody className="py-4"><p className="text-xs text-slate-500">{label}</p><p className={`text-2xl font-bold ${cls}`}>{value}</p></CardBody></Card>}
function ScoreCell({label,value}:{label:string;value:string}){return <div className="rounded-lg border border-slate-200 dark:border-slate-800 p-3"><span className="text-xs text-slate-500">{label}</span><p className="font-semibold mt-1">{value}</p></div>}
function MetricCell({label,value}:{label:string;value:string}){return <div><span className="text-xs text-slate-500">{label}</span><p className="font-medium">{value}</p></div>}
function formatScore(v:unknown){return typeof v==='number'&&Number.isFinite(v)?`${v.toFixed(1)}/100`:'—'}
function formatNumber(v:unknown,d=2){return typeof v==='number'&&Number.isFinite(v)?v.toFixed(d):'—'}
function formatInteger(v:unknown){return typeof v==='number'&&Number.isFinite(v)?Math.round(v).toLocaleString('en-IN'):'—'}
function formatPrice(v:unknown){return typeof v==='number'&&Number.isFinite(v)?`₹${v.toFixed(2)}`:'—'}
function formatPlain(v:unknown){return typeof v==='number'&&Number.isFinite(v)?v.toFixed(0):'—'}
function formatSessionTime(v:unknown){if(typeof v!=='string')return '—';const d=new Date(v);return Number.isNaN(d.getTime())?v:d.toLocaleString('en-IN',{timeZone:'Asia/Kolkata',hour12:true})}
