import { useMemo,useState } from 'react';
import { CandlestickChart,Play } from 'lucide-react';
import { Badge,Button,Card,CardBody,CardHeader } from '@/components/ui';
import { ALPHAPILOT_API_BASE } from '@/lib/alphaPilotApi';

type Row={pattern_type:string;direction:'LONG'|'SHORT';trades:number;wins:number;losses:number;win_rate:number;average_r:number;total_r:number;profit_factor:number;ambiguous:number;state:'PROMISING'|'WEAK'|'LOW_SAMPLE'};
type Result={start_date:string;end_date:string;observations:number;rows:Row[];errors:any[];fixed_gates?:Record<string,number>;definitions?:Record<string,string>};
type Block={id:string;start:string;end:string};
const BLOCKS:Block[]=[
 {id:'N-0A',start:'2026-05-25',end:'2026-06-05'},
 {id:'N-0B',start:'2026-06-08',end:'2026-06-19'},
 {id:'N-0C',start:'2026-06-22',end:'2026-07-03'},
 {id:'N-1',start:'2026-07-06',end:'2026-07-17'},
 {id:'N-2',start:'2026-07-20',end:'2026-07-31'},
 {id:'N-3',start:'2026-08-03',end:'2026-08-10'},
];
const SYMBOLS=['RELIANCE','HDFCBANK','ICICIBANK','SBIN','TCS','INFY','TATASTEEL','MARUTI'];
const REQUIRED_BLOCKS=3;
function fmtR(v:number){return `${v>=0?'+':''}${Number(v||0).toFixed(3)}R`}
async function runBlock(b:Block):Promise<Result>{const r=await fetch(`${ALPHAPILOT_API_BASE}/v1/research/candlestick-discovery-v1`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({symbols:SYMBOLS,start_date:b.start,end_date:b.end})});if(!r.ok){let d='';try{const x=await r.json();d=x?.detail?`: ${x.detail}`:''}catch{}throw new Error(`${b.id} API ${r.status}${d}`)}return r.json()}
export function CandlestickDiscoveryV1(){const[running,setRunning]=useState(false),[progress,setProgress]=useState(''),[results,setResults]=useState<Record<string,Result>>({}),[error,setError]=useState<string|null>(null);
 const replicated=useMemo(()=>{const map=new Map<string,{pattern:string;direction:string;blocks:string[];trades:number;weighted:number}>();for(const b of BLOCKS){const r=results[b.id];if(!r)continue;for(const row of r.rows){if(row.state!=='PROMISING')continue;const key=`${row.pattern_type}|${row.direction}`;const cur=map.get(key)||{pattern:row.pattern_type,direction:row.direction,blocks:[],trades:0,weighted:0};cur.blocks.push(b.id);cur.trades+=row.trades;cur.weighted+=row.average_r*row.trades;map.set(key,cur)}}return[...map.values()].filter(x=>x.blocks.length>=REQUIRED_BLOCKS).map(x=>({...x,avgR:x.trades?x.weighted/x.trades:0})).sort((a,b)=>b.blocks.length-a.blocks.length||b.trades-a.trades)},[results]);
 async function run(){setRunning(true);setError(null);setResults({});try{for(const b of BLOCKS){setProgress(`Running ${b.id} · ${b.start} → ${b.end}`);const r=await runBlock(b);setResults(x=>({...x,[b.id]:r}));await new Promise(res=>setTimeout(res,700))}}catch(e){setError(e instanceof Error?e.message:'Candlestick Discovery v1 failed.')}finally{setProgress('');setRunning(false)}}
 const completed=Object.keys(results).length,totalObs=Object.values(results).reduce((a,r)=>a+r.observations,0),promising=Object.values(results).reduce((a,r)=>a+r.rows.filter(x=>x.state==='PROMISING').length,0);
 return <Card><CardHeader title="Candlestick Discovery v1 — Nison Pattern Replication" subtitle="Fresh candlestick hypothesis family. Frozen definitions, fixed blocks and no production changes." action={<CandlestickChart size={18} className="text-violet-500"/>}/><CardBody className="space-y-4">
  <div className="flex gap-2 flex-wrap"><Badge variant="blue">CANDLESTICK DISCOVERY v1</Badge><Badge variant="default">6 FIXED BLOCKS</Badge><Badge variant="default">4 FROZEN PATTERNS</Badge><Badge variant="default">NEXT 5m OPEN</Badge><Badge variant="default">FIXED 1R</Badge><Badge variant="default">3-BLOCK REPLICATION</Badge><Badge variant="default">RESEARCH ONLY</Badge><Badge variant="default">PRODUCTION UNCHANGED</Badge></div>
  <div className="flex items-center justify-between gap-4"><p className="text-xs text-slate-500">Frozen hypotheses: Bullish Engulfing LONG, Bearish Engulfing SHORT, Hammer LONG and Shooting Star SHORT. Pattern geometry plus prior-trend/location and confirmation are evaluated mechanically. No Market Brain, RSI, option chain, news or discretionary filters. A block is PROMISING only with ≥12 resolved trades, Avg R ≥ +0.10R, win rate ≥55% and PF ≥1.20. Exact pattern + direction must pass in ≥3 independent blocks.</p><Button variant="primary" onClick={run} disabled={running}><Play size={14} className="inline mr-1"/>{running?'Running Candlestick Discovery v1…':'Run Candlestick Discovery v1'}</Button></div>
  {progress&&<div className="rounded-lg border p-3 text-xs">{progress}</div>}{error&&<div className="rounded-lg border border-red-200 p-3 text-sm text-red-600">{error}</div>}
  <div className="overflow-x-auto rounded-lg border"><table className="w-full text-xs"><thead className="bg-slate-50 dark:bg-slate-900"><tr><th className="p-2 text-left">Block</th><th>Dates</th><th>Observations</th><th>Promising</th><th>Errors</th><th>Status</th></tr></thead><tbody>{BLOCKS.map(b=>{const r=results[b.id];return <tr className="border-t" key={b.id}><td className="p-2 font-semibold">{b.id}</td><td className="text-center">{b.start} → {b.end}</td><td className="text-center">{r?.observations??'—'}</td><td className="text-center">{r?r.rows.filter(x=>x.state==='PROMISING').length:'—'}</td><td className="text-center">{r?.errors.length??'—'}</td><td className="text-center"><Badge variant={r?'green':'default'}>{r?'COMPLETE':'PENDING'}</Badge></td></tr>})}</tbody></table></div>
  {completed>0&&<div className="grid grid-cols-2 md:grid-cols-5 gap-3"><Stat label="Completed blocks" value={`${completed}/${BLOCKS.length}`}/><Stat label="Resolved observations" value={String(totalObs)}/><Stat label="Promising block rows" value={String(promising)}/><Stat label="Replicated patterns" value={String(replicated.length)}/><div className="rounded-lg border p-3"><p className="text-xs text-slate-500">Decision</p><Badge variant={replicated.length?'blue':'default'}>{completed<BLOCKS.length?'INCOMPLETE':replicated.length?'REPLICATED_CANDLE_CANDIDATE':'NO_REPLICATED_CANDLE_EDGE'}</Badge></div></div>}
  {replicated.length>0&&<div><p className="text-sm font-semibold mb-2">Replicated candlestick candidates</p><div className="overflow-x-auto rounded-lg border"><table className="w-full text-xs"><thead><tr><th className="p-2 text-left">Pattern</th><th>Direction</th><th>Blocks</th><th>Trades</th><th>Weighted Avg R</th></tr></thead><tbody>{replicated.map((x,i)=><tr key={i} className="border-t"><td className="p-2 font-medium">{x.pattern}</td><td className="text-center">{x.direction}</td><td className="text-center">{x.blocks.join(', ')}</td><td className="text-center">{x.trades}</td><td className="text-center font-semibold">{fmtR(x.avgR)}</td></tr>)}</tbody></table></div></div>}
  {completed>0&&<div className="space-y-3"><p className="text-sm font-semibold">Block results</p>{BLOCKS.map(b=>{const r=results[b.id];if(!r)return null;return <div key={b.id}><p className="text-xs font-semibold mb-1">{b.id}</p><div className="overflow-x-auto rounded-lg border"><table className="w-full text-xs"><thead><tr><th className="p-2 text-left">Pattern</th><th>Dir</th><th>Trades</th><th>Win</th><th>Avg R</th><th>Total R</th><th>PF</th><th>State</th></tr></thead><tbody>{r.rows.map((x,i)=><tr key={i} className="border-t"><td className="p-2 font-medium">{x.pattern_type}</td><td className="text-center">{x.direction}</td><td className="text-center">{x.trades}</td><td className="text-center">{x.win_rate.toFixed(1)}%</td><td className="text-center">{fmtR(x.average_r)}</td><td className="text-center">{fmtR(x.total_r)}</td><td className="text-center">{x.profit_factor.toFixed(2)}</td><td className="text-center"><Badge variant={x.state==='PROMISING'?'green':x.state==='WEAK'?'red':'default'}>{x.state}</Badge></td></tr>)}</tbody></table></div></div>})}</div>}
  <p className="text-[11px] text-slate-500">Underlying-price discovery only. This panel deliberately keeps the first candlestick test narrow. A replicated result is not deployed: it must be frozen and pass untouched OOS before any option-premium validation or production consideration.</p>
 </CardBody></Card>}
function Stat({label,value}:{label:string;value:string}){return <div className="rounded-lg border p-3"><p className="text-xs text-slate-500">{label}</p><p className="text-lg font-bold">{value}</p></div>}
