import { useMemo,useState } from 'react';
import { LockKeyhole,Play } from 'lucide-react';
import { Badge,Button,Card,CardBody,CardHeader } from '@/components/ui';
import { ALPHAPILOT_API_BASE } from '@/lib/alphaPilotApi';

type Trade={symbol:string;fill_at:string;option_entry_at?:string|null;expiry?:string;strike?:number;net_r?:number|null;replay_status?:string;gross_1r_outcome?:string};
type Result={start_date:string;end_date:string;candidate_fills_selected:number;summary:{option_replays:number;resolved:number;coverage_pct:number;wins:number;losses:number;win_rate:number;average_r:number;total_r:number;profit_factor:number;decision:string};trades:Trade[];errors:any[]};
type Block={id:string;purpose:string;symbols:string[]};
const START='2026-08-11',END='2026-08-24';
const BLOCKS:Block[]=[
 {id:'H-OPT-1',purpose:'Forward option OOS · development-symbol group',symbols:['RELIANCE','HDFCBANK','ICICIBANK','SBIN','TCS','INFY','TATASTEEL','MARUTI']},
 {id:'H-OPT-2',purpose:'Forward option OOS · new-symbol group A',symbols:['AXISBANK','KOTAKBANK','LT','HINDALCO','ONGC','HCLTECH','JSWSTEEL','M&M']},
 {id:'H-OPT-3',purpose:'Forward option OOS · new-symbol group B',symbols:['SUNPHARMA','DRREDDY','CIPLA','ITC','TITAN','ADANIPORTS','BAJFINANCE','BHARTIARTL']},
];
const MIN_RESOLVED=30,MIN_COVERAGE=50,MIN_WIN=55,MIN_AVG=.10,MIN_PF=1.20;
function fmtR(v:number){return `${v>=0?'+':''}${Number(v||0).toFixed(3)}R`}
async function runBlock(b:Block):Promise<Result>{const r=await fetch(`${ALPHAPILOT_API_BASE}/v1/research/candidate-h-option-oos`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({symbols:b.symbols,start_date:START,end_date:END,max_signals:80})});if(!r.ok){let d='';try{const x=await r.json();d=x?.detail?`: ${x.detail}`:''}catch{}throw new Error(`${b.id} API ${r.status}${d}`)}return r.json()}
function pf(rs:number[]){const w=rs.filter(x=>x>0).reduce((a,b)=>a+b,0),l=Math.abs(rs.filter(x=>x<0).reduce((a,b)=>a+b,0));return l>0?w/l:(w>0?99:0)}
export function CandidateHOptionValidator(){const[running,setRunning]=useState(false),[progress,setProgress]=useState(''),[results,setResults]=useState<Record<string,Result>>({}),[error,setError]=useState<string|null>(null);
 const rows=useMemo(()=>BLOCKS.map(b=>({...b,result:results[b.id]})),[results]);
 const combined=useMemo(()=>{const all=rows.flatMap(x=>x.result?.trades??[]),rs=all.map(x=>x.net_r).filter((x):x is number=>typeof x==='number'&&Number.isFinite(x));const fills=rows.reduce((s,x)=>s+(x.result?.candidate_fills_selected??0),0),resolved=rs.length,total=rs.reduce((a,b)=>a+b,0),wins=rs.filter(x=>x>0).length,coverage=fills?resolved/fills*100:0,win=resolved?wins/resolved*100:0,avg=resolved?total/resolved:0,profit=pf(rs),positiveBlocks=rows.filter(x=>(x.result?.summary.average_r??0)>0).length,complete=rows.every(x=>x.result),pass=complete&&resolved>=MIN_RESOLVED&&coverage>=MIN_COVERAGE&&win>=MIN_WIN&&avg>=MIN_AVG&&profit>=MIN_PF&&positiveBlocks>=2;return{fills,resolved,total,coverage,win,avg,profit,positiveBlocks,pass}},[rows]);
 async function run(){setRunning(true);setError(null);setResults({});try{for(const b of BLOCKS){setProgress(`Running ${b.id} · ${b.symbols.length} symbols · ${START} → ${END}`);const r=await runBlock(b);setResults(x=>({...x,[b.id]:r}));await new Promise(res=>setTimeout(res,1200))}}catch(e){setError(e instanceof Error?e.message:'Candidate H option OOS failed.')}finally{setProgress('');setRunning(false)}}
 const completed=rows.filter(x=>x.result).length;
 return <Card><CardHeader title="Candidate H — True Option-Premium OOS" subtitle="BUY CE validation at the frozen Candidate H pullback-fill timestamps. Production execution remains unchanged." action={<LockKeyhole size={18} className="text-violet-500"/>}/><CardBody className="space-y-4">
  <div className="flex gap-2 flex-wrap"><Badge variant="blue">CANDIDATE H FROZEN</Badge><Badge variant="default">FAILED BREAKOUT LONG</Badge><Badge variant="default">PULLBACK ENTRY</Badge><Badge variant="default">BUY CE</Badge><Badge variant="default">NEAREST EXPIRY</Badge><Badge variant="default">NEAREST STRIKE</Badge><Badge variant="default">FIXED PREMIUM 1R</Badge><Badge variant="default">10 BPS COST</Badge><Badge variant="default">RESEARCH ONLY</Badge><Badge variant="default">PRODUCTION UNCHANGED</Badge></div>
  <div className="flex items-center justify-between gap-4"><p className="text-xs text-slate-500">Frozen option specification: the underlying Candidate H rule is unchanged; after its 3-bar/0.25 ATR pullback fill, AlphaPilot buys the nearest-strike CE from the nearest listed expiry, entering at the next 5m option open after the fill bar. Premium risk uses the existing fixed schedule (30% below ₹10, 25% below ₹30, otherwise 20%), target is fixed 1R and 10 bps round-trip cost is deducted. PASS is pre-registered as ≥30 resolved option trades, ≥50% contract/candle coverage, win rate ≥55%, Avg R ≥+0.10R, PF ≥1.20 and positive Avg R in at least 2/3 symbol blocks.</p><Button variant="primary" onClick={run} disabled={running}><Play size={14} className="inline mr-1"/>{running?'Running Candidate H Option OOS…':'Run Candidate H Option OOS'}</Button></div>
  <div className="rounded-lg border p-3 text-[11px] text-slate-500">Date note: 11–24 Aug is forward to the Execution-Structure v1 discovery window, but these calendar dates were previously viewed in unrelated candidate research. Candidate H's option specification and gates were frozen before this option replay; this is Candidate-H OOS, not globally unseen-market OOS.</div>
  {progress&&<div className="rounded-lg border p-3 text-xs">{progress}</div>}{error&&<div className="rounded-lg border border-red-200 p-3 text-sm text-red-600">{error}</div>}
  <div className="overflow-x-auto rounded-lg border"><table className="w-full text-xs"><thead><tr><th className="p-2 text-left">Block</th><th>Purpose</th><th>Symbols</th><th>Candidate fills</th><th>Resolved</th><th>Coverage</th><th>Win</th><th>Avg R</th><th>PF</th></tr></thead><tbody>{rows.map(x=>{const s=x.result?.summary;return <tr className="border-t" key={x.id}><td className="p-2 font-semibold">{x.id}</td><td className="text-center">{x.purpose}</td><td className="text-center">{x.symbols.length}</td><td className="text-center">{x.result?.candidate_fills_selected??'—'}</td><td className="text-center">{s?.resolved??'—'}</td><td className="text-center">{s?`${s.coverage_pct.toFixed(1)}%`:'—'}</td><td className="text-center">{s?`${s.win_rate.toFixed(1)}%`:'—'}</td><td className="text-center">{s?fmtR(s.average_r):'—'}</td><td className="text-center">{s?s.profit_factor.toFixed(2):'—'}</td></tr>})}</tbody></table></div>
  {completed>0&&<div className="grid grid-cols-2 md:grid-cols-5 gap-3"><Stat label="Completed blocks" value={`${completed}/3`}/><Stat label="Candidate fills" value={String(combined.fills)}/><Stat label="Resolved option trades" value={String(combined.resolved)}/><Stat label="Coverage" value={`${combined.coverage.toFixed(1)}%`}/><Stat label="Win rate" value={`${combined.win.toFixed(1)}%`}/><Stat label="Avg R" value={fmtR(combined.avg)}/><Stat label="Total R" value={fmtR(combined.total)}/><Stat label="Profit Factor" value={combined.profit.toFixed(2)}/><Stat label="Positive blocks" value={`${combined.positiveBlocks}/3`}/><div className="rounded-lg border p-3"><p className="text-xs text-slate-500">Decision</p><Badge variant={completed<3?'default':combined.pass?'green':'red'}>{completed<3?'INCOMPLETE':combined.pass?'PASS — OPTION EDGE SURVIVES':'FAIL — OPTION EDGE NOT VALIDATED'}</Badge></div></div>}
  {completed>0&&<p className="text-[11px] text-slate-500">Missing/expired contracts or missing premium candles are reported as coverage loss and errors; they are never fabricated. Even a PASS cannot modify production. It would permit a final prospective/paper-trading validation stage only.</p>}
 </CardBody></Card>}
function Stat({label,value}:{label:string;value:string}){return <div className="rounded-lg border p-3"><p className="text-xs text-slate-500">{label}</p><p className="text-lg font-bold">{value}</p></div>}
