import { useMemo,useState } from 'react';
import { ShieldCheck,Play } from 'lucide-react';
import { Badge,Button,Card,CardBody,CardHeader,Input } from '@/components/ui';
import { runCandidateValidator,type CandidateValidatorResponse } from '@/lib/candidateValidatorApi';

const RECOMMENDED_SYMBOLS='MARUTI,EICHERMOT,INDUSINDBK,JSWSTEEL,TITAN,NESTLEIND,GRASIM,BRITANNIA,LT,DRREDDY,BAJFINANCE,M&M,SUNPHARMA,ADANIPORTS,KOTAKBANK';
const RECOMMENDED_START='2026-08-04';
const RECOMMENDED_END='2026-08-13';
function fmt(v:unknown,d=2){const n=Number(v);return Number.isFinite(n)?n.toFixed(d):'—'}
function StatusBadge({status}:{status:string}){return <Badge variant={status==='PASS'?'green':status==='WATCH'?'blue':status==='FAIL'?'red':'default'}>{status}</Badge>}
export function CandidateValidator(){
 const [symbolsText,setSymbolsText]=useState(RECOMMENDED_SYMBOLS);
 const [start,setStart]=useState(RECOMMENDED_START);const [end,setEnd]=useState(RECOMMENDED_END);const [cost,setCost]=useState('10');const [sampleBars,setSampleBars]=useState('3');const [maxTrades,setMaxTrades]=useState('250');
 const [running,setRunning]=useState(false);const [error,setError]=useState<string|null>(null);const [result,setResult]=useState<CandidateValidatorResponse|null>(null);
 const symbols=useMemo(()=>symbolsText.split(',').map(x=>x.trim().toUpperCase()).filter(Boolean).slice(0,20),[symbolsText]);
 async function run(){if(!symbols.length||!start||!end){setError('Enter symbols and dates.');return}if(end<start){setError('End date must be on or after start date.');return}setRunning(true);setError(null);setResult(null);try{setResult(await runCandidateValidator({symbols,start_date:start,end_date:end,round_trip_cost_bps:Math.max(0,Number(cost)||0),sample_every_bars:Math.max(1,Math.min(Number(sampleBars)||3,12)),max_trades:Math.max(10,Math.min(Number(maxTrades)||250,500))}))}catch(e){setError(e instanceof Error?e.message:'Candidate validation failed.')}finally{setRunning(false)}}
 const s=result?.summary,b=result?.baseline;
 return <Card><CardHeader title="Frozen Candidate Validator v1" subtitle="Out-of-sample test for Candidate A: BUY PE only when Market Brain=RANGE and premium ATR is HIGH (≥5%). No extra filters are allowed." action={<ShieldCheck size={18} className="text-emerald-500"/>}/><CardBody className="space-y-4">
 <div className="flex gap-2 flex-wrap"><Badge variant="green">CANDIDATE A FROZEN</Badge><Badge variant="default">PE × RANGE × HIGH ATR</Badge><Badge variant="default">RESEARCH ONLY</Badge><Badge variant="default">PRODUCTION UNCHANGED</Badge><Badge variant="blue">RECOMMENDED OOS PRESET LOADED</Badge></div>
 <div className="rounded-lg border border-blue-200 bg-blue-50/40 p-3 text-xs text-blue-700 dark:border-blue-900 dark:bg-blue-950/20 dark:text-blue-300">All validation inputs are prefilled with the frozen OOS preset. You can simply click <b>Run Candidate Validation</b> and share the result.</div>
 <div className="grid grid-cols-1 md:grid-cols-5 gap-2 items-end"><Input label="Untouched symbols" value={symbolsText} onChange={setSymbolsText}/><Input label="Start date" type="date" value={start} onChange={setStart}/><Input label="End date" type="date" value={end} onChange={setEnd}/><Input label="Cost (bps)" type="number" value={cost} onChange={setCost}/><Input label="Max trades" type="number" value={maxTrades} onChange={setMaxTrades}/></div>
 <div className="grid grid-cols-1 md:grid-cols-[220px_1fr] gap-3 items-end"><Input label="Sample every N bars" type="number" value={sampleBars} onChange={setSampleBars}/><div className="flex justify-end"><Button variant="primary" onClick={run} disabled={running}><Play size={14} className="inline mr-1"/>{running?'Validating frozen candidate…':'Run Candidate Validation'}</Button></div></div>
 <p className="text-[11px] text-slate-500">Preset: 15 untouched symbols · 04-Aug-2026 to 13-Aug-2026 · 10 bps cost · max 250 trades · sample every 3 bars. The validator uses next-5m-candle entry, a fixed 1R target, the same premium-risk stop as discovery, conservative same-candle ordering, trading costs and non-overlapping trades per symbol.</p>
 {error&&<div className="rounded-lg border border-red-200 p-3 text-sm text-red-600">{error}</div>}
 {result&&s&&b&&<><div className="flex items-center gap-3"><StatusBadge status={result.status}/><p className="text-xs text-slate-500">{result.validation_note}</p></div>
 <div className="grid grid-cols-2 md:grid-cols-6 gap-3"><div className="rounded-lg border p-3"><p className="text-xs text-slate-500">Trades</p><p className="text-lg font-bold">{s.trades}</p></div><div className="rounded-lg border p-3"><p className="text-xs text-slate-500">Win rate</p><p className="text-lg font-bold">{fmt(s.win_rate_pct,1)}%</p></div><div className="rounded-lg border p-3"><p className="text-xs text-slate-500">Avg R</p><p className="text-lg font-bold">{s.avg_r>0?'+':''}{fmt(s.avg_r,3)}R</p></div><div className="rounded-lg border p-3"><p className="text-xs text-slate-500">Total R</p><p className="text-lg font-bold">{s.total_r>0?'+':''}{fmt(s.total_r)}R</p></div><div className="rounded-lg border p-3"><p className="text-xs text-slate-500">Profit Factor</p><p className="text-lg font-bold">{fmt(s.profit_factor)}</p></div><div className="rounded-lg border p-3"><p className="text-xs text-slate-500">Max DD</p><p className="text-lg font-bold">{fmt(s.max_drawdown_r)}R</p></div></div>
 <div className="overflow-x-auto rounded-lg border border-slate-200 dark:border-slate-800"><table className="w-full text-xs"><thead className="bg-slate-50 dark:bg-slate-900"><tr><th className="p-2 text-left">Metric</th><th>Frozen Candidate</th><th>Unconditional PE Baseline</th></tr></thead><tbody>{[['Trades',s.trades,b.trades],['Win rate',`${fmt(s.win_rate_pct,1)}%`,`${fmt(b.win_rate_pct,1)}%`],['Avg R',`${fmt(s.avg_r,3)}R`,`${fmt(b.avg_r,3)}R`],['Total R',`${fmt(s.total_r)}R`,`${fmt(b.total_r)}R`],['Profit factor',fmt(s.profit_factor),fmt(b.profit_factor)],['Max drawdown',`${fmt(s.max_drawdown_r)}R`,`${fmt(b.max_drawdown_r)}R`],['Avg MFE',`${fmt(s.avg_mfe_r)}R`,`${fmt(b.avg_mfe_r)}R`],['Avg MAE',`${fmt(s.avg_mae_r)}R`,`${fmt(b.avg_mae_r)}R`],['Max losing streak',s.max_consecutive_losses,b.max_consecutive_losses]].map((r,i)=><tr key={i} className="border-t border-slate-200 dark:border-slate-800"><td className="p-2 font-medium">{r[0]}</td><td className="text-center">{r[1]}</td><td className="text-center">{r[2]}</td></tr>)}</tbody></table></div>
 {result.trades?.length>0&&<div><p className="text-sm font-semibold mb-2">Frozen Candidate Trades</p><div className="overflow-x-auto rounded-lg border border-slate-200 dark:border-slate-800"><table className="w-full text-xs"><thead className="bg-slate-50 dark:bg-slate-900"><tr><th className="p-2 text-left">Symbol</th><th>Signal</th><th>Contract</th><th>ATR</th><th>Entry</th><th>SL</th><th>Target</th><th>Outcome</th><th>R</th></tr></thead><tbody>{result.trades.slice(0,100).map((t,i)=><tr key={i} className="border-t border-slate-200 dark:border-slate-800"><td className="p-2 font-semibold">{t.symbol}</td><td className="text-center whitespace-nowrap">{new Date(t.signal_at).toLocaleString('en-IN')}</td><td className="text-center">{t.contract||'—'}</td><td className="text-center">{fmt(t.atr_pct)}%</td><td className="text-center">₹{fmt(t.entry)}</td><td className="text-center">₹{fmt(t.stop)}</td><td className="text-center">₹{fmt(t.target)}</td><td className="text-center font-semibold">{t.outcome}</td><td className={`text-center font-semibold ${t.net_r>0?'text-emerald-600':'text-red-600'}`}>{t.net_r>0?'+':''}{fmt(t.net_r,3)}R</td></tr>)}</tbody></table></div></div>}
 {(result.errors?.length??0)>0&&<div className="rounded-lg border border-amber-200 p-3 text-xs text-amber-700">{result.errors!.length} contract/data errors were excluded rather than fabricated.</div>}
 </>}
 </CardBody></Card>
}
