import { useMemo,useState } from 'react';
import { LockKeyhole,Play } from 'lucide-react';
import { Badge,Button,Card,CardBody,CardHeader } from '@/components/ui';
import { ALPHAPILOT_API_BASE } from '@/lib/alphaPilotApi';

type Row={setup_type:string;direction:'LONG'|'SHORT';trades:number;wins:number;losses:number;win_rate:number;average_r:number;total_r:number;profit_factor:number;ambiguous:number;state:'PROMISING'|'WEAK'|'LOW_SAMPLE'};
type Result={start_date:string;end_date:string;observations:number;rows:Row[];errors:any[]};
type Block={id:string;purpose:string;start:string;end:string;symbols:string[]};
const BLOCKS:Block[]=[
 {id:'C-OOS-1',purpose:'Forward dates · development symbols',start:'2026-08-11',end:'2026-08-24',symbols:['RELIANCE','HDFCBANK','ICICIBANK','SBIN','TCS','INFY','TATASTEEL','MARUTI']},
 {id:'C-OOS-2',purpose:'Forward dates · new symbols A',start:'2026-08-11',end:'2026-08-24',symbols:['AXISBANK','KOTAKBANK','BAJFINANCE','LT','HCLTECH','JSWSTEEL','HINDALCO','M&M']},
 {id:'C-OOS-3',purpose:'Forward dates · new symbols B',start:'2026-08-11',end:'2026-08-24',symbols:['SUNPHARMA','DRREDDY','CIPLA','ITC','TITAN','ADANIPORTS','ONGC','BHARTIARTL']},
];
const CANDIDATE='PULLBACK_CONTINUATION';
const DIRECTION='SHORT';
const MIN_TOTAL_TRADES=50, AVG_R_GATE=.10, WIN_GATE=55, PF_GATE=1.20;
function fmtR(v:number){return `${v>=0?'+':''}${Number(v||0).toFixed(3)}R`}
async function runBlock(b:Block):Promise<Result>{const r=await fetch(`${ALPHAPILOT_API_BASE}/v1/research/setup-discovery-v2`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({symbols:b.symbols,start_date:b.start,end_date:b.end})});if(!r.ok){let d='';try{const x=await r.json();d=x?.detail?`: ${x.detail}`:''}catch{}throw new Error(`${b.id} API ${r.status}${d}`)}return r.json()}
export function CandidateCValidator(){const[running,setRunning]=useState(false),[progress,setProgress]=useState(''),[results,setResults]=useState<Record<string,Result>>({}),[error,setError]=useState<string|null>(null);
 const rows=useMemo(()=>BLOCKS.map(b=>{const r=results[b.id];const row=r?.rows.find(x=>x.setup_type===CANDIDATE&&x.direction===DIRECTION);return{...b,result:r,row}}),[results]);
 const combined=useMemo(()=>{const rs=rows.flatMap(x=>x.row?[x.row]:[]);const trades=rs.reduce((s,x)=>s+x.trades,0),wins=rs.reduce((s,x)=>s+x.wins,0),losses=rs.reduce((s,x)=>s+x.losses,0),totalR=rs.reduce((s,x)=>s+x.total_r,0);const grossWin=wins;const grossLoss=losses;const pf=grossLoss?grossWin/grossLoss:(grossWin?99:0);const avg=trades?totalR/trades:0,win=trades?wins/trades*100:0;const positiveBlocks=rs.filter(x=>x.average_r>0).length;const pass=rows.every(x=>x.result)&&trades>=MIN_TOTAL_TRADES&&avg>=AVG_R_GATE&&win>=WIN_GATE&&pf>=PF_GATE&&positiveBlocks>=2;return{trades,wins,losses,totalR,avg,win,pf,positiveBlocks,pass}},[rows]);
 async function run(){setRunning(true);setError(null);setResults({});try{for(const b of BLOCKS){setProgress(`Running ${b.id} · ${b.purpose}`);const r=await runBlock(b);setResults(x=>({...x,[b.id]:r}));await new Promise(res=>setTimeout(res,800))}}catch(e){setError(e instanceof Error?e.message:'Candidate C OOS failed.')}finally{setProgress('');setRunning(false)}}
 const completed=rows.filter(x=>x.result).length;
 return <Card><CardHeader title="Frozen Candidate C Validator — Pullback Continuation SHORT" subtitle="Untouched forward OOS validation of the strongest replicated Setup Discovery v2 candidate. Production rules remain unchanged." action={<LockKeyhole size={18} className="text-violet-500"/>}/><CardBody className="space-y-4">
  <div className="flex gap-2 flex-wrap"><Badge variant="blue">CANDIDATE C FROZEN</Badge><Badge variant="default">PULLBACK CONTINUATION</Badge><Badge variant="default">SHORT ONLY</Badge><Badge variant="default">NEXT 5m OPEN</Badge><Badge variant="default">FIXED 1R</Badge><Badge variant="default">NO RETUNING</Badge><Badge variant="default">RESEARCH ONLY</Badge><Badge variant="default">PRODUCTION UNCHANGED</Badge></div>
  <div className="flex items-center justify-between gap-4"><p className="text-xs text-slate-500">Candidate C is frozen exactly from Setup Discovery v2: EMA20 below EMA50, prior candle touches EMA20 and closes at/below it, then the signal candle closes below the prior low; stop remains max(prior high, EMA20 + 0.35 ATR). OOS uses 11–24 Aug only, split into three disjoint symbol groups. PASS is pre-registered as ≥50 combined trades, Avg R ≥ +0.10R, win rate ≥55%, PF ≥1.20 and positive Avg R in at least 2/3 blocks.</p><Button variant="primary" onClick={run} disabled={running}><Play size={14} className="inline mr-1"/>{running?'Running Candidate C OOS…':'Run Candidate C OOS'}</Button></div>
  {progress&&<div className="rounded-lg border p-3 text-xs">{progress}</div>}{error&&<div className="rounded-lg border border-red-200 p-3 text-sm text-red-600">{error}</div>}
  <div className="overflow-x-auto rounded-lg border"><table className="w-full text-xs"><thead><tr><th className="p-2 text-left">Block</th><th>Purpose</th><th>Symbols</th><th>Trades</th><th>Win</th><th>Avg R</th><th>PF</th><th>Status</th></tr></thead><tbody>{rows.map(x=><tr className="border-t" key={x.id}><td className="p-2 font-semibold">{x.id}</td><td className="text-center">{x.purpose}</td><td className="text-center">{x.symbols.length}</td><td className="text-center">{x.row?.trades??'—'}</td><td className="text-center">{x.row?`${x.row.win_rate.toFixed(1)}%`:'—'}</td><td className="text-center">{x.row?fmtR(x.row.average_r):'—'}</td><td className="text-center">{x.row?x.row.profit_factor.toFixed(2):'—'}</td><td className="text-center"><Badge variant={x.row?.state==='PROMISING'?'green':x.result?'red':'default'}>{x.result?(x.row?.state??'NO ROW'):'PENDING'}</Badge></td></tr>)}</tbody></table></div>
  {completed>0&&<div className="grid grid-cols-2 md:grid-cols-6 gap-3"><Stat label="Completed blocks" value={`${completed}/${BLOCKS.length}`}/><Stat label="Combined trades" value={String(combined.trades)}/><Stat label="Win rate" value={`${combined.win.toFixed(1)}%`}/><Stat label="Avg R" value={fmtR(combined.avg)}/><Stat label="Profit Factor" value={combined.pf.toFixed(2)}/><div className="rounded-lg border p-3"><p className="text-xs text-slate-500">Decision</p><Badge variant={completed<BLOCKS.length?'default':combined.pass?'green':'red'}>{completed<BLOCKS.length?'INCOMPLETE':combined.pass?'PASS — FREEZE FOR OPTION OOS':'FAIL — REJECT CANDIDATE C'}</Badge></div></div>}
  <p className="text-[11px] text-slate-500">This validator does not search alternatives and does not alter Candidate C after seeing OOS results. A PASS still does not authorize production; it only permits a separate historical option-premium OOS stage using the same frozen signal timestamps.</p>
 </CardBody></Card>}
function Stat({label,value}:{label:string;value:string}){return <div className="rounded-lg border p-3"><p className="text-xs text-slate-500">{label}</p><p className="text-lg font-bold">{value}</p></div>}
