import { useMemo,useState } from 'react';
import { LockKeyhole,Play } from 'lucide-react';
import { Badge,Button,Card,CardBody,CardHeader } from '@/components/ui';
import { ALPHAPILOT_API_BASE } from '@/lib/alphaPilotApi';

type Row={setup_type:string;direction:'LONG'|'SHORT';method:'NEXT_OPEN'|'BREAK_CONFIRMATION'|'PULLBACK_ENTRY';signals:number;fills:number;resolved:number;fill_rate:number;wins:number;losses:number;win_rate:number;average_r_filled:number;average_r_per_signal:number;total_r:number;profit_factor:number;delta_vs_next_open:number|null;ambiguous:number;state:'CONTROL'|'IMPROVED'|'WEAK'|'LOW_SAMPLE'};
type Result={start_date:string;end_date:string;errors:any[];execution_structure_v1:{rows:Row[]}};
type Block={id:string;purpose:string;start:string;end:string;symbols:string[]};

const SYMBOLS=['RELIANCE','HDFCBANK','ICICIBANK','SBIN','TCS','INFY','TATASTEEL','MARUTI','AXISBANK','KOTAKBANK','LT','HINDALCO'];
const BLOCKS:Block[]=[
 {id:'H-OOS-1',purpose:'Untouched earlier execution holdout A',start:'2026-01-05',end:'2026-01-16',symbols:SYMBOLS},
 {id:'H-OOS-2',purpose:'Untouched earlier execution holdout B',start:'2026-01-19',end:'2026-01-30',symbols:SYMBOLS},
 {id:'H-OOS-3',purpose:'Untouched earlier execution holdout C',start:'2026-02-02',end:'2026-02-13',symbols:SYMBOLS},
];
const SETUP='FAILED_BREAKOUT_REVERSAL';
const DIRECTION='LONG';
const METHOD='PULLBACK_ENTRY';
const MIN_SIGNALS=100, MIN_FILL_RATE=60, AVG_R_SIGNAL_GATE=.10, DELTA_GATE=.10, WIN_GATE=55, PF_GATE=1.20;

function fmtR(v:number|null|undefined){if(v==null)return '—';return `${v>=0?'+':''}${Number(v).toFixed(3)}R`}
async function runBlock(b:Block):Promise<Result>{const r=await fetch(`${ALPHAPILOT_API_BASE}/v1/research/setup-discovery-v2`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({symbols:b.symbols,start_date:b.start,end_date:b.end})});if(!r.ok){let d='';try{const x=await r.json();d=x?.detail?`: ${x.detail}`:''}catch{}throw new Error(`${b.id} API ${r.status}${d}`)}return r.json()}

export function CandidateHExecutionValidator(){
 const[running,setRunning]=useState(false),[progress,setProgress]=useState(''),[results,setResults]=useState<Record<string,Result>>({}),[error,setError]=useState<string|null>(null);
 const rows=useMemo(()=>BLOCKS.map(b=>{const r=results[b.id];const all=r?.execution_structure_v1?.rows||[];const alt=all.find(x=>x.setup_type===SETUP&&x.direction===DIRECTION&&x.method===METHOD);const control=all.find(x=>x.setup_type===SETUP&&x.direction===DIRECTION&&x.method==='NEXT_OPEN');return{...b,result:r,alt,control}}),[results]);
 const combined=useMemo(()=>{const rs=rows.flatMap(x=>x.alt?[x.alt]:[]);const signals=rs.reduce((s,x)=>s+x.signals,0),fills=rs.reduce((s,x)=>s+x.fills,0),wins=rs.reduce((s,x)=>s+x.wins,0),losses=rs.reduce((s,x)=>s+x.losses,0),totalR=rs.reduce((s,x)=>s+x.total_r,0);const avgPerSignal=signals?totalR/signals:0;const fillRate=signals?fills/signals*100:0;const winRate=(wins+losses)?wins/(wins+losses)*100:0;const pf=losses?wins/losses:(wins?99:0);const weightedDelta=signals?rs.reduce((s,x)=>s+(x.delta_vs_next_open||0)*x.signals,0)/signals:0;const positiveAltBlocks=rs.filter(x=>x.average_r_per_signal>0).length;const positiveDeltaBlocks=rs.filter(x=>(x.delta_vs_next_open||0)>0).length;const complete=rows.every(x=>x.result&&x.alt&&x.control);const pass=complete&&signals>=MIN_SIGNALS&&fillRate>=MIN_FILL_RATE&&avgPerSignal>=AVG_R_SIGNAL_GATE&&weightedDelta>=DELTA_GATE&&winRate>=WIN_GATE&&pf>=PF_GATE&&positiveAltBlocks>=2&&positiveDeltaBlocks===3;return{signals,fills,wins,losses,totalR,avgPerSignal,fillRate,winRate,pf,weightedDelta,positiveAltBlocks,positiveDeltaBlocks,pass}},[rows]);
 async function run(){setRunning(true);setError(null);setResults({});try{for(const b of BLOCKS){setProgress(`Running ${b.id} · ${b.start} → ${b.end}`);const r=await runBlock(b);if(!r.execution_structure_v1)throw new Error(`${b.id}: Execution Structure v1 payload is unavailable`);setResults(x=>({...x,[b.id]:r}));await new Promise(res=>setTimeout(res,900))}}catch(e){setError(e instanceof Error?e.message:'Candidate H OOS failed.')}finally{setProgress('');setRunning(false)}}
 const completed=rows.filter(x=>x.result).length;
 return <Card><CardHeader title="Frozen Candidate H Validator — Failed Breakout LONG × Pullback Entry" subtitle="Untouched execution OOS for the strongest replicated Execution-Structure v1 candidate. Production execution remains unchanged." action={<LockKeyhole size={18} className="text-violet-500"/>}/><CardBody className="space-y-4">
  <div className="flex gap-2 flex-wrap"><Badge variant="blue">CANDIDATE H FROZEN</Badge><Badge variant="default">FAILED BREAKOUT REVERSAL</Badge><Badge variant="default">LONG ONLY</Badge><Badge variant="default">PULLBACK ENTRY</Badge><Badge variant="default">3-BAR WINDOW</Badge><Badge variant="default">0.25 ATR RETRACEMENT</Badge><Badge variant="default">FIXED 1R</Badge><Badge variant="default">NO RETUNING</Badge><Badge variant="default">RESEARCH ONLY</Badge><Badge variant="default">PRODUCTION UNCHANGED</Badge></div>
  <div className="flex items-center justify-between gap-4"><p className="text-xs text-slate-500">Candidate H is frozen exactly from Execution-Structure Discovery v1: the existing FAILED_BREAKOUT_REVERSAL LONG signal is unchanged, but entry waits up to 3 bars for a 0.25 ATR pullback from the signal close. The original structural stop and fixed 1R target remain unchanged; unfilled signals count as 0R. Holdout dates 05-Jan → 13-Feb were not used in the execution discovery blocks. PASS is pre-registered as ≥100 signals, ≥60% fill rate, Avg R per original signal ≥+0.10R, weighted lift versus NEXT_OPEN ≥+0.10R, filled win rate ≥55%, PF ≥1.20, positive alternative expectancy in at least 2/3 blocks and positive lift in all 3 blocks.</p><Button variant="primary" onClick={run} disabled={running}><Play size={14} className="inline mr-1"/>{running?'Running Candidate H OOS…':'Run Candidate H OOS'}</Button></div>
  {progress&&<div className="rounded-lg border p-3 text-xs">{progress}</div>}{error&&<div className="rounded-lg border border-red-200 p-3 text-sm text-red-600">{error}</div>}
  <div className="overflow-x-auto rounded-lg border"><table className="w-full text-xs"><thead><tr><th className="p-2 text-left">Block</th><th>Dates</th><th>Signals</th><th>Fill</th><th>Filled win</th><th>Avg R / signal</th><th>Δ vs open</th><th>PF</th><th>Status</th></tr></thead><tbody>{rows.map(x=><tr className="border-t" key={x.id}><td className="p-2 font-semibold">{x.id}</td><td className="text-center">{x.start} → {x.end}</td><td className="text-center">{x.alt?.signals??'—'}</td><td className="text-center">{x.alt?`${x.alt.fill_rate.toFixed(1)}%`:'—'}</td><td className="text-center">{x.alt?`${x.alt.win_rate.toFixed(1)}%`:'—'}</td><td className="text-center">{x.alt?fmtR(x.alt.average_r_per_signal):'—'}</td><td className="text-center font-semibold">{x.alt?fmtR(x.alt.delta_vs_next_open):'—'}</td><td className="text-center">{x.alt?x.alt.profit_factor.toFixed(2):'—'}</td><td className="text-center"><Badge variant={x.alt?.state==='IMPROVED'?'green':x.result?'red':'default'}>{x.result?(x.alt?.state??'NO ROW'):'PENDING'}</Badge></td></tr>)}</tbody></table></div>
  {completed>0&&<div className="grid grid-cols-2 md:grid-cols-5 gap-3"><Stat label="Completed blocks" value={`${completed}/3`}/><Stat label="Combined signals" value={String(combined.signals)}/><Stat label="Combined fill" value={`${combined.fillRate.toFixed(1)}%`}/><Stat label="Avg R / signal" value={fmtR(combined.avgPerSignal)}/><Stat label="Weighted Δ vs open" value={fmtR(combined.weightedDelta)}/><Stat label="Filled win rate" value={`${combined.winRate.toFixed(1)}%`}/><Stat label="Profit Factor" value={combined.pf.toFixed(2)}/><Stat label="Positive alt blocks" value={`${combined.positiveAltBlocks}/3`}/><Stat label="Positive lift blocks" value={`${combined.positiveDeltaBlocks}/3`}/><div className="rounded-lg border p-3"><p className="text-xs text-slate-500">Decision</p><Badge variant={completed<3?'default':combined.pass?'green':'red'}>{completed<3?'INCOMPLETE':combined.pass?'PASS — FREEZE EXECUTION FOR OPTION OOS':'FAIL — REJECT CANDIDATE H'}</Badge></div></div>}
  <p className="text-[11px] text-slate-500">This validator tests only the pre-existing FAILED_BREAKOUT_REVERSAL LONG × PULLBACK_ENTRY candidate. It does not search the other replicated methods or alter the 3-bar/0.25 ATR entry rule after seeing holdout results. A PASS still cannot change live execution; it only permits a separately frozen option-premium validation stage.</p>
 </CardBody></Card>}
function Stat({label,value}:{label:string;value:string}){return <div className="rounded-lg border p-3"><p className="text-xs text-slate-500">{label}</p><p className="text-lg font-bold">{value}</p></div>}
