import { useState } from 'react';
import { ShieldCheck,Play } from 'lucide-react';
import { Badge,Button,Card,CardBody,CardHeader } from '@/components/ui';
import { runCandidateValidator,type CandidateStats,type CandidateTrade,type CandidateValidatorResponse } from '@/lib/candidateValidatorApi';

const BLOCKS=[
 {id:'OOS-1',label:'Original untouched block',symbols:['MARUTI','EICHERMOT','INDUSINDBK','JSWSTEEL','TITAN','NESTLEIND','GRASIM','BRITANNIA','LT','DRREDDY','BAJFINANCE','M&M','SUNPHARMA','ADANIPORTS','KOTAKBANK'],start:'2026-08-04',end:'2026-08-13'},
 {id:'OOS-2',label:'Forward date block',symbols:['MARUTI','EICHERMOT','INDUSINDBK','JSWSTEEL','TITAN','NESTLEIND','GRASIM','BRITANNIA','LT','DRREDDY','BAJFINANCE','M&M','SUNPHARMA','ADANIPORTS','KOTAKBANK'],start:'2026-08-14',end:'2026-08-24'},
 {id:'OOS-3',label:'New-symbol block',symbols:['HCLTECH','WIPRO','TECHM','BHARTIARTL','ASIANPAINT','ULTRACEMCO','CIPLA','TATAMOTORS','POWERGRID','NTPC','COALINDIA','BEL','TRENT','HDFCLIFE','SBILIFE'],start:'2026-08-04',end:'2026-08-13'},
 {id:'OOS-4',label:'New symbols + forward dates',symbols:['HCLTECH','WIPRO','TECHM','BHARTIARTL','ASIANPAINT','ULTRACEMCO','CIPLA','TATAMOTORS','POWERGRID','NTPC','COALINDIA','BEL','TRENT','HDFCLIFE','SBILIFE'],start:'2026-08-14',end:'2026-08-24'},
] as const;
const COST_BPS=10,SAMPLE_BARS=3,MAX_TRADES=250;
function fmt(v:unknown,d=2){const n=Number(v);return Number.isFinite(n)?n.toFixed(d):'—'}
function stats(trades:CandidateTrade[]):CandidateStats{const rs=trades.map(t=>Number(t.net_r)||0),wins=rs.filter(r=>r>0),losses=rs.filter(r=>r<0);let eq=0,peak=0,dd=0,streak=0,maxStreak=0;for(const r of rs){eq+=r;peak=Math.max(peak,eq);dd=Math.max(dd,peak-eq);if(r<0){streak++;maxStreak=Math.max(maxStreak,streak)}else streak=0}const gp=wins.reduce((a,b)=>a+b,0),gl=Math.abs(losses.reduce((a,b)=>a+b,0));return{trades:trades.length,wins:wins.length,losses:losses.length,win_rate_pct:trades.length?wins.length/trades.length*100:0,avg_r:trades.length?rs.reduce((a,b)=>a+b,0)/trades.length:0,total_r:rs.reduce((a,b)=>a+b,0),profit_factor:gl?gp/gl:gp?999:0,max_drawdown_r:dd,max_consecutive_losses:maxStreak,avg_mfe_r:trades.length?trades.reduce((a,t)=>a+(Number((t as any).mfe_r)||0),0)/trades.length:0,avg_mae_r:trades.length?trades.reduce((a,t)=>a+(Number((t as any).mae_r)||0),0)/trades.length:0,t1:trades.filter(t=>t.outcome==='T1').length,sl:trades.filter(t=>t.outcome==='SL').length,eod:trades.filter(t=>t.outcome==='EOD').length}}
function status(s:CandidateStats){return s.trades>=50&&s.avg_r>0&&s.profit_factor>1?'PASS':s.trades>=25&&s.avg_r>0?'WATCH':s.trades>=25?'FAIL':'INSUFFICIENT_SAMPLE'}
function StatusBadge({value}:{value:string}){return <Badge variant={value==='PASS'?'green':value==='WATCH'?'blue':value==='FAIL'?'red':'default'}>{value}</Badge>}
export function CandidateValidator(){
 const [running,setRunning]=useState(false),[progress,setProgress]=useState(''),[error,setError]=useState<string|null>(null),[results,setResults]=useState<Array<{block:typeof BLOCKS[number];result:CandidateValidatorResponse}>>([]);
 async function run(){setRunning(true);setError(null);setResults([]);const out:Array<{block:typeof BLOCKS[number];result:CandidateValidatorResponse}>=[];try{for(let i=0;i<BLOCKS.length;i++){const block=BLOCKS[i];setProgress(`Running ${block.id} (${i+1}/${BLOCKS.length})…`);const result=await runCandidateValidator({symbols:[...block.symbols],start_date:block.start,end_date:block.end,round_trip_cost_bps:COST_BPS,sample_every_bars:SAMPLE_BARS,max_trades:MAX_TRADES});out.push({block,result});setResults([...out])}}catch(e){setError(e instanceof Error?e.message:'Multi-block candidate validation failed.')}finally{setRunning(false);setProgress('')}}
 const allTrades=results.flatMap(x=>x.result.trades||[]).sort((a,b)=>String(a.signal_at).localeCompare(String(b.signal_at)));const combined=stats(allTrades);const combinedStatus=status(combined);const errors=results.reduce((n,x)=>n+(x.result.errors?.length||0),0);
 return <Card><CardHeader title="Frozen Candidate Validator v2 — Multi-Block OOS" subtitle="One-click sample expansion for frozen Candidate A: PE × RANGE × HIGH ATR (≥5%). Candidate rules and production rules cannot be changed here." action={<ShieldCheck size={18} className="text-emerald-500"/>}/><CardBody className="space-y-4">
 <div className="flex gap-2 flex-wrap"><Badge variant="green">CANDIDATE A FROZEN</Badge><Badge variant="default">NO RETUNING</Badge><Badge variant="default">RESEARCH ONLY</Badge><Badge variant="default">PRODUCTION UNCHANGED</Badge><Badge variant="blue">MULTI-BLOCK OOS PRESET LOADED</Badge></div>
 <div className="rounded-lg border border-blue-200 bg-blue-50/40 p-3 text-xs text-blue-700 dark:border-blue-900 dark:bg-blue-950/20 dark:text-blue-300">The old single block produced only 12 trades, so it is not enough for the ≥50-trade validation gate. v2 locks four independent expansion blocks: forward dates, new symbols, and their cross-block. No threshold is optimized from results.</div>
 <div className="overflow-x-auto rounded-lg border border-slate-200 dark:border-slate-800"><table className="w-full text-xs"><thead className="bg-slate-50 dark:bg-slate-900"><tr><th className="p-2 text-left">Block</th><th className="text-left">Purpose</th><th>Dates</th><th>Symbols</th><th>Trades</th><th>Avg R</th><th>PF</th><th>Status</th></tr></thead><tbody>{BLOCKS.map(block=>{const r=results.find(x=>x.block.id===block.id)?.result;return <tr key={block.id} className="border-t border-slate-200 dark:border-slate-800"><td className="p-2 font-semibold">{block.id}</td><td>{block.label}</td><td className="text-center whitespace-nowrap">{block.start} → {block.end}</td><td className="text-center">{block.symbols.length}</td><td className="text-center">{r?.summary.trades??'—'}</td><td className="text-center">{r?`${r.summary.avg_r>0?'+':''}${fmt(r.summary.avg_r,3)}R`:'—'}</td><td className="text-center">{r?fmt(r.summary.profit_factor):'—'}</td><td className="text-center">{r?<StatusBadge value={r.status}/>:<Badge variant="default">PENDING</Badge>}</td></tr>})}</tbody></table></div>
 <div className="flex items-center justify-between gap-3 flex-wrap"><p className="text-[11px] text-slate-500">Locked execution assumptions: next 5m open · fixed 1R target · frozen premium-risk stop · conservative same-candle ordering · 10 bps cost · non-overlapping trades · sample every 3 bars.</p><Button variant="primary" onClick={run} disabled={running}><Play size={14} className="inline mr-1"/>{running?progress:'Run Full OOS Expansion'}</Button></div>
 {error&&<div className="rounded-lg border border-red-200 p-3 text-sm text-red-600">{error}</div>}
 {results.length>0&&<><div className="flex items-center gap-3"><StatusBadge value={combinedStatus}/><p className="text-xs text-slate-500">Combined evidence across {results.length}/{BLOCKS.length} locked blocks. Target is ≥50 trades; 100+ remains preferable.</p></div><div className="grid grid-cols-2 md:grid-cols-6 gap-3"><div className="rounded-lg border p-3"><p className="text-xs text-slate-500">Combined trades</p><p className="text-lg font-bold">{combined.trades}</p></div><div className="rounded-lg border p-3"><p className="text-xs text-slate-500">Win rate</p><p className="text-lg font-bold">{fmt(combined.win_rate_pct,1)}%</p></div><div className="rounded-lg border p-3"><p className="text-xs text-slate-500">Avg R</p><p className="text-lg font-bold">{combined.avg_r>0?'+':''}{fmt(combined.avg_r,3)}R</p></div><div className="rounded-lg border p-3"><p className="text-xs text-slate-500">Total R</p><p className="text-lg font-bold">{combined.total_r>0?'+':''}{fmt(combined.total_r)}R</p></div><div className="rounded-lg border p-3"><p className="text-xs text-slate-500">Profit Factor</p><p className="text-lg font-bold">{fmt(combined.profit_factor)}</p></div><div className="rounded-lg border p-3"><p className="text-xs text-slate-500">Max DD</p><p className="text-lg font-bold">{fmt(combined.max_drawdown_r)}R</p></div></div><p className="text-xs text-slate-500">{errors} contract/data errors were excluded rather than fabricated. Do not alter Candidate A based on any individual block. Review the combined result only after all four blocks complete.</p></>}
 </CardBody></Card>
}
