import { useState } from 'react';
import { ShieldCheck,Play } from 'lucide-react';
import { Badge,Button,Card,CardBody,CardHeader } from '@/components/ui';
import { runCandidateBValidator,type CandidateBStats,type CandidateBTrade } from '@/lib/candidateBValidatorApi';

const DEV_SYMBOLS=['RELIANCE','SBIN','AXISBANK','HDFCBANK','ICICIBANK','TATASTEEL','HINDALCO','ONGC','INFY','TCS'] as const;
const NEW_SYMBOLS=['MARUTI','EICHERMOT','INDUSINDBK','JSWSTEEL','TITAN','NESTLEIND','GRASIM','BRITANNIA','LT','DRREDDY','BAJFINANCE','M&M','SUNPHARMA','ADANIPORTS','KOTAKBANK'] as const;
const BLOCKS=[
 {id:'B-OOS-1',label:'Earlier-date holdout',symbols:DEV_SYMBOLS,start:'2026-07-06',end:'2026-07-17'},
 {id:'B-OOS-2',label:'New-symbol holdout',symbols:NEW_SYMBOLS,start:'2026-07-20',end:'2026-08-03'},
 {id:'B-OOS-3',label:'New symbols × earlier dates',symbols:NEW_SYMBOLS,start:'2026-07-06',end:'2026-07-17'},
] as const;
const COST_BPS=10,SAMPLE_BARS=3,MAX_TRADES=250,RETRIES=3,PAUSE_MS=1800;
const CHECKPOINT_KEY='alphapilot.candidateB.oos.single-symbol.v1';
type BlockResult={summary:CandidateBStats;status:string;trades:CandidateBTrade[];errors:Array<Record<string,unknown>>};
type SavedRun={trades:CandidateBTrade[];errors:Array<Record<string,unknown>>};
type SavedRuns=Record<string,SavedRun>;
function fmt(v:unknown,d=2){const n=Number(v);return Number.isFinite(n)?n.toFixed(d):'—'}
function stats(trades:CandidateBTrade[]):CandidateBStats{const rs=trades.map(t=>Number(t.net_r)||0),wins=rs.filter(r=>r>0),losses=rs.filter(r=>r<0);let eq=0,peak=0,dd=0,streak=0,maxStreak=0;for(const r of rs){eq+=r;peak=Math.max(peak,eq);dd=Math.max(dd,peak-eq);if(r<0){streak++;maxStreak=Math.max(maxStreak,streak)}else streak=0}const gp=wins.reduce((a,b)=>a+b,0),gl=Math.abs(losses.reduce((a,b)=>a+b,0));return{trades:trades.length,wins:wins.length,losses:losses.length,win_rate_pct:trades.length?wins.length/trades.length*100:0,avg_r:trades.length?rs.reduce((a,b)=>a+b,0)/trades.length:0,total_r:rs.reduce((a,b)=>a+b,0),profit_factor:gl?gp/gl:gp?999:0,max_drawdown_r:dd,max_consecutive_losses:maxStreak,avg_mfe_r:trades.length?trades.reduce((a,t)=>a+(Number((t as CandidateBTrade&{mfe_r?:number}).mfe_r)||0),0)/trades.length:0,avg_mae_r:trades.length?trades.reduce((a,t)=>a+(Number((t as CandidateBTrade&{mae_r?:number}).mae_r)||0),0)/trades.length:0,t1:trades.filter(t=>t.outcome==='T1').length,sl:trades.filter(t=>t.outcome==='SL').length,eod:trades.filter(t=>t.outcome==='EOD').length}}
function status(s:CandidateBStats){return s.trades>=50&&s.avg_r>0&&s.profit_factor>1?'PASS':s.trades>=25&&s.avg_r>0?'WATCH':s.trades>=25?'FAIL':'INSUFFICIENT_SAMPLE'}
function StatusBadge({value}:{value:string}){return <Badge variant={value==='PASS'?'green':value==='WATCH'?'blue':value==='FAIL'?'red':'default'}>{value}</Badge>}
function sleep(ms:number){return new Promise(resolve=>setTimeout(resolve,ms))}
function key(blockId:string,symbol:string){return `${blockId}:${symbol}`}
function loadSaved():SavedRuns{if(typeof window==='undefined')return{};try{const raw=window.localStorage.getItem(CHECKPOINT_KEY);return raw?JSON.parse(raw) as SavedRuns:{}}catch{return{}}}
function saveRuns(runs:SavedRuns){if(typeof window==='undefined')return;try{window.localStorage.setItem(CHECKPOINT_KEY,JSON.stringify(runs))}catch{/* best effort */}}
function buildResults(runs:SavedRuns){const out:Array<{block:typeof BLOCKS[number];result:BlockResult}>=[];for(const block of BLOCKS){if(!block.symbols.every(symbol=>runs[key(block.id,symbol)]))continue;const trades=block.symbols.flatMap(symbol=>runs[key(block.id,symbol)].trades).sort((a,b)=>String(a.signal_at).localeCompare(String(b.signal_at))).slice(0,MAX_TRADES);const errors=block.symbols.flatMap(symbol=>runs[key(block.id,symbol)].errors);const summary=stats(trades);out.push({block,result:{summary,status:status(summary),trades,errors}})}return out}
async function runSingle(symbol:string,start:string,end:string){let last:unknown;for(let attempt=0;attempt<=RETRIES;attempt++){try{return await runCandidateBValidator({symbols:[symbol],start_date:start,end_date:end,round_trip_cost_bps:COST_BPS,sample_every_bars:SAMPLE_BARS,max_trades:MAX_TRADES})}catch(e){last=e;if(attempt<RETRIES)await sleep([2000,5000,10000][attempt]??10000)}}throw last}

export function CandidateBValidator(){
 const [runs,setRuns]=useState<SavedRuns>(()=>loadSaved());
 const [running,setRunning]=useState(false),[progress,setProgress]=useState(''),[error,setError]=useState<string|null>(null),[results,setResults]=useState<Array<{block:typeof BLOCKS[number];result:BlockResult}>>(()=>buildResults(loadSaved()));
 const completedSymbols=Object.keys(runs).filter(k=>BLOCKS.some(b=>b.symbols.some(s=>key(b.id,s)===k))).length,totalSymbols=BLOCKS.reduce((n,b)=>n+b.symbols.length,0);
 async function run(){setRunning(true);setError(null);let working={...runs};try{let ordinal=0;for(const block of BLOCKS){for(const symbol of block.symbols){ordinal++;const runKey=key(block.id,symbol);if(working[runKey])continue;setProgress(`${block.id} · ${symbol} · ${ordinal}/${totalSymbols}`);try{const r=await runSingle(symbol,block.start,block.end);working={...working,[runKey]:{trades:r.trades||[],errors:r.errors||[]}};setRuns(working);saveRuns(working);setResults(buildResults(working));await sleep(PAUSE_MS)}catch(e){setError(`${block.id} / ${symbol}: ${e instanceof Error?e.message:'API request failed.'} Progress is saved; resume after the API recovers.`);return}}}}finally{setRunning(false);setProgress('')}}
 const allTrades=results.flatMap(x=>x.result.trades).sort((a,b)=>String(a.signal_at).localeCompare(String(b.signal_at))),combined=stats(allTrades),combinedStatus=status(combined),errors=results.reduce((n,x)=>n+x.result.errors.length,0);
 return <Card><CardHeader title="Frozen Candidate B Validator — Resumable OOS" subtitle="Candidate B frozen from v3: BUY PE when premium ATR remains NORMAL (2%≤ATR<5%) across consecutive sampled states and current Market Brain regime is TREND_LONG." action={<ShieldCheck size={18} className="text-emerald-500"/>}/><CardBody className="space-y-4">
 <div className="flex gap-2 flex-wrap"><Badge variant="red">CANDIDATE A REJECTED</Badge><Badge variant="green">CANDIDATE B FROZEN</Badge><Badge variant="default">NO RETUNING</Badge><Badge variant="default">RESEARCH ONLY</Badge><Badge variant="default">PRODUCTION UNCHANGED</Badge><Badge variant="blue">SINGLE-SYMBOL CHECKPOINTING</Badge></div>
 <div className="rounded-lg border border-emerald-200 bg-emerald-50/40 p-3 text-xs text-emerald-700 dark:border-emerald-900 dark:bg-emerald-950/20 dark:text-emerald-300">Candidate B was nominated because PE · ATR NORMAL→NORMAL · TREND_LONG had 95 development observations, 13.7% 1R hit rate and +8.2pp lift versus the 5.4% development baseline. The rule is now frozen exactly. These OOS blocks deliberately avoid 04-Aug-2026 onward, which was already examined during Candidate A validation.</div>
 <div className="overflow-x-auto rounded-lg border border-slate-200 dark:border-slate-800"><table className="w-full text-xs"><thead className="bg-slate-50 dark:bg-slate-900"><tr><th className="p-2 text-left">Block</th><th className="text-left">Purpose</th><th>Dates</th><th>Done</th><th>Trades</th><th>Avg R</th><th>PF</th><th>Status</th></tr></thead><tbody>{BLOCKS.map(block=>{const r=results.find(x=>x.block.id===block.id)?.result,done=block.symbols.filter(symbol=>runs[key(block.id,symbol)]).length;return <tr key={block.id} className="border-t border-slate-200 dark:border-slate-800"><td className="p-2 font-semibold">{block.id}</td><td>{block.label}</td><td className="text-center whitespace-nowrap">{block.start} → {block.end}</td><td className="text-center">{done}/{block.symbols.length}</td><td className="text-center">{r?.summary.trades??'—'}</td><td className="text-center">{r?`${r.summary.avg_r>0?'+':''}${fmt(r.summary.avg_r,3)}R`:'—'}</td><td className="text-center">{r?fmt(r.summary.profit_factor):'—'}</td><td className="text-center">{r?<StatusBadge value={r.status}/>:<Badge variant="default">{done?'PARTIAL':'PENDING'}</Badge>}</td></tr>})}</tbody></table></div>
 <div className="flex items-center justify-between gap-3 flex-wrap"><p className="text-[11px] text-slate-500">Checkpoint progress: {completedSymbols}/{totalSymbols} symbol-block tests. Frozen assumptions: PE only · ATR NORMAL→NORMAL using fixed 2%/5% buckets · current TREND_LONG · sample every 3 bars · next 5m open · fixed 1R target · frozen premium-risk stop · conservative same-candle ordering · 10 bps cost · non-overlapping trades.</p><Button variant="primary" onClick={run} disabled={running}><Play size={14} className="inline mr-1"/>{running?progress:completedSymbols?'Resume Candidate B OOS':'Run Candidate B OOS'}</Button></div>
 {error&&<div className="rounded-lg border border-red-200 p-3 text-sm text-red-600">{error}</div>}
 {results.length>0&&<><div className="flex items-center gap-3"><StatusBadge value={combinedStatus}/><p className="text-xs text-slate-500">Combined evidence across {results.length}/{BLOCKS.length} fully completed frozen blocks. ≥50 trades is the minimum decision sample; 100+ is preferable.</p></div><div className="grid grid-cols-2 md:grid-cols-6 gap-3"><div className="rounded-lg border p-3"><p className="text-xs text-slate-500">Combined trades</p><p className="text-lg font-bold">{combined.trades}</p></div><div className="rounded-lg border p-3"><p className="text-xs text-slate-500">Win rate</p><p className="text-lg font-bold">{fmt(combined.win_rate_pct,1)}%</p></div><div className="rounded-lg border p-3"><p className="text-xs text-slate-500">Avg R</p><p className="text-lg font-bold">{combined.avg_r>0?'+':''}{fmt(combined.avg_r,3)}R</p></div><div className="rounded-lg border p-3"><p className="text-xs text-slate-500">Total R</p><p className="text-lg font-bold">{combined.total_r>0?'+':''}{fmt(combined.total_r)}R</p></div><div className="rounded-lg border p-3"><p className="text-xs text-slate-500">Profit Factor</p><p className="text-lg font-bold">{fmt(combined.profit_factor)}</p></div><div className="rounded-lg border p-3"><p className="text-xs text-slate-500">Max DD</p><p className="text-lg font-bold">{fmt(combined.max_drawdown_r)}R</p></div></div><p className="text-xs text-slate-500">{errors} contract/data errors were excluded rather than fabricated. Do not alter Candidate B from any individual or combined OOS result.</p></>}
 </CardBody></Card>
}
