import { useMemo,useState } from 'react';
import { Calculator,Play } from 'lucide-react';
import { Badge,Button,Card,CardBody,CardHeader } from '@/components/ui';
import { ALPHAPILOT_API_BASE } from '@/lib/alphaPilotApi';

type Trade={symbol:string;option_entry_at?:string|null;option_entry?:number|null;premium_risk_percent?:number|null;net_r?:number|null;expiry?:string;strike?:number;gross_1r_outcome?:string};
type Result={candidate_fills_selected:number;trades:Trade[];errors:any[]};
const DATE='2026-08-17',STARTING_CAPITAL=12000;
const GROUPS=[
 ['RELIANCE','HDFCBANK','ICICIBANK','SBIN','TCS','INFY','TATASTEEL','MARUTI'],
 ['AXISBANK','KOTAKBANK','LT','HINDALCO','ONGC','HCLTECH','JSWSTEEL','M&M'],
 ['SUNPHARMA','DRREDDY','CIPLA','ITC','TITAN','ADANIPORTS','BAJFINANCE','BHARTIARTL'],
];
async function fetchGroup(symbols:string[]):Promise<Result>{const r=await fetch(`${ALPHAPILOT_API_BASE}/v1/research/candidate-h-option-oos`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({symbols,start_date:DATE,end_date:DATE,max_signals:80})});if(!r.ok){let d='';try{const x=await r.json();d=x?.detail?`: ${x.detail}`:''}catch{}throw new Error(`API ${r.status}${d}`)}return r.json()}
function money(v:number){return new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(v)}
export function CandidateHDayReplay(){const[running,setRunning]=useState(false),[results,setResults]=useState<Result[]>([]),[error,setError]=useState<string|null>(null),[progress,setProgress]=useState('');
 const replay=useMemo(()=>{const trades=results.flatMap(x=>x.trades||[]).filter(t=>typeof t.net_r==='number'&&typeof t.premium_risk_percent==='number').sort((a,b)=>String(a.option_entry_at||'').localeCompare(String(b.option_entry_at||'')));let capital=STARTING_CAPITAL;const rows=trades.map((t,i)=>{const before=capital,riskFrac=Number(t.premium_risk_percent)/100,netR=Number(t.net_r),pnl=before*riskFrac*netR;capital=Math.max(0,before+pnl);return{...t,n:i+1,before,pnl,after:capital}});return{rows,ending:capital,pnl:capital-STARTING_CAPITAL,returnPct:(capital/STARTING_CAPITAL-1)*100}},[results]);
 async function run(){setRunning(true);setError(null);setResults([]);try{const out:Result[]=[];for(let i=0;i<GROUPS.length;i++){setProgress(`Replaying 17 Aug · group ${i+1}/3`);out.push(await fetchGroup(GROUPS[i]));await new Promise(r=>setTimeout(r,900))}setResults(out)}catch(e){setError(e instanceof Error?e.message:'Day replay failed.')}finally{setProgress('');setRunning(false)}}
 return <Card><CardHeader title="Candidate H — ₹12,000 Day Replay (17 Aug 2026)" subtitle="Historical what-if using the frozen Candidate H option specification." action={<Calculator size={18} className="text-violet-500"/>}/><CardBody className="space-y-4">
  <div className="flex flex-wrap gap-2"><Badge variant="blue">17 AUG 2026</Badge><Badge variant="default">START ₹12,000</Badge><Badge variant="default">CANDIDATE H FROZEN</Badge><Badge variant="default">REAL OPTION CANDLES</Badge><Badge variant="default">10 BPS INCLUDED</Badge><Badge variant="default">WHAT-IF ONLY</Badge></div>
  <div className="flex items-center justify-between gap-4"><p className="text-xs text-slate-500">This replay finds every resolved Candidate H BUY CE trade on 17-Aug across the same 24-symbol research universe, sorts them by option-entry time, and compounds the available ₹12,000 through each trade. For this capital illustration, each trade is treated as if 100% of the then-available capital were deployed; the premium-risk percentage converts its net R result into account P&L. This is a theoretical capital replay: lot-size granularity, simultaneous-position capital conflicts and brokerage beyond the frozen 10 bps research cost are not reconstructed.</p><Button variant="primary" onClick={run} disabled={running}><Play size={14} className="inline mr-1"/>{running?'Running 17 Aug replay…':'Run ₹12,000 Day Replay'}</Button></div>
  {progress&&<div className="rounded-lg border p-3 text-xs">{progress}</div>}{error&&<div className="rounded-lg border border-red-200 p-3 text-sm text-red-600">{error}</div>}
  {results.length>0&&<><div className="grid grid-cols-2 md:grid-cols-4 gap-3"><Stat label="Starting capital" value={money(STARTING_CAPITAL)}/><Stat label="Resolved trades" value={String(replay.rows.length)}/><Stat label="End-of-day balance" value={money(replay.ending)}/><Stat label="Day P&L" value={`${replay.pnl>=0?'+':''}${money(replay.pnl)} (${replay.returnPct>=0?'+':''}${replay.returnPct.toFixed(1)}%)`}/></div>
  <div className="overflow-x-auto rounded-lg border"><table className="w-full text-xs"><thead><tr><th className="p-2 text-left">#</th><th>Time</th><th>Symbol</th><th>Contract</th><th>Premium</th><th>Risk</th><th>Net R</th><th>Capital before</th><th>P&L</th><th>Capital after</th></tr></thead><tbody>{replay.rows.map(r=><tr key={`${r.n}-${r.symbol}-${r.option_entry_at}`} className="border-t"><td className="p-2">{r.n}</td><td className="text-center">{r.option_entry_at?new Date(r.option_entry_at).toLocaleTimeString('en-IN',{hour:'2-digit',minute:'2-digit',timeZone:'Asia/Kolkata'}):'—'}</td><td className="text-center font-medium">{r.symbol}</td><td className="text-center">{r.strike?`${r.strike} CE`:'CE'}</td><td className="text-center">{typeof r.option_entry==='number'?`₹${r.option_entry.toFixed(2)}`:'—'}</td><td className="text-center">{Number(r.premium_risk_percent).toFixed(0)}%</td><td className="text-center font-semibold">{Number(r.net_r)>=0?'+':''}{Number(r.net_r).toFixed(3)}R</td><td className="text-center">{money(r.before)}</td><td className="text-center">{r.pnl>=0?'+':''}{money(r.pnl)}</td><td className="text-center font-semibold">{money(r.after)}</td></tr>)}</tbody></table></div>
  <p className="text-[11px] text-slate-500">If there were no resolved Candidate H option trades on 17-Aug, the balance stays ₹12,000. This panel does not change Candidate H's rejected option-OOS decision or any production rule.</p></>}
 </CardBody></Card>}
function Stat({label,value}:{label:string;value:string}){return <div className="rounded-lg border p-3"><p className="text-xs text-slate-500">{label}</p><p className="text-lg font-bold">{value}</p></div>}
