import { useMemo,useState } from 'react';
import { LockKeyhole,Play } from 'lucide-react';
import { Badge,Button,Card,CardBody,CardHeader } from '@/components/ui';
import { ALPHAPILOT_API_BASE } from '@/lib/alphaPilotApi';

type Row={setup_type:string;direction:'LONG'|'SHORT';trades:number;wins:number;losses:number;win_rate:number;average_r:number;total_r:number;profit_factor:number;ambiguous:number;state:'PROMISING'|'WEAK'|'LOW_SAMPLE'};
type Result={start_date:string;end_date:string;observations:number;rows:Row[];errors:any[]};
type Block={id:string;purpose:string;start:string;end:string;symbols:string[]};
const SYMBOLS=['RELIANCE','HDFCBANK','ICICIBANK','SBIN','TCS','INFY','TATASTEEL','MARUTI'];
const BLOCKS:Block[]=[
 {id:'D-OOS-1',purpose:'Untouched earlier holdout A',start:'2026-04-13',end:'2026-04-24',symbols:SYMBOLS},
 {id:'D-OOS-2',purpose:'Untouched earlier holdout B',start:'2026-04-27',end:'2026-05-08',symbols:SYMBOLS},
 {id:'D-OOS-3',purpose:'Untouched earlier holdout C',start:'2026-05-11',end:'2026-05-22',symbols:SYMBOLS},
];
const CANDIDATE='FAILED_BREAKOUT_REVERSAL';
const DIRECTION='SHORT';
const MIN_TOTAL_TRADES=75, AVG_R_GATE=.10, WIN_GATE=55, MIN_PROMISING_BLOCKS=2;
function fmtR(v:number){return `${v>=0?'+':''}${Number(v||0).toFixed(3)}R`}
async function runBlock(b:Block):Promise<Result>{const r=await fetch(`${ALPHAPILOT_API_BASE}/v1/research/setup-discovery-v2`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({symbols:b.symbols,start_date:b.start,end_date:b.end})});if(!r.ok){let d='';try{const x=await r.json();d=x?.detail?`: ${x.detail}`:''}catch{}throw new Error(`${b.id} API ${r.status}${d}`)}return r.json()}
export function CandidateDValidator(){const[running,setRunning]=useState(false),[progress,setProgress]=useState(''),[results,setResults]=useState<Record<string,Result>>({}),[error,setError]=useState<string|null>(null);
 const rows=useMemo(()=>BLOCKS.map(b=>{const r=results[b.id];const row=r?.rows.find(x=>x.setup_type===CANDIDATE&&x.direction===DIRECTION);return{...b,result:r,row}}),[results]);
 const combined=useMemo(()=>{const rs=rows.flatMap(x=>x.row?[x.row]:[]);const trades=rs.reduce((s,x)=>s+x.trades,0),wins=rs.reduce((s,x)=>s+x.wins,0),totalR=rs.reduce((s,x)=>s+x.total_r,0);const avg=trades?totalR/trades:0,win=trades?wins/trades*100:0;const positiveBlocks=rs.filter(x=>x.average_r>0).length;const promisingBlocks=rs.filter(x=>x.state==='PROMISING').length;const pass=rows.every(x=>x.result)&&trades>=MIN_TOTAL_TRADES&&avg>=AVG_R_GATE&&win>=WIN_GATE&&positiveBlocks===3&&promisingBlocks>=MIN_PROMISING_BLOCKS;return{trades,wins,totalR,avg,win,positiveBlocks,promisingBlocks,pass}},[rows]);
 async function run(){setRunning(true);setError(null);setResults({});try{for(const b of BLOCKS){setProgress(`Running ${b.id} · ${b.start} → ${b.end}`);const r=await runBlock(b);setResults(x=>({...x,[b.id]:r}));await new Promise(res=>setTimeout(res,800))}}catch(e){setError(e instanceof Error?e.message:'Candidate D OOS failed.')}finally{setProgress('');setRunning(false)}}
 const completed=rows.filter(x=>x.result).length;
 return <Card><CardHeader title="Frozen Candidate D Validator — Failed Breakout Reversal SHORT" subtitle="Untouched historical holdout for the second setup that had already replicated in Setup Discovery v2 before Candidate C OOS was seen." action={<LockKeyhole size={18} className="text-violet-500"/>}/><CardBody className="space-y-4">
  <div className="flex gap-2 flex-wrap"><Badge variant="blue">CANDIDATE D FROZEN</Badge><Badge variant="default">FAILED BREAKOUT REVERSAL</Badge><Badge variant="default">SHORT ONLY</Badge><Badge variant="default">SECONDARY CANDIDATE</Badge><Badge variant="default">NO RETUNING</Badge><Badge variant="default">RESEARCH ONLY</Badge><Badge variant="default">PRODUCTION UNCHANGED</Badge></div>
  <div className="flex items-center justify-between gap-4"><p className="text-xs text-slate-500">Candidate D is frozen exactly from Setup Discovery v2: the signal candle sweeps the prior 10-bar high by at least 0.10 ATR, closes back below that prior high, enters SHORT at the next 5m open, stop = signal high + 0.20 ATR, fixed 1R target. It was already the second replicated candidate before Candidate C OOS was observed; no rule was selected from Candidate C's failure. To account for sequential testing, this secondary-candidate gate is stricter: ≥75 combined trades, Avg R ≥ +0.10R, win rate ≥55%, positive Avg R in all 3 holdout blocks, and at least 2/3 blocks individually PROMISING.</p><Button variant="primary" onClick={run} disabled={running}><Play size={14} className="inline mr-1"/>{running?'Running Candidate D OOS…':'Run Candidate D OOS'}</Button></div>
  <div className="rounded-lg border border-amber-200 bg-amber-50/40 p-3 text-xs text-slate-600 dark:bg-amber-950/10">These dates (13-Apr → 22-May 2026) precede the Setup Discovery v2 development window. This is an untouched historical holdout rather than a forward-time holdout, so even a PASS would require a later forward confirmation before option-premium validation.</div>
  {progress&&<div className="rounded-lg border p-3 text-xs">{progress}</div>}{error&&<div className="rounded-lg border border-red-200 p-3 text-sm text-red-600">{error}</div>}
  <div className="overflow-x-auto rounded-lg border"><table className="w-full text-xs"><thead><tr><th className="p-2 text-left">Block</th><th>Purpose</th><th>Dates</th><th>Trades</th><th>Win</th><th>Avg R</th><th>PF</th><th>Status</th></tr></thead><tbody>{rows.map(x=><tr className="border-t" key={x.id}><td className="p-2 font-semibold">{x.id}</td><td className="text-center">{x.purpose}</td><td className="text-center">{x.start} → {x.end}</td><td className="text-center">{x.row?.trades??'—'}</td><td className="text-center">{x.row?`${x.row.win_rate.toFixed(1)}%`:'—'}</td><td className="text-center">{x.row?fmtR(x.row.average_r):'—'}</td><td className="text-center">{x.row?x.row.profit_factor.toFixed(2):'—'}</td><td className="text-center"><Badge variant={x.row?.state==='PROMISING'?'green':x.result?'red':'default'}>{x.result?(x.row?.state??'NO ROW'):'PENDING'}</Badge></td></tr>)}</tbody></table></div>
  {completed>0&&<div className="grid grid-cols-2 md:grid-cols-6 gap-3"><Stat label="Completed blocks" value={`${completed}/${BLOCKS.length}`}/><Stat label="Combined trades" value={String(combined.trades)}/><Stat label="Win rate" value={`${combined.win.toFixed(1)}%`}/><Stat label="Avg R" value={fmtR(combined.avg)}/><Stat label="Promising blocks" value={`${combined.promisingBlocks}/3`}/><div className="rounded-lg border p-3"><p className="text-xs text-slate-500">Decision</p><Badge variant={completed<BLOCKS.length?'default':combined.pass?'green':'red'}>{completed<BLOCKS.length?'INCOMPLETE':combined.pass?'PASS — REQUIRE FORWARD CONFIRMATION':'FAIL — REJECT CANDIDATE D'}</Badge></div></div>}
  <p className="text-[11px] text-slate-500">This validator tests only the pre-existing Candidate D and searches no alternatives. It does not modify Candidate D after results and cannot alter production. Candidate C remains rejected; Candidate D is not a retune of Candidate C.</p>
 </CardBody></Card>}
function Stat({label,value}:{label:string;value:string}){return <div className="rounded-lg border p-3"><p className="text-xs text-slate-500">{label}</p><p className="text-lg font-bold">{value}</p></div>}
