import { useMemo,useState } from 'react';
import { LockKeyhole,Play } from 'lucide-react';
import { Badge,Button,Card,CardBody,CardHeader } from '@/components/ui';
import { ALPHAPILOT_API_BASE } from '@/lib/alphaPilotApi';

type Row={pattern_type:string;direction:'LONG'|'SHORT';trades:number;wins:number;losses:number;win_rate:number;average_r:number;total_r:number;profit_factor:number;ambiguous:number;state:'PROMISING'|'WEAK'|'LOW_SAMPLE'};
type Result={start_date:string;end_date:string;observations:number;rows:Row[];errors:any[]};
type Block={id:string;purpose:string;start:string;end:string;symbols:string[]};
const SYMBOLS=['RELIANCE','HDFCBANK','ICICIBANK','SBIN','TCS','INFY','TATASTEEL','MARUTI','AXISBANK','KOTAKBANK','LT','HINDALCO'];
const BLOCKS:Block[]=[
 {id:'G-OOS-1',purpose:'Untouched earlier holdout A',start:'2026-03-02',end:'2026-03-13',symbols:SYMBOLS},
 {id:'G-OOS-2',purpose:'Untouched earlier holdout B',start:'2026-03-16',end:'2026-03-27',symbols:SYMBOLS},
 {id:'G-OOS-3',purpose:'Untouched earlier holdout C',start:'2026-03-30',end:'2026-04-10',symbols:SYMBOLS},
];
const CANDIDATE='DARK_CLOUD';
const DIRECTION='SHORT';
const MIN_TOTAL_TRADES=60, AVG_R_GATE=.10, WIN_GATE=55, PF_GATE=1.20;
function fmtR(v:number){return `${v>=0?'+':''}${Number(v||0).toFixed(3)}R`}
async function runBlock(b:Block):Promise<Result>{const r=await fetch(`${ALPHAPILOT_API_BASE}/v1/research/candlestick-discovery-v2`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({symbols:b.symbols,start_date:b.start,end_date:b.end})});if(!r.ok){let d='';try{const x=await r.json();d=x?.detail?`: ${x.detail}`:''}catch{}throw new Error(`${b.id} API ${r.status}${d}`)}return r.json()}
export function CandidateGValidator(){const[running,setRunning]=useState(false),[progress,setProgress]=useState(''),[results,setResults]=useState<Record<string,Result>>({}),[error,setError]=useState<string|null>(null);
 const rows=useMemo(()=>BLOCKS.map(b=>{const r=results[b.id];const row=r?.rows.find(x=>x.pattern_type===CANDIDATE&&x.direction===DIRECTION);return{...b,result:r,row}}),[results]);
 const combined=useMemo(()=>{const rs=rows.flatMap(x=>x.row?[x.row]:[]);const trades=rs.reduce((s,x)=>s+x.trades,0),wins=rs.reduce((s,x)=>s+x.wins,0),losses=rs.reduce((s,x)=>s+x.losses,0),totalR=rs.reduce((s,x)=>s+x.total_r,0);const pf=losses?wins/losses:(wins?99:0);const avg=trades?totalR/trades:0,win=trades?wins/trades*100:0;const positiveBlocks=rs.filter(x=>x.average_r>0).length,promisingBlocks=rs.filter(x=>x.state==='PROMISING').length;const pass=rows.every(x=>x.result)&&trades>=MIN_TOTAL_TRADES&&avg>=AVG_R_GATE&&win>=WIN_GATE&&pf>=PF_GATE&&positiveBlocks===3&&promisingBlocks>=2;return{trades,totalR,avg,win,pf,positiveBlocks,promisingBlocks,pass}},[rows]);
 async function run(){setRunning(true);setError(null);setResults({});try{for(const b of BLOCKS){setProgress(`Running ${b.id} · ${b.start} → ${b.end}`);const r=await runBlock(b);setResults(x=>({...x,[b.id]:r}));await new Promise(res=>setTimeout(res,900))}}catch(e){setError(e instanceof Error?e.message:'Candidate G OOS failed.')}finally{setProgress('');setRunning(false)}}
 const completed=rows.filter(x=>x.result).length;
 return <Card><CardHeader title="Frozen Candidate G Validator — Dark Cloud SHORT" subtitle="Untouched earlier holdout for the secondary Candlestick Discovery v2 candidate. Production rules remain unchanged." action={<LockKeyhole size={18} className="text-violet-500"/>}/><CardBody className="space-y-4">
  <div className="flex gap-2 flex-wrap"><Badge variant="blue">CANDIDATE G FROZEN</Badge><Badge variant="default">DARK CLOUD</Badge><Badge variant="default">SHORT ONLY</Badge><Badge variant="default">SECONDARY CANDIDATE</Badge><Badge variant="default">NEXT 5m OPEN</Badge><Badge variant="default">FIXED 1R</Badge><Badge variant="default">NO RETUNING</Badge><Badge variant="default">RESEARCH ONLY</Badge><Badge variant="default">PRODUCTION UNCHANGED</Badge></div>
  <div className="flex items-center justify-between gap-4"><p className="text-xs text-slate-500">Candidate G is the pre-existing secondary Candlestick Discovery v2 candidate: fixed prior rise, bullish first candle followed by a bearish candle that opens at/above the prior close and penetrates at least 50% into the first real body; next-5m-open SHORT entry, stop=max(pattern high protection, entry + 0.60 ATR), fixed 1R target and unchanged same-candle ambiguity exclusion. Because Morning Star was tested first, this secondary-candidate holdout uses untouched 02-Mar → 10-Apr dates and a stricter pre-registered gate: ≥60 combined trades, Avg R ≥ +0.10R, win rate ≥55%, PF ≥1.20, positive Avg R in all 3 blocks and at least 2/3 blocks individually PROMISING.</p><Button variant="primary" onClick={run} disabled={running}><Play size={14} className="inline mr-1"/>{running?'Running Candidate G OOS…':'Run Candidate G OOS'}</Button></div>
  {progress&&<div className="rounded-lg border p-3 text-xs">{progress}</div>}{error&&<div className="rounded-lg border border-red-200 p-3 text-sm text-red-600">{error}</div>}
  <div className="overflow-x-auto rounded-lg border"><table className="w-full text-xs"><thead><tr><th className="p-2 text-left">Block</th><th>Purpose</th><th>Dates</th><th>Symbols</th><th>Trades</th><th>Win</th><th>Avg R</th><th>PF</th><th>Status</th></tr></thead><tbody>{rows.map(x=><tr className="border-t" key={x.id}><td className="p-2 font-semibold">{x.id}</td><td className="text-center">{x.purpose}</td><td className="text-center">{x.start} → {x.end}</td><td className="text-center">{x.symbols.length}</td><td className="text-center">{x.row?.trades??'—'}</td><td className="text-center">{x.row?`${x.row.win_rate.toFixed(1)}%`:'—'}</td><td className="text-center">{x.row?fmtR(x.row.average_r):'—'}</td><td className="text-center">{x.row?x.row.profit_factor.toFixed(2):'—'}</td><td className="text-center"><Badge variant={x.row?.state==='PROMISING'?'green':x.result?'red':'default'}>{x.result?(x.row?.state??'NO ROW'):'PENDING'}</Badge></td></tr>)}</tbody></table></div>
  {completed>0&&<div className="grid grid-cols-2 md:grid-cols-7 gap-3"><Stat label="Completed blocks" value={`${completed}/${BLOCKS.length}`}/><Stat label="Combined trades" value={String(combined.trades)}/><Stat label="Win rate" value={`${combined.win.toFixed(1)}%`}/><Stat label="Avg R" value={fmtR(combined.avg)}/><Stat label="Profit Factor" value={combined.pf.toFixed(2)}/><Stat label="Promising blocks" value={`${combined.promisingBlocks}/3`}/><div className="rounded-lg border p-3"><p className="text-xs text-slate-500">Decision</p><Badge variant={completed<BLOCKS.length?'default':combined.pass?'green':'red'}>{completed<BLOCKS.length?'INCOMPLETE':combined.pass?'PASS — REQUIRE LATER FORWARD CONFIRMATION':'FAIL — REJECT CANDIDATE G'}</Badge></div></div>}
  <p className="text-[11px] text-slate-500">This validator tests only the Dark Cloud SHORT pattern that had already replicated before Candidate F OOS was observed. It searches no alternatives and changes no v2 thresholds. Even a PASS would still require a later genuinely forward confirmation before option-premium validation.</p>
 </CardBody></Card>}
function Stat({label,value}:{label:string;value:string}){return <div className="rounded-lg border p-3"><p className="text-xs text-slate-500">{label}</p><p className="text-lg font-bold">{value}</p></div>}
