import { useMemo,useState } from 'react';
import { GitCompareArrows,Play } from 'lucide-react';
import { Badge,Button,Card,CardBody,CardHeader } from '@/components/ui';
import { ALPHAPILOT_API_BASE } from '@/lib/alphaPilotApi';

type Row={setup_type:string;direction:'LONG'|'SHORT';method:'NEXT_OPEN'|'BREAK_CONFIRMATION'|'PULLBACK_ENTRY';signals:number;fills:number;resolved:number;fill_rate:number;wins:number;losses:number;win_rate:number;average_r_filled:number;average_r_per_signal:number;total_r:number;profit_factor:number;delta_vs_next_open:number|null;ambiguous:number;state:'CONTROL'|'IMPROVED'|'WEAK'|'LOW_SAMPLE'};
type Result={start_date:string;end_date:string;errors:any[];execution_structure_v1:{rows:Row[];fixed_methods:Record<string,string>;fixed_improvement_gate:Record<string,number>}};
type Block={id:string;start:string;end:string};
const BLOCKS:Block[]=[
 {id:'X-0A',start:'2026-05-25',end:'2026-06-05'},
 {id:'X-0B',start:'2026-06-08',end:'2026-06-19'},
 {id:'X-0C',start:'2026-06-22',end:'2026-07-03'},
 {id:'X-1',start:'2026-07-06',end:'2026-07-17'},
 {id:'X-2',start:'2026-07-20',end:'2026-07-31'},
 {id:'X-3',start:'2026-08-03',end:'2026-08-10'},
];
const SYMBOLS=['RELIANCE','HDFCBANK','ICICIBANK','SBIN','TCS','INFY','TATASTEEL','MARUTI'];
function fmtR(v:number|null|undefined){if(v==null)return '—';return `${v>=0?'+':''}${Number(v).toFixed(3)}R`}
async function runBlock(b:Block):Promise<Result>{const r=await fetch(`${ALPHAPILOT_API_BASE}/v1/research/setup-discovery-v2`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({symbols:SYMBOLS,start_date:b.start,end_date:b.end})});if(!r.ok){let d='';try{const x=await r.json();d=x?.detail?`: ${x.detail}`:''}catch{}throw new Error(`${b.id} API ${r.status}${d}`)}return r.json()}
export function ExecutionStructureDiscoveryV1(){const[running,setRunning]=useState(false),[progress,setProgress]=useState(''),[results,setResults]=useState<Record<string,Result>>({}),[error,setError]=useState<string|null>(null);
 const replicated=useMemo(()=>{const map=new Map<string,{setup:string;direction:string;method:string;blocks:string[];signals:number;fills:number;weightedDelta:number}>();for(const b of BLOCKS){const r=results[b.id];if(!r?.execution_structure_v1)continue;for(const row of r.execution_structure_v1.rows){if(row.state!=='IMPROVED')continue;const key=`${row.setup_type}|${row.direction}|${row.method}`;const cur=map.get(key)||{setup:row.setup_type,direction:row.direction,method:row.method,blocks:[],signals:0,fills:0,weightedDelta:0};cur.blocks.push(b.id);cur.signals+=row.signals;cur.fills+=row.fills;cur.weightedDelta+=(row.delta_vs_next_open||0)*row.signals;map.set(key,cur)}}return[...map.values()].filter(x=>x.blocks.length>=3).map(x=>({...x,delta:x.signals?x.weightedDelta/x.signals:0})).sort((a,b)=>b.blocks.length-a.blocks.length||b.delta-a.delta)},[results]);
 async function run(){setRunning(true);setError(null);setResults({});try{for(const b of BLOCKS){setProgress(`Running ${b.id} · ${b.start} → ${b.end}`);const r=await runBlock(b);if(!r.execution_structure_v1)throw new Error(`${b.id}: backend has not deployed Execution Structure v1 payload yet`);setResults(x=>({...x,[b.id]:r}));await new Promise(res=>setTimeout(res,800))}}catch(e){setError(e instanceof Error?e.message:'Execution Structure v1 failed.')}finally{setProgress('');setRunning(false)}}
 const completed=Object.keys(results).length,improved=Object.values(results).reduce((s,r)=>s+r.execution_structure_v1.rows.filter(x=>x.state==='IMPROVED').length,0),errors=Object.values(results).reduce((s,r)=>s+r.errors.length,0);
 return <Card><CardHeader title="Execution-Structure Discovery v1 — Entry Method Replication" subtitle="Tests whether entry mechanics improve the same frozen Setup Discovery v2 signals. Production execution remains unchanged." action={<GitCompareArrows size={18} className="text-violet-500"/>}/><CardBody className="space-y-4">
  <div className="flex gap-2 flex-wrap"><Badge variant="blue">EXECUTION STRUCTURE v1</Badge><Badge variant="default">SAME SIGNAL TIMESTAMPS</Badge><Badge variant="default">NEXT OPEN CONTROL</Badge><Badge variant="default">BREAK CONFIRMATION</Badge><Badge variant="default">PULLBACK ENTRY</Badge><Badge variant="default">6 FIXED BLOCKS</Badge><Badge variant="default">NO RETUNING</Badge><Badge variant="default">RESEARCH ONLY</Badge><Badge variant="default">PRODUCTION UNCHANGED</Badge></div>
  <div className="flex items-center justify-between gap-4"><p className="text-xs text-slate-500">Control is the existing next-5m-open entry. BREAK_CONFIRMATION waits up to 3 bars for a 0.05 ATR break beyond the signal candle. PULLBACK_ENTRY waits up to 3 bars for a 0.25 ATR retracement from signal close. Original structural stops and fixed 1R target remain unchanged. Alternatives are IMPROVED only with ≥12 signals, ≥50% fill rate, ≥+0.10R per-signal lift versus NEXT_OPEN, ≥55% filled win rate and PF ≥1.20. Exact setup + direction + method must improve in ≥3 blocks.</p><Button variant="primary" onClick={run} disabled={running}><Play size={14} className="inline mr-1"/>{running?'Running Execution Structure v1…':'Run Execution Structure v1'}</Button></div>
  {progress&&<div className="rounded-lg border p-3 text-xs">{progress}</div>}{error&&<div className="rounded-lg border border-red-200 p-3 text-sm text-red-600">{error}</div>}
  <div className="overflow-x-auto rounded-lg border"><table className="w-full text-xs"><thead><tr><th className="p-2 text-left">Block</th><th>Dates</th><th>Improved rows</th><th>Errors</th><th>Status</th></tr></thead><tbody>{BLOCKS.map(b=>{const r=results[b.id];return <tr className="border-t" key={b.id}><td className="p-2 font-semibold">{b.id}</td><td className="text-center">{b.start} → {b.end}</td><td className="text-center">{r?r.execution_structure_v1.rows.filter(x=>x.state==='IMPROVED').length:'—'}</td><td className="text-center">{r?.errors.length??'—'}</td><td className="text-center"><Badge variant={r?'green':'default'}>{r?'COMPLETE':'PENDING'}</Badge></td></tr>})}</tbody></table></div>
  {completed>0&&<div className="grid grid-cols-2 md:grid-cols-5 gap-3"><Stat label="Completed blocks" value={`${completed}/6`}/><Stat label="Improved block rows" value={String(improved)}/><Stat label="Data errors" value={String(errors)}/><Stat label="Replicated methods" value={String(replicated.length)}/><div className="rounded-lg border p-3"><p className="text-xs text-slate-500">Decision</p><Badge variant={completed<6?'default':replicated.length?'blue':'default'}>{completed<6?'INCOMPLETE':replicated.length?'REPLICATED_EXECUTION_CANDIDATE':'NO_REPLICATED_EXECUTION_EDGE'}</Badge></div></div>}
  {replicated.length>0&&<div><p className="text-sm font-semibold mb-2">Replicated execution candidates</p><div className="overflow-x-auto rounded-lg border"><table className="w-full text-xs"><thead><tr><th className="p-2 text-left">Setup</th><th>Dir</th><th>Method</th><th>Blocks</th><th>Signals</th><th>Fills</th><th>Weighted Δ / signal</th></tr></thead><tbody>{replicated.map((x,i)=><tr key={i} className="border-t"><td className="p-2 font-medium">{x.setup}</td><td className="text-center">{x.direction}</td><td className="text-center">{x.method}</td><td className="text-center">{x.blocks.join(', ')}</td><td className="text-center">{x.signals}</td><td className="text-center">{x.fills}</td><td className="text-center font-semibold">{fmtR(x.delta)}</td></tr>)}</tbody></table></div></div>}
  {completed>0&&<div className="space-y-3"><p className="text-sm font-semibold">Improved block rows</p>{BLOCKS.map(b=>{const r=results[b.id];if(!r)return null;const rows=r.execution_structure_v1.rows.filter(x=>x.state==='IMPROVED');return <div key={b.id}><p className="text-xs font-semibold mb-1">{b.id}</p>{rows.length===0?<p className="text-xs text-slate-500">No frozen alternative entry met the improvement gate.</p>:<div className="overflow-x-auto rounded-lg border"><table className="w-full text-xs"><thead><tr><th className="p-2 text-left">Setup</th><th>Dir</th><th>Method</th><th>Signals</th><th>Fill</th><th>Win</th><th>Avg R / signal</th><th>Δ vs open</th><th>PF</th></tr></thead><tbody>{rows.map((x,i)=><tr key={i} className="border-t"><td className="p-2 font-medium">{x.setup_type}</td><td className="text-center">{x.direction}</td><td className="text-center">{x.method}</td><td className="text-center">{x.signals}</td><td className="text-center">{x.fill_rate.toFixed(1)}%</td><td className="text-center">{x.win_rate.toFixed(1)}%</td><td className="text-center">{fmtR(x.average_r_per_signal)}</td><td className="text-center font-semibold">{fmtR(x.delta_vs_next_open)}</td><td className="text-center">{x.profit_factor.toFixed(2)}</td></tr>)}</tbody></table></div>}</div>})}</div>}
  <p className="text-[11px] text-slate-500">Unfilled alternative entries contribute 0R to per-signal expectancy, so lower participation cannot artificially inflate the result. A replicated method remains research-only and must pass untouched OOS before any execution-rule consideration.</p>
 </CardBody></Card>}
function Stat({label,value}:{label:string;value:string}){return <div className="rounded-lg border p-3"><p className="text-xs text-slate-500">{label}</p><p className="text-lg font-bold">{value}</p></div>}
