import { useState } from 'react';
import { Database, Play } from 'lucide-react';
import { Badge, Button, Card, CardBody, CardHeader, Input } from '@/components/ui';
import { probeHistoricalFnoOption, type FnoHistoryProbeResponse } from '@/lib/alphaPilotApi';

function offset(days:number){const d=new Date();d.setDate(d.getDate()-days);return d.toISOString().slice(0,10)}
export function FnoHistoryProbe(){
 const[symbol,setSymbol]=useState('RELIANCE'),[expiry,setExpiry]=useState(''),[strike,setStrike]=useState(''),[type,setType]=useState<'CE'|'PE'>('CE'),[start,setStart]=useState(offset(7)),[end,setEnd]=useState(offset(1)),[running,setRunning]=useState(false),[error,setError]=useState<string|null>(null),[result,setResult]=useState<FnoHistoryProbeResponse|null>(null);
 async function run(){const n=Number(strike);if(!symbol.trim()||!expiry||!Number.isFinite(n)||n<=0){setError('Enter symbol, exact expiry and a positive strike.');return}setRunning(true);setError(null);setResult(null);try{setResult(await probeHistoricalFnoOption({symbol,expiry,strike:n,option_type:type,start_date:start,end_date:end,interval:'5m'}))}catch(e){setError(e instanceof Error?e.message:'Historical option probe failed.')}finally{setRunning(false)}}
 const count=Number(result?.candle_count??0),possible=result?.capability==='TRUE_OPTION_PREMIUM_REPLAY_POSSIBLE'||count>0;
 return <Card><CardHeader title="Historical F&O Data Probe" subtitle="Tests whether Groww can return real 5-minute premium candles for an exact NSE option contract." action={<Database size={18} className="text-blue-500"/>}/><CardBody className="space-y-4">
  <div className="grid grid-cols-2 md:grid-cols-6 gap-2"><Input value={symbol} onChange={e=>setSymbol(e.target.value.toUpperCase())} placeholder="RELIANCE"/><Input type="date" value={expiry} onChange={e=>setExpiry(e.target.value)}/><Input value={strike} onChange={e=>setStrike(e.target.value)} placeholder="Strike e.g. 1400"/><select className="rounded-md border border-slate-200 dark:border-slate-700 bg-transparent px-3 text-sm" value={type} onChange={e=>setType(e.target.value as 'CE'|'PE')}><option>CE</option><option>PE</option></select><Input type="date" value={start} onChange={e=>setStart(e.target.value)}/><Input type="date" value={end} onChange={e=>setEnd(e.target.value)}/></div>
  <Button onClick={run} disabled={running}><Play size={14} className="inline mr-1"/>{running?'Testing Groww…':'Run Option History Probe'}</Button>
  {error&&<div className="rounded-lg border border-red-200 p-3 text-sm text-red-600">{error}</div>}
  {result&&<div className="rounded-lg border border-slate-200 dark:border-slate-800 p-4 space-y-3"><div className="flex flex-wrap justify-between gap-2"><div><p className="font-semibold">Capability result</p><p className="text-xs text-slate-500 mt-1">{result.message??'Groww historical option response received.'}</p></div><Badge variant={possible?'green':'amber'}>{possible?'PREMIUM REPLAY POSSIBLE':'NOT YET CONFIRMED'}</Badge></div><div className="grid grid-cols-2 md:grid-cols-4 gap-3 text-sm"><Metric l="Candles" v={String(count)}/><Metric l="Capability" v={String(result.capability??result.status??'UNKNOWN')}/><Metric l="Contract" v={String(result.contract?.trading_symbol??result.contract?.groww_symbol??'—')}/><Metric l="Exchange token" v={String(result.contract?.exchange_token??'—')}/></div>{Array.isArray(result.sample)&&result.sample.length>0&&<div><p className="text-xs font-semibold mb-1">Returned candle sample</p><pre className="text-[10px] overflow-auto rounded bg-slate-50 dark:bg-slate-900 p-2 max-h-40">{JSON.stringify(result.sample,null,2)}</pre></div>}</div>}
  <p className="text-xs text-slate-500">Use an exact contract from a known F&O setup. A positive result lets us build true option-premium SL/T1/T2 replay. A failed contract lookup alone does not prove Groww lacks historical option data.</p>
 </CardBody></Card>
}
function Metric({l,v}:{l:string;v:string}){return <div><p className="text-xs text-slate-500">{l}</p><p className="font-semibold mt-1 break-all">{v}</p></div>}
