import { useMemo, useState } from 'react';
import { Database, Play, RotateCcw } from 'lucide-react';
import { Badge, Button, Card, CardBody, CardHeader, Input } from '@/components/ui';
import { probeHistoricalFnoOption, replayHistoricalFnoOption, type FnoHistoryProbeResponse, type FnoPremiumReplayResponse } from '@/lib/alphaPilotApi';
import { readValidationRecords, type ValidationRecord } from '@/lib/liveValidation';

function offset(days:number){const d=new Date();d.setDate(d.getDate()-days);return d.toISOString().slice(0,10)}
function dateOnly(v?:string){if(!v)return'';const d=new Date(v);return Number.isNaN(d.getTime())?String(v).slice(0,10):d.toISOString().slice(0,10)}
function timeOnlyIST(v?:string){if(!v)return'09:30';const d=new Date(v);if(Number.isNaN(d.getTime()))return'09:30';const parts=new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Kolkata',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(d);return `${parts.find(x=>x.type==='hour')?.value??'09'}:${parts.find(x=>x.type==='minute')?.value??'30'}`}
function usableRecord(r:ValidationRecord){return Boolean(r.symbol&&r.expiry&&Number.isFinite(r.strike)&&r.option_type)}

export function FnoHistoryProbe(){
 const saved=useMemo(()=>readValidationRecords().filter(usableRecord).sort((a,b)=>new Date(b.captured_at).getTime()-new Date(a.captured_at).getTime()).slice(0,12),[]);
 const latest=saved[0];
 const[symbol,setSymbol]=useState(latest?.symbol??'RELIANCE'),[expiry,setExpiry]=useState(latest?.expiry??''),[strike,setStrike]=useState(latest?.strike!=null?String(latest.strike):''),[type,setType]=useState<'CE'|'PE'>(latest?.option_type??'CE'),[start,setStart]=useState(latest?dateOnly(latest.captured_at):offset(7)),[end,setEnd]=useState(latest?dateOnly(latest.resolved_at??new Date().toISOString()):offset(1)),[entryTime,setEntryTime]=useState(timeOnlyIST(latest?.captured_at)),[running,setRunning]=useState(false),[replaying,setReplaying]=useState(false),[error,setError]=useState<string|null>(null),[result,setResult]=useState<FnoHistoryProbeResponse|null>(null),[replay,setReplay]=useState<FnoPremiumReplayResponse|null>(null),[selectedId,setSelectedId]=useState(latest?.id??'');
 function applyRecord(r:ValidationRecord){setSelectedId(r.id);setSymbol(r.symbol);setExpiry(r.expiry??'');setStrike(r.strike!=null?String(r.strike):'');setType(r.option_type??'CE');const captured=dateOnly(r.captured_at);setStart(captured);setEntryTime(timeOnlyIST(r.captured_at));const resolved=dateOnly(r.resolved_at);setEnd(resolved||dateOnly(new Date().toISOString()));setResult(null);setReplay(null);setError(null)}
 async function run(){const n=Number(strike);if(!symbol.trim()||!expiry||!Number.isFinite(n)||n<=0){setError('Enter symbol, exact expiry and a positive strike.');return}if(!start||!end||end<start){setError('Choose a valid start/end date range.');return}setRunning(true);setError(null);setResult(null);setReplay(null);try{setResult(await probeHistoricalFnoOption({symbol,expiry,strike:n,option_type:type,start_date:start,end_date:end,interval:'5minute'}))}catch(e){setError(e instanceof Error?e.message:'Historical option probe failed.')}finally{setRunning(false)}}
 async function runReplay(){const n=Number(strike);if(!Number.isFinite(n)||!start||!entryTime)return;setReplaying(true);setError(null);setReplay(null);try{setReplay(await replayHistoricalFnoOption({symbol,expiry,strike:n,option_type:type,trade_date:start,entry_time:entryTime,min_risk_reward:1.5}))}catch(e){setError(e instanceof Error?e.message:'Historical premium replay failed.')}finally{setReplaying(false)}}
 const count=Number(result?.candle_count??0),possible=result?.capability==='TRUE_OPTION_PREMIUM_REPLAY_POSSIBLE'||result?.backtest_implication==='TRUE_OPTION_PREMIUM_REPLAY_POSSIBLE'||result?.supported===true||count>0;
 return <Card><CardHeader title="Historical F&O Data Probe" subtitle="Tests Groww premium history, then replays the exact option plan on real 5-minute OHLC." action={<Database size={18} className="text-blue-500"/>}/><CardBody className="space-y-4">
  {saved.length>0&&<div className="rounded-lg border border-slate-200 dark:border-slate-800 p-3"><div className="flex flex-col md:flex-row md:items-end gap-3"><label className="text-xs font-medium flex-1">Use a saved Live Validation contract<select className="block mt-1 w-full rounded-md border border-slate-200 dark:border-slate-700 bg-transparent px-3 py-2 text-sm" value={selectedId} onChange={e=>{const r=saved.find(x=>x.id===e.target.value);if(r)applyRecord(r)}}>{saved.map(r=><option key={r.id} value={r.id}>{r.symbol} · {r.expiry} · {r.strike} {r.option_type} · {new Date(r.captured_at).toLocaleDateString('en-IN')}</option>)}</select></label><Button variant="ghost" onClick={()=>latest&&applyRecord(latest)} disabled={!latest}><RotateCcw size={14} className="inline mr-1"/>Latest contract</Button></div><p className="text-[11px] text-slate-500 mt-2">Loads the exact contract and captured signal time from Live Validation.</p></div>}
  <div className="grid grid-cols-2 md:grid-cols-7 gap-2"><Input value={symbol} onChange={value=>setSymbol(value.toUpperCase())} placeholder="RELIANCE"/><Input type="date" value={expiry} onChange={setExpiry}/><Input value={strike} onChange={setStrike} placeholder="Strike"/><select className="rounded-md border border-slate-200 dark:border-slate-700 bg-transparent px-3 text-sm" value={type} onChange={e=>setType(e.target.value as 'CE'|'PE')}><option>CE</option><option>PE</option></select><Input type="date" value={start} onChange={setStart}/><Input type="time" value={entryTime} onChange={setEntryTime}/><Input type="date" value={end} onChange={setEnd}/></div>
  <div className="flex flex-wrap gap-2"><Button onClick={run} disabled={running||replaying}><Play size={14} className="inline mr-1"/>{running?'Testing Groww…':'Run Option History Probe'}</Button>{possible&&<Button variant="primary" onClick={runReplay} disabled={running||replaying}><Play size={14} className="inline mr-1"/>{replaying?'Replaying premium…':'Replay True Premium Trade'}</Button>}</div>
  {error&&<div className="rounded-lg border border-red-200 p-3 text-sm text-red-600">{error}</div>}
  {result&&<div className="rounded-lg border border-slate-200 dark:border-slate-800 p-4 space-y-3"><div className="flex flex-wrap justify-between gap-2"><div><p className="font-semibold">Capability result</p><p className="text-xs text-slate-500 mt-1">{result.reason??result.message??'Groww historical option response received.'}</p></div><Badge variant={possible?'green':'amber'}>{possible?'PREMIUM REPLAY POSSIBLE':'NOT YET CONFIRMED'}</Badge></div><div className="grid grid-cols-2 md:grid-cols-4 gap-3 text-sm"><Metric l="Candles" v={String(count)}/><Metric l="Capability" v={String(result.backtest_implication??result.capability??result.status??'UNKNOWN')}/><Metric l="Contract" v={String(result.contract?.trading_symbol??result.contract?.groww_symbol??'—')}/><Metric l="Lot size" v={String(result.contract?.lot_size??'—')}/></div></div>}
  {replay&&<div className="rounded-lg border border-slate-200 dark:border-slate-800 p-4 space-y-3"><div className="flex justify-between gap-2"><div><p className="font-semibold">True option-premium replay</p><p className="text-xs text-slate-500 mt-1">Actual Groww 5-minute OHLC · entry on next 5m open after the saved signal time.</p></div><Badge variant={replay.status==='REPLAY_COMPLETE'?(Number(replay.r_multiple)>=0?'green':'red'):replay.status==='AMBIGUOUS'?'amber':'default'}>{replay.outcome??replay.status}</Badge></div><div className="grid grid-cols-2 md:grid-cols-6 gap-3"><Metric l="Entry" v={money(replay.option_entry)}/><Metric l="Stop" v={money(replay.option_stop)}/><Metric l="T1" v={money(replay.option_target1)}/><Metric l="T2" v={money(replay.option_target2)}/><Metric l="Result" v={replay.r_multiple==null?'—':`${replay.r_multiple>0?'+':''}${replay.r_multiple.toFixed(2)}R`}/><Metric l="MFE / MAE" v={`${replay.mfe_r?.toFixed(2)??'—'}R / ${replay.mae_r?.toFixed(2)??'—'}R`}/></div>{replay.ambiguity_reason&&<p className="text-xs text-amber-600">{replay.ambiguity_reason}</p>}</div>}
  <p className="text-xs text-slate-500">A positive probe now unlocks real premium replay. Same-candle stop/target conflicts are marked ambiguous rather than guessed.</p>
 </CardBody></Card>
}
function Metric({l,v}:{l:string;v:string}){return <div><p className="text-xs text-slate-500">{l}</p><p className="font-semibold mt-1 break-all">{v}</p></div>}
function money(v?:number){return Number.isFinite(v)?`₹${Number(v).toFixed(2)}`:'—'}
