import { useEffect, useMemo, useState } from 'react';
import { Badge, Card, CardBody, CardHeader } from '@/components/ui';
import type { ValidationRecord } from '@/lib/liveValidation';

type Props={records:ValidationRecord[]}; type Kind='HALF_EXIT'|'HALF_PARTIAL'|'BE_HALF'|'BE_ONE';
type Scenario={name:string;samples:number;avgR:number;netR:number;deltaR:number;improved:number;worsened:number;unchanged:number}; type Segment={label:string;rows:ValidationRecord[]};
type Frozen={name:string;kind:Kind;frozen_at:string;development_samples:number;development_delta_r:number};
const FREEZE_KEY='alphapilot.fno-management-candidate.v1';
function realisedR(r:ValidationRecord){const e=Number(r.option_entry),s=Number(r.option_stop),t=Number(r.option_target1),risk=e-s;if(![e,s,t,risk].every(Number.isFinite)||risk<=0)return null;if(r.status==='STOP_HIT')return-1;if(r.status==='TARGET1_HIT'||r.status==='TARGET2_HIT')return(t-e)/risk;return null}
function scenarioR(r:ValidationRecord,k:Kind){const b=realisedR(r),m=Number(r.mfe_r);if(b==null||!Number.isFinite(m))return null;if(k==='HALF_EXIT')return m>=.5?.5:b;if(k==='HALF_PARTIAL')return m>=.5?.25+.5*b:b;if(k==='BE_HALF')return b<0&&m>=.5?0:b;if(k==='BE_ONE')return b<0&&m>=1?0:b;return b}
function summarize(name:string,rows:ValidationRecord[],k?:Kind):Scenario{const p=rows.map(r=>{const b=realisedR(r),v=k?scenarioR(r,k):b;return b==null||v==null?null:{b,v,d:v-b}}).filter((x):x is {b:number;v:number;d:number}=>!!x),v=p.map(x=>x.v),d=p.map(x=>x.d),e=1e-9;return{name,samples:v.length,avgR:v.length?v.reduce((a,b)=>a+b,0)/v.length:0,netR:v.reduce((a,b)=>a+b,0),deltaR:d.length?d.reduce((a,b)=>a+b,0)/d.length:0,improved:d.filter(x=>x>e).length,worsened:d.filter(x=>x<-e).length,unchanged:d.filter(x=>Math.abs(x)<=e).length}}
function evidence(s:Scenario){if(s.samples>=20&&s.deltaR>=.10&&s.improved>s.worsened)return'REVIEW CANDIDATE';if(s.samples>=5&&s.deltaR>=.05&&s.improved>s.worsened)return'EARLY CANDIDATE';return'NO CONCLUSION'}
function hourIST(v:string){const d=new Date(v);if(Number.isNaN(d.getTime()))return null;const p=new Intl.DateTimeFormat('en-US',{timeZone:'Asia/Kolkata',hour:'2-digit',hourCycle:'h23'}).formatToParts(d);return Number(p.find(x=>x.type==='hour')?.value)}
function dte(r:ValidationRecord){if(!r.expiry)return null;const x=new Date(`${String(r.expiry).slice(0,10)}T15:30:00+05:30`),c=new Date(r.captured_at);if(Number.isNaN(x.getTime())||Number.isNaN(c.getTime()))return null;return Math.max(0,Math.ceil((x.getTime()-c.getTime())/86400000))}
const defs:[string,Kind][]=[['Full Exit at +0.50R','HALF_EXIT'],['50% at +0.50R, Rest Frozen','HALF_PARTIAL'],['BE after observed +0.50R','BE_HALF'],['BE after observed +1.00R','BE_ONE']];
function stability(name:string,k:Kind,segs:Segment[]){const a=segs.map(g=>summarize(name,g.rows,k)).filter(s=>s.samples>=5);if(a.length<2)return{label:'INSUFFICIENT',variant:'default' as const,reason:`Only ${a.length} major subgroup${a.length===1?' has':'s have'} ≥5 matched trades.`};const neg=a.filter(s=>s.deltaR<-.05),pos=a.filter(s=>s.deltaR>=.05);if(neg.length)return{label:'MIXED',variant:'amber' as const,reason:`${neg.length} evidence-bearing subgroup${neg.length===1?' is':'s are'} materially negative.`};if(pos.length>=Math.ceil(a.length/2))return{label:'STABLE',variant:'green' as const,reason:`No evidence-bearing subgroup is materially negative; ${pos.length}/${a.length} are ≥ +0.05R.`};return{label:'MIXED',variant:'amber' as const,reason:`Positive improvement is not broad enough yet (${pos.length}/${a.length}).`}}
function readFreeze():Frozen|null{try{const x=JSON.parse(localStorage.getItem(FREEZE_KEY)||'null');return x&&x.kind&&x.frozen_at?x:null}catch{return null}}
export function FnoManagementSimulation({records}:Props){const[freeze,setFreeze]=useState<Frozen|null>(()=>typeof window==='undefined'?null:readFreeze());const resolved=useMemo(()=>records.filter(r=>['STOP_HIT','TARGET1_HIT','TARGET2_HIT'].includes(r.status)),[records]);const scenarios=useMemo(()=>[summarize('Frozen Plan',resolved),...defs.map(([n,k])=>summarize(n,resolved,k))],[resolved]);const segments=useMemo<Segment[]>(()=>[{label:'BUY CE',rows:resolved.filter(r=>r.action==='BUY CE'||r.option_type==='CE')},{label:'BUY PE',rows:resolved.filter(r=>r.action==='BUY PE'||r.option_type==='PE')},{label:'09:15–10:59',rows:resolved.filter(r=>{const h=hourIST(r.captured_at);return h!=null&&h>=9&&h<11})},{label:'11:00–12:59',rows:resolved.filter(r=>{const h=hourIST(r.captured_at);return h!=null&&h>=11&&h<13})},{label:'13:00–14:29',rows:resolved.filter(r=>{const h=hourIST(r.captured_at);return h!=null&&h>=13&&h<15})},{label:'14:30–15:30',rows:resolved.filter(r=>hourIST(r.captured_at)!==null&&Number(hourIST(r.captured_at))>=14)},{label:'0 DTE',rows:resolved.filter(r=>dte(r)===0)},{label:'1 DTE',rows:resolved.filter(r=>dte(r)===1)},{label:'2–3 DTE',rows:resolved.filter(r=>{const x=dte(r);return x!=null&&x>=2&&x<=3})},{label:'4+ DTE',rows:resolved.filter(r=>{const x=dte(r);return x!=null&&x>=4})}],[resolved]);
const candidates=useMemo(()=>defs.map(([n,k])=>{const s=scenarios.find(x=>x.name===n)!;return{name:n,kind:k,s,st:stability(n,k,segments)}}),[scenarios,segments]);
useEffect(()=>{if(freeze||typeof window==='undefined')return;const c=candidates.find(x=>evidence(x.s)==='REVIEW CANDIDATE'&&x.st.label==='STABLE');if(!c)return;const f:Frozen={name:c.name,kind:c.kind,frozen_at:new Date().toISOString(),development_samples:c.s.samples,development_delta_r:c.s.deltaR};localStorage.setItem(FREEZE_KEY,JSON.stringify(f));setFreeze(f)},[freeze,candidates]);
const forward=useMemo(()=>{if(!freeze)return null;const rows=resolved.filter(r=>new Date(r.captured_at).getTime()>new Date(freeze.frozen_at).getTime()),s=summarize(freeze.name,rows,freeze.kind);const validated=s.samples>=10&&s.deltaR>=.05&&s.improved>s.worsened;return{rows,s,validated}},[freeze,resolved]);const usable=scenarios[0]?.samples??0;
return <Card><CardHeader title="F&O Management Simulation" subtitle="Analytics-only management study with subgroup stability and out-of-sample validation." action={<Badge variant={usable>=30?'green':usable>=10?'blue':'default'}>{usable>=30?'USABLE SAMPLE':usable>=10?'EARLY SIGNAL':'INSUFFICIENT SAMPLE'}</Badge>}/><CardBody className="space-y-4"><div className="grid grid-cols-1 md:grid-cols-5 gap-2">{scenarios.map((s,i)=><div key={s.name} className="rounded-lg border border-slate-200 dark:border-slate-800 p-3"><div className="flex justify-between gap-2"><b className="text-xs">{s.name}</b>{i>0&&<Badge variant={s.deltaR>0?'green':s.deltaR<0?'red':'default'}>{s.deltaR>=0?'+':''}{s.deltaR.toFixed(2)}R</Badge>}</div><p className="text-lg font-bold mt-1">{s.avgR.toFixed(2)}R</p><p className="text-[11px] text-slate-500">Net {s.netR.toFixed(2)}R · {s.samples} matched</p>{i>0&&<p className="text-[11px] text-slate-500">{s.improved} improved · {s.worsened} worsened · {evidence(s)}</p>}</div>)}</div>
<div className="rounded-lg border border-slate-200 dark:border-slate-800 p-3"><p className="text-sm font-semibold">Subgroup stability gate</p><div className="grid grid-cols-1 md:grid-cols-2 gap-2 mt-3">{candidates.map(c=>{const ev=evidence(c.s),effective=ev==='REVIEW CANDIDATE'&&c.st.label!=='STABLE'?'EARLY CANDIDATE':ev;return <div key={c.name} className="rounded-lg bg-slate-50 dark:bg-slate-800 p-3"><div className="flex flex-wrap justify-between gap-2"><b className="text-xs">{c.name}</b><div className="flex gap-1"><Badge variant={effective==='REVIEW CANDIDATE'?'green':effective==='EARLY CANDIDATE'?'blue':'default'}>{effective}</Badge><Badge variant={c.st.variant}>{c.st.label}</Badge></div></div><p className="text-[11px] text-slate-500 mt-2">{c.st.reason}</p></div>})}</div></div>
<div className="rounded-lg border border-slate-200 dark:border-slate-800 p-3"><div className="flex flex-wrap justify-between gap-2"><div><p className="text-sm font-semibold">Out-of-sample forward validation</p><p className="text-xs text-slate-500 mt-1">A REVIEW + STABLE rule is frozen once. Only setups captured after that timestamp can validate it.</p></div><Badge variant={forward?.validated?'green':freeze?'blue':'default'}>{forward?.validated?'FORWARD VALIDATED':freeze?'FORWARD TESTING':'WAITING FOR CANDIDATE'}</Badge></div>{freeze?<div className="grid grid-cols-2 md:grid-cols-5 gap-3 mt-3 text-xs"><Metric l="Frozen rule" v={freeze.name}/><Metric l="Frozen at" v={new Date(freeze.frozen_at).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'})}/><Metric l="Forward matched" v={String(forward?.s.samples??0)}/><Metric l="Forward ΔR" v={`${(forward?.s.deltaR??0)>=0?'+':''}${(forward?.s.deltaR??0).toFixed(2)}R`}/><Metric l="Improved / worsened" v={`${forward?.s.improved??0} / ${forward?.s.worsened??0}`}/></div>:<p className="text-xs text-slate-500 mt-3">No rule has yet passed both the development evidence and stability gates.</p>}<p className="text-[11px] text-slate-500 mt-3">FORWARD VALIDATED requires ≥10 new matched trades, ≥+0.05R average improvement and more improved than worsened. It still does not auto-deploy.</p></div>
<div className="grid grid-cols-1 lg:grid-cols-2 gap-3">{segments.map(seg=><div key={seg.label} className="rounded-lg border border-slate-200 dark:border-slate-800 p-3"><div className="flex justify-between"><b className="text-sm">{seg.label}</b><Badge variant={seg.rows.length>=20?'green':seg.rows.length>=5?'blue':'default'}>{seg.rows.length} trades</Badge></div><div className="mt-2 space-y-1">{defs.map(([n,k])=>{const x=summarize(n,seg.rows,k);return <div key={n} className="grid grid-cols-[1fr_auto] text-[11px] gap-2"><span className="truncate">{n}</span><b>{x.deltaR>=0?'+':''}{x.deltaR.toFixed(2)}R</b></div>})}</div></div>)}</div>
<div className="rounded-lg border border-slate-200 dark:border-slate-800 p-3 text-xs text-slate-500"><b>Observation limitation:</b> option MFE is polling-based rather than tick-perfect. Counterfactual management results therefore remain research evidence. No option entry, premium SL, target, Alpha threshold or execution gate is changed.</div></CardBody></Card>}
function Metric({l,v}:{l:string;v:string}){return <div><p className="text-slate-500">{l}</p><p className="font-semibold mt-1">{v}</p></div>}
