import { useMemo } from 'react';
import { Badge, Card, CardBody, CardHeader } from '@/components/ui';
import type { ValidationRecord } from '@/lib/liveValidation';

type Props = { records: ValidationRecord[] };
type Kind='HALF_EXIT'|'HALF_PARTIAL'|'BE_HALF'|'BE_ONE';
type Scenario = { name: string; samples: number; avgR: number; netR: number; deltaR: number; improved: number; worsened: number; unchanged: number };
type Segment={label:string;rows:ValidationRecord[]};
function realisedR(r: ValidationRecord) {const e=Number(r.option_entry),s=Number(r.option_stop),t=Number(r.option_target1),risk=e-s;if(![e,s,t,risk].every(Number.isFinite)||risk<=0)return null;if(r.status==='STOP_HIT')return -1;if(r.status==='TARGET1_HIT'||r.status==='TARGET2_HIT')return(t-e)/risk;return null}
function scenarioR(r:ValidationRecord,kind:Kind){const base=realisedR(r),mfe=Number(r.mfe_r);if(base==null||!Number.isFinite(mfe))return null;if(kind==='HALF_EXIT')return mfe>=.5?.5:base;if(kind==='HALF_PARTIAL')return mfe>=.5?.25+.5*base:base;if(kind==='BE_HALF')return base<0&&mfe>=.5?0:base;if(kind==='BE_ONE')return base<0&&mfe>=1?0:base;return base}
function summarize(name:string,rows:ValidationRecord[],kind?:Kind):Scenario{const pairs=rows.map(r=>{const b=realisedR(r),v=kind?scenarioR(r,kind):b;return b==null||v==null?null:{b,v,d:v-b}}).filter((x):x is {b:number;v:number;d:number}=>Boolean(x)),vals=pairs.map(x=>x.v),ds=pairs.map(x=>x.d),eps=1e-9;return{name,samples:vals.length,avgR:vals.length?vals.reduce((a,b)=>a+b,0)/vals.length:0,netR:vals.reduce((a,b)=>a+b,0),deltaR:ds.length?ds.reduce((a,b)=>a+b,0)/ds.length:0,improved:ds.filter(x=>x>eps).length,worsened:ds.filter(x=>x<-eps).length,unchanged:ds.filter(x=>Math.abs(x)<=eps).length}}
function evidence(s:Scenario){if(s.samples>=20&&s.deltaR>=.10&&s.improved>s.worsened)return{label:'REVIEW CANDIDATE',variant:'green' as const};if(s.samples>=5&&s.deltaR>=.05&&s.improved>s.worsened)return{label:'EARLY CANDIDATE',variant:'blue' as const};return{label:'NO CONCLUSION',variant:'default' as const}}
function hourIST(v:string){const d=new Date(v);if(Number.isNaN(d.getTime()))return null;const p=new Intl.DateTimeFormat('en-US',{timeZone:'Asia/Kolkata',hour:'2-digit',hourCycle:'h23'}).formatToParts(d);const h=Number(p.find(x=>x.type==='hour')?.value);return Number.isFinite(h)?h:null}
function dte(r:ValidationRecord){if(!r.expiry)return null;const x=new Date(`${String(r.expiry).slice(0,10)}T15:30:00+05:30`),c=new Date(r.captured_at);if(Number.isNaN(x.getTime())||Number.isNaN(c.getTime()))return null;return Math.max(0,Math.ceil((x.getTime()-c.getTime())/86400000))}
const scenarioDefs:[string,Kind][]=[['Full Exit at +0.50R','HALF_EXIT'],['50% at +0.50R, Rest Frozen','HALF_PARTIAL'],['BE after observed +0.50R','BE_HALF'],['BE after observed +1.00R','BE_ONE']];
function stability(name:string,kind:Kind,segments:Segment[]){const stats=segments.map(g=>summarize(name,g.rows,kind)).filter(s=>s.samples>=5);if(stats.length<2)return{label:'INSUFFICIENT',variant:'default' as const,reason:`Only ${stats.length} major subgroup${stats.length===1?' has':'s have'} ≥5 matched trades.`};const neg=stats.filter(s=>s.deltaR<-.05),pos=stats.filter(s=>s.deltaR>=.05);if(neg.length)return{label:'MIXED',variant:'amber' as const,reason:`${neg.length} evidence-bearing subgroup${neg.length===1?' is':'s are'} materially negative (< -0.05R).`};if(pos.length>=Math.ceil(stats.length/2))return{label:'STABLE',variant:'green' as const,reason:`No evidence-bearing subgroup is materially negative; ${pos.length}/${stats.length} are ≥ +0.05R.`};return{label:'MIXED',variant:'amber' as const,reason:`Positive improvement is not broad enough yet (${pos.length}/${stats.length} ≥ +0.05R).`}}
export function FnoManagementSimulation({records}:Props){const resolved=useMemo(()=>records.filter(r=>r.status==='STOP_HIT'||r.status==='TARGET1_HIT'||r.status==='TARGET2_HIT'),[records]);const scenarios=useMemo(()=>[summarize('Frozen Plan',resolved),...scenarioDefs.map(([n,k])=>summarize(n,resolved,k))],[resolved]);const segments=useMemo<Segment[]>(()=>[
{label:'BUY CE',rows:resolved.filter(r=>r.action==='BUY CE'||r.option_type==='CE')},{label:'BUY PE',rows:resolved.filter(r=>r.action==='BUY PE'||r.option_type==='PE')},
{label:'09:15–10:59',rows:resolved.filter(r=>{const h=hourIST(r.captured_at);return h!=null&&h>=9&&h<11})},{label:'11:00–12:59',rows:resolved.filter(r=>{const h=hourIST(r.captured_at);return h!=null&&h>=11&&h<13})},{label:'13:00–14:29',rows:resolved.filter(r=>{const h=hourIST(r.captured_at);return h!=null&&h>=13&&h<14.5})},{label:'14:30–15:30',rows:resolved.filter(r=>{const d=new Date(r.captured_at);const parts=new Intl.DateTimeFormat('en-US',{timeZone:'Asia/Kolkata',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(d);const h=Number(parts.find(x=>x.type==='hour')?.value),m=Number(parts.find(x=>x.type==='minute')?.value);return h>14||(h===14&&m>=30)})},
{label:'0 DTE',rows:resolved.filter(r=>dte(r)===0)},{label:'1 DTE',rows:resolved.filter(r=>dte(r)===1)},{label:'2–3 DTE',rows:resolved.filter(r=>{const x=dte(r);return x!=null&&x>=2&&x<=3})},{label:'4+ DTE',rows:resolved.filter(r=>{const x=dte(r);return x!=null&&x>=4})}
],[resolved]);const usable=scenarios[0]?.samples??0;return <Card><CardHeader title="F&O Management Simulation" subtitle="Analytics-only counterfactuals using saved realised outcomes plus observed option-premium MFE. No live rule is changed." action={<Badge variant={usable>=30?'green':usable>=10?'blue':'default'}>{usable>=30?'USABLE SAMPLE':usable>=10?'EARLY SIGNAL':'INSUFFICIENT SAMPLE'}</Badge>}/><CardBody className="space-y-4"><div className="grid grid-cols-1 md:grid-cols-5 gap-2">{scenarios.map((s,i)=><div key={s.name} className="rounded-lg border border-slate-200 dark:border-slate-800 p-3"><div className="flex items-start justify-between gap-2"><b className="text-xs">{s.name}</b>{i>0&&<Badge variant={s.deltaR>0?'green':s.deltaR<0?'red':'default'}>{s.deltaR>=0?'+':''}{s.deltaR.toFixed(2)}R</Badge>}</div><p className="text-lg font-bold mt-1">{s.avgR.toFixed(2)}R</p><p className="text-[11px] text-slate-500">Avg R · Net {s.netR.toFixed(2)}R · {s.samples} matched</p>{i>0&&<><p className="text-[11px] text-slate-500 mt-1">{s.improved} improved · {s.worsened} worsened · {s.unchanged} unchanged</p><div className="mt-2"><Badge variant={evidence(s).variant}>{evidence(s).label}</Badge></div></>}</div>)}</div>
<div className="rounded-lg border border-slate-200 dark:border-slate-800 p-3"><p className="text-sm font-semibold">Subgroup stability gate</p><p className="text-xs text-slate-500 mt-1">Cross-checks management ideas across CE/PE, NSE session windows and DTE. A materially negative evidence-bearing subgroup blocks promotion.</p><div className="grid grid-cols-1 md:grid-cols-2 gap-2 mt-3">{scenarioDefs.map(([name,kind])=>{const s=scenarios.find(x=>x.name===name)!,g=evidence(s),st=stability(name,kind,segments),effective=g.label==='REVIEW CANDIDATE'&&st.label!=='STABLE'?'EARLY CANDIDATE':g.label;return <div key={name} className="rounded-lg bg-slate-50 dark:bg-slate-800 p-3"><div className="flex flex-wrap justify-between gap-2"><b className="text-xs">{name}</b><div className="flex gap-1"><Badge variant={effective==='REVIEW CANDIDATE'?'green':effective==='EARLY CANDIDATE'?'blue':'default'}>{effective}</Badge><Badge variant={st.variant}>{st.label}</Badge></div></div><p className="text-[11px] text-slate-500 mt-2">{st.reason}</p></div>})}</div></div>
<div className="grid grid-cols-1 lg:grid-cols-2 gap-3">{segments.map(seg=><div key={seg.label} className="rounded-lg border border-slate-200 dark:border-slate-800 p-3"><div className="flex justify-between gap-2"><b className="text-sm">{seg.label}</b><Badge variant={seg.rows.length>=20?'green':seg.rows.length>=5?'blue':'default'}>{seg.rows.length} trades</Badge></div><div className="mt-2 space-y-1">{scenarioDefs.map(([n,k])=>{const x=summarize(n,seg.rows,k);return <div key={n} className="grid grid-cols-[1fr_auto] gap-2 text-[11px]"><span className="truncate">{n}</span><b>{x.deltaR>=0?'+':''}{x.deltaR.toFixed(2)}R</b></div>})}</div></div>)}</div>
<div className="rounded-lg border border-slate-200 dark:border-slate-800 p-3 text-xs text-slate-500"><b>Important limitation:</b> MFE comes from roughly one-minute option-LTP observations, not tick-perfect historical candles. These are conservative counterfactuals, not claims about exact intraminute sequencing. Promotion requires later forward/out-of-sample validation.</div><p className="text-xs text-slate-500">EARLY requires ≥5 matched trades, ≥+0.05R and more improved than worsened; REVIEW requires ≥20, ≥+0.10R, consistency, and STABLE subgroup evidence. Nothing here changes option entry, premium stop, targets, or execution readiness.</p></CardBody></Card>}
