import { useMemo,useState } from 'react';
import { Layers3,Play } from 'lucide-react';
import { Badge,Button,Card,CardBody,CardHeader } from '@/components/ui';
import { ALPHAPILOT_API_BASE } from '@/lib/alphaPilotApi';

type Effect={label:string;direction:string;archetype_axis:string;archetype:string;feature:string;value:string;trades:number;avg_r:number;win_rate:number;baseline_trades:number;baseline_avg_r:number;baseline_win_rate:number;delta_avg_r:number;delta_win_rate_pp:number;state:'BOOST'|'DRAG'|'MIXED'|'LOW_SAMPLE'};
type V5={archetype_counts:Record<string,number>;effects:Effect[];hypotheses_tested:number;eligible_hypotheses:number;boosts:number;drags:number;fixed_effect_rules:{min_group_trades:number;delta_avg_r:number;delta_win_rate_pp:number};archetype_rules:Record<string,string>};
type Result={setup_trades:number;eligible_setup_trades:number;matched_trades:number;match_rate_pct:number;overall:{trades:number;avg_r:number;win_rate:number;total_r:number};v5_archetype_context:V5};
type Block={id:string;start:string;end:string};
const BLOCKS:Block[]=[
  {id:'S-0A',start:'2026-05-25',end:'2026-06-05'},
  {id:'S-0B',start:'2026-06-08',end:'2026-06-19'},
  {id:'S-0C',start:'2026-06-22',end:'2026-07-03'},
  {id:'S-1',start:'2026-07-06',end:'2026-07-17'},
  {id:'S-2',start:'2026-07-20',end:'2026-07-31'},
  {id:'S-3',start:'2026-08-03',end:'2026-08-10'},
];
const REQUIRED_REPLICATION_BLOCKS=3;
async function runBlock(b:Block):Promise<Result>{const r=await fetch(`${ALPHAPILOT_API_BASE}/v1/research/market-brain-v4-setup-expectancy`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({start_date:b.start,end_date:b.end})});if(!r.ok){let d='';try{const x=await r.json();d=x?.detail?`: ${x.detail}`:''}catch{}throw new Error(`${b.id} API ${r.status}${d}`)}return r.json()}
function fmtR(v:number){return `${v>=0?'+':''}${Number(v||0).toFixed(3)}R`}
export function MarketBrainArchetypeContextResearch(){
  const[running,setRunning]=useState(false),[progress,setProgress]=useState(''),[results,setResults]=useState<Record<string,Result>>({}),[error,setError]=useState<string|null>(null);
  const replicated=useMemo(()=>{const m=new Map<string,{state:'BOOST'|'DRAG';blocks:string[];opposite:string[];trades:number;weighted:number}>();for(const b of BLOCKS){const v=results[b.id]?.v5_archetype_context;if(!v)continue;for(const e of v.effects){if(e.state!=='BOOST'&&e.state!=='DRAG')continue;const current=m.get(e.label);if(!current){m.set(e.label,{state:e.state,blocks:[b.id],opposite:[],trades:e.trades,weighted:e.avg_r*e.trades});continue}if(current.state===e.state){current.blocks.push(b.id);current.trades+=e.trades;current.weighted+=e.avg_r*e.trades}else current.opposite.push(b.id)}}return[...m.entries()].filter(([,g])=>g.blocks.length>=REQUIRED_REPLICATION_BLOCKS&&g.opposite.length===0).map(([label,g])=>({label,state:g.state,blocks:g.blocks.join(', '),trades:g.trades,avgR:g.trades?g.weighted/g.trades:0})).sort((a,b)=>b.trades-a.trades)},[results]);
  async function run(){setRunning(true);setError(null);setResults({});try{for(const b of BLOCKS){setProgress(`Running ${b.id} · ${b.start} → ${b.end}`);const r=await runBlock(b);if(!r.v5_archetype_context)throw new Error(`${b.id} backend has not deployed Market Brain v5 yet.`);setResults(x=>({...x,[b.id]:r}));await new Promise(res=>setTimeout(res,700))}}catch(e){setError(e instanceof Error?e.message:'Market Brain v5 failed.')}finally{setProgress('');setRunning(false)}}
  const completed=Object.keys(results).length,totalMatched=Object.values(results).reduce((a,x)=>a+x.matched_trades,0),tested=Object.values(results).reduce((a,x)=>a+(x.v5_archetype_context?.hypotheses_tested||0),0),eligible=Object.values(results).reduce((a,x)=>a+(x.v5_archetype_context?.eligible_hypotheses||0),0);
  return <Card><CardHeader title="Market Brain v5 — Setup-Archetype × Context Replication" subtitle="Tests whether frozen Market Brain context matters only for specific historical scanner setup archetypes." action={<Layers3 size={18} className="text-violet-500"/>}/><CardBody className="space-y-4">
    <div className="flex gap-2 flex-wrap"><Badge variant="blue">MARKET BRAIN v5</Badge><Badge variant="default">6 FIXED BLOCKS</Badge><Badge variant="default">ARCHETYPE × CONTEXT</Badge><Badge variant="default">SAME-DIRECTION + SAME-ARCHETYPE BASELINE</Badge><Badge variant="default">3-BLOCK REPLICATION</Badge><Badge variant="default">NO RETUNING</Badge><Badge variant="default">RESEARCH ONLY</Badge><Badge variant="default">PRODUCTION UNCHANGED</Badge></div>
    <div className="flex items-center justify-between gap-3"><p className="text-xs text-slate-500">Frozen archetypes: HIGH_ALPHA ≥75 vs STANDARD_ALPHA; HIGH_RR ≥2.0 vs STANDARD_RR; EARLY_SETUP through 11:30 IST vs LATE_SETUP. BOOST/DRAG requires ≥10 trades, ±0.20R versus the same-direction/same-archetype baseline and ±8pp win-rate difference. Replication requires the exact same effect in ≥3 blocks with no opposite qualifying block.</p><Button variant="primary" onClick={run} disabled={running}><Play size={14} className="inline mr-1"/>{running?'Running v5…':'Run Market Brain v5'}</Button></div>
    {progress&&<div className="rounded-lg border p-3 text-xs">{progress}</div>}{error&&<div className="rounded-lg border border-red-200 p-3 text-sm text-red-600">{error}</div>}
    <div className="overflow-x-auto rounded-lg border"><table className="w-full text-xs"><thead className="bg-slate-50 dark:bg-slate-900"><tr><th className="p-2 text-left">Block</th><th>Dates</th><th>Setups</th><th>Eligible</th><th>Matched</th><th>Match</th><th>Avg R</th><th>Win</th><th>Hypotheses</th><th>Eligible H</th><th>Boosts</th><th>Drags</th><th>Status</th></tr></thead><tbody>{BLOCKS.map(b=>{const r=results[b.id],v=r?.v5_archetype_context;return <tr key={b.id} className="border-t"><td className="p-2 font-semibold">{b.id}</td><td>{b.start} → {b.end}</td><td className="text-center">{r?.setup_trades??'—'}</td><td className="text-center">{r?.eligible_setup_trades??'—'}</td><td className="text-center">{r?.matched_trades??'—'}</td><td className="text-center">{r?.match_rate_pct!=null?`${r.match_rate_pct.toFixed(1)}%`:'—'}</td><td className="text-center">{r?fmtR(r.overall.avg_r):'—'}</td><td className="text-center">{r?`${r.overall.win_rate.toFixed(1)}%`:'—'}</td><td className="text-center">{v?.hypotheses_tested??'—'}</td><td className="text-center">{v?.eligible_hypotheses??'—'}</td><td className="text-center">{v?.boosts??'—'}</td><td className="text-center">{v?.drags??'—'}</td><td className="text-center"><Badge variant={r?'green':'default'}>{r?'COMPLETE':'PENDING'}</Badge></td></tr>})}</tbody></table></div>
    {completed>0&&<div className="grid grid-cols-2 md:grid-cols-6 gap-3"><Stat label="Completed blocks" value={`${completed}/${BLOCKS.length}`}/><Stat label="Matched setups" value={String(totalMatched)}/><Stat label="Hypotheses tested" value={String(tested)}/><Stat label="Eligible hypotheses" value={String(eligible)}/><Stat label="Replicated effects" value={String(replicated.length)}/><div className="rounded-lg border p-3"><p className="text-xs text-slate-500">Decision</p><Badge variant={replicated.length?'blue':'default'}>{completed<BLOCKS.length?'INCOMPLETE':replicated.length?'REPLICATED_ARCHETYPE_CONTEXT_CANDIDATE':'NO_REPLICATED_ARCHETYPE_CONTEXT_EFFECT'}</Badge></div></div>}
    {replicated.length>0&&<div className="overflow-x-auto rounded-lg border"><table className="w-full text-xs"><thead><tr><th className="p-2 text-left">Replicated archetype-context effect</th><th>Effect</th><th>Blocks</th><th>Trades</th><th>Weighted Avg R</th></tr></thead><tbody>{replicated.map((x,i)=><tr key={i} className="border-t"><td className="p-2 font-medium">{x.label}</td><td className="text-center"><Badge variant={x.state==='BOOST'?'green':'red'}>{x.state}</Badge></td><td className="text-center">{x.blocks}</td><td className="text-center">{x.trades}</td><td className="text-center font-semibold">{fmtR(x.avgR)}</td></tr>)}</tbody></table></div>}
    {completed>0&&<div className="space-y-2"><p className="text-sm font-semibold">Top block effects</p>{BLOCKS.map(b=>{const v=results[b.id]?.v5_archetype_context;if(!v)return null;const rows=v.effects.filter(e=>e.state==='BOOST'||e.state==='DRAG').slice(0,8);return <div key={b.id}><p className="text-xs font-semibold mb-1">{b.id}</p>{rows.length?<div className="overflow-x-auto rounded-lg border"><table className="w-full text-xs"><thead><tr><th className="p-2 text-left">Archetype × Context</th><th>Trades</th><th>Baseline N</th><th>Avg R</th><th>Δ Avg R</th><th>Win</th><th>Δ Win</th><th>Effect</th></tr></thead><tbody>{rows.map((e,i)=><tr key={i} className="border-t"><td className="p-2 font-medium">{e.label}</td><td className="text-center">{e.trades}</td><td className="text-center">{e.baseline_trades}</td><td className="text-center">{fmtR(e.avg_r)}</td><td className="text-center">{fmtR(e.delta_avg_r)}</td><td className="text-center">{e.win_rate.toFixed(1)}%</td><td className="text-center">{e.delta_win_rate_pp>=0?'+':''}{e.delta_win_rate_pp.toFixed(1)}pp</td><td className="text-center"><Badge variant={e.state==='BOOST'?'green':'red'}>{e.state}</Badge></td></tr>)}</tbody></table></div>:<p className="text-xs text-slate-500">No fixed BOOST/DRAG archetype-context effect in this block.</p>}</div>})}</div>}
    {completed>0&&<div><p className="text-sm font-semibold mb-2">Archetype coverage diagnostics</p><div className="grid grid-cols-1 md:grid-cols-3 gap-3">{Object.entries(results[BLOCKS.find(b=>results[b.id])?.id||'']?.v5_archetype_context?.archetype_rules||{}).map(([k,v])=><div className="rounded-lg border p-3" key={k}><p className="text-xs font-semibold">{k}</p><p className="text-[11px] text-slate-500 mt-1">{v}</p></div>)}</div></div>}
    <p className="text-[11px] text-slate-500">v5 uses only information available at setup time and compares each context state against the same-direction, same-archetype baseline. The search space is reported explicitly through Hypotheses tested and Eligible hypotheses. Even a replicated result is only a frozen research candidate for untouched validation; it cannot alter production trading rules.</p>
  </CardBody></Card>
}
function Stat({label,value}:{label:string;value:string}){return <div className="rounded-lg border p-3"><p className="text-xs text-slate-500">{label}</p><p className="text-lg font-bold">{value}</p></div>}
