import { useState } from 'react';
import { Activity, RefreshCw } from 'lucide-react';
import { Badge, Button, Card, CardBody, CardHeader } from '@/components/ui';
import { fetchMarketBrainV2, type MarketBrainV2Result } from '@/lib/marketBrainV2Api';

export function MarketBrainV2(){
  const [result,setResult]=useState<MarketBrainV2Result|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState<string|null>(null);
  async function run(){setLoading(true);setError(null);try{setResult(await fetchMarketBrainV2())}catch(e){setError(e instanceof Error?e.message:'Market Brain v2 failed.')}finally{setLoading(false)}}
  const tone=(v:string)=>/LONG|RISK_ON|BUYING|UP/.test(v)?'green':/SHORT|RISK_OFF|SELLING|DOWN|ELEVATED/.test(v)?'red':'default';
  return <Card><CardHeader title="Market Brain v2 — Flow, Breadth, Cross-Asset & Event Context" subtitle="Research-only context designed to measure whether the wider market is actually supporting a setup. Production rules remain unchanged." action={<Activity size={18} className="text-emerald-500"/>}/><CardBody className="space-y-4">
    <div className="flex gap-2 flex-wrap"><Badge variant="blue">MARKET BRAIN v2</Badge><Badge variant="default">BREADTH</Badge><Badge variant="default">FLOW PROXY</Badge><Badge variant="default">CROSS-ASSET</Badge><Badge variant="default">EVENT RISK</Badge><Badge variant="default">RESEARCH ONLY</Badge><Badge variant="default">PRODUCTION UNCHANGED</Badge></div>
    <div className="flex items-center justify-between gap-3"><p className="text-xs text-slate-500">Runs on current 15m NSE context plus Global Intelligence and GIFT NIFTY. Missing cross-assets are shown as unavailable rather than fabricated.</p><Button variant="primary" onClick={run} disabled={loading}><RefreshCw size={14} className="inline mr-1"/>{loading?'Reading market context…':'Refresh Market Brain v2'}</Button></div>
    {error&&<div className="rounded-lg border border-red-200 p-3 text-sm text-red-600">{error}</div>}
    {result&&<><div className="grid grid-cols-2 md:grid-cols-4 gap-3"><div className="rounded-lg border p-3"><p className="text-[11px] text-slate-500">Composite</p><Badge variant={tone(result.composite.state)}>{result.composite.state}</Badge><p className="text-lg font-semibold mt-1">{result.composite.score}</p><p className="text-[10px] text-slate-500">Confidence {result.composite.confidence}</p></div><div className="rounded-lg border p-3"><p className="text-[11px] text-slate-500">Breadth</p><Badge variant={tone(result.breadth.state)}>{result.breadth.state}</Badge><p className="text-sm mt-1">{result.breadth.advancers} up · {result.breadth.decliners} down</p><p className="text-[10px] text-slate-500">{result.breadth.above_vwap}/{result.breadth.total} above VWAP</p></div><div className="rounded-lg border p-3"><p className="text-[11px] text-slate-500">Flow proxy</p><Badge variant={tone(result.flow.state)}>{result.flow.state}</Badge><p className="text-lg font-semibold mt-1">{result.flow.score}</p><p className="text-[10px] text-slate-500">Strong-volume: {result.flow.strong_volume_names.join(', ')||'none'}</p></div><div className="rounded-lg border p-3"><p className="text-[11px] text-slate-500">Event context</p><Badge variant={tone(result.event_context.state)}>{result.event_context.state}</Badge><p className="text-sm mt-1">{result.event_context.high_impact_count} high-impact</p><p className="text-[10px] text-slate-500">Context only, not a gate</p></div></div>
    <div className="grid grid-cols-1 md:grid-cols-2 gap-3"><div className="rounded-lg border p-3"><p className="text-sm font-semibold mb-2">Index + cross-asset confirmation</p><div className="text-xs space-y-2">{result.index_context.nifty&&<div className="flex justify-between"><span>NIFTY</span><span>{result.index_context.nifty.change_pct}% · {result.index_context.nifty.trend} · {result.index_context.nifty.above_vwap?'above':'below'} VWAP</span></div>}{result.index_context.banknifty&&<div className="flex justify-between"><span>BANKNIFTY</span><span>{result.index_context.banknifty.change_pct}% · {result.index_context.banknifty.trend} · {result.index_context.banknifty.above_vwap?'above':'below'} VWAP</span></div>}<div className="flex justify-between"><span>GIFT NIFTY</span><span>{result.cross_asset.gift_nifty.bias}{typeof result.cross_asset.gift_nifty.change_pct==='number'?` · ${result.cross_asset.gift_nifty.change_pct}%`:''}</span></div><p className="text-[10px] text-slate-500">Pending reliable feeds: {result.cross_asset.unavailable.join(' · ')}</p></div></div><div className="rounded-lg border p-3"><p className="text-sm font-semibold mb-2">Event watch</p>{result.event_context.items.length===0?<p className="text-xs text-slate-500">No qualifying event headlines found.</p>:<div className="space-y-2">{result.event_context.items.slice(0,5).map((x,i)=><div key={i} className="text-xs border-t first:border-t-0 pt-2 first:pt-0"><div className="flex gap-1 mb-1"><Badge variant={x.impact==='HIGH'?'red':'default'}>{x.impact}</Badge><Badge variant="default">{x.topic}</Badge></div><p>{x.headline}</p><p className="text-slate-500">{x.source}</p></div>)}</div>}</div></div>
    <div className="rounded-lg border p-3 overflow-x-auto"><p className="text-sm font-semibold mb-2">Breadth proxy constituents</p><table className="w-full text-xs"><thead><tr className="text-left text-slate-500"><th>Symbol</th><th>15m change</th><th>VWAP</th><th>Volume ratio</th><th>5-bar trend</th></tr></thead><tbody>{result.breadth.rows.map(x=><tr key={x.symbol} className="border-t"><td className="py-2 font-semibold">{x.symbol}</td><td>{x.change_pct}%</td><td>{x.above_vwap?'ABOVE':'BELOW'}</td><td>{x.volume_ratio}×</td><td><Badge variant={tone(x.trend)}>{x.trend}</Badge></td></tr>)}</tbody></table></div>
    <div className="text-[11px] text-slate-500 space-y-1">{result.limitations.map((x,i)=><p key={i}>• {x}</p>)}</div></>}
  </CardBody></Card>
}
