import { useMemo,useState } from 'react';
import { BrainCircuit,Play } from 'lucide-react';
import { Badge,Button,Card,CardBody,CardHeader,Input } from '@/components/ui';
import { runMarketRegimeResearch,type MarketRegimeResponse } from '@/lib/marketRegimeResearchApi';

function offset(days:number){const d=new Date();d.setDate(d.getDate()-days);return d.toISOString().slice(0,10)}
function fmt(v:unknown,d=2){const n=Number(v);return Number.isFinite(n)?n.toFixed(d):'—'}
function modelName(v:unknown){const s=String(v??'—');return s==='CE_PREMIUM_MOMENTUM'?'CE Premium Momentum':s==='PE_PREMIUM_MOMENTUM'?'PE Premium Momentum':s==='CE_PE_RELATIVE_STRENGTH'?'CE vs PE Relative Strength':s}

export function MarketRegimeResearch(){
 const [symbolsText,setSymbolsText]=useState('RELIANCE,SBIN,AXISBANK,HDFCBANK,ICICIBANK,TATASTEEL,HINDALCO,ONGC,INFY,TCS');
 const [start,setStart]=useState(offset(10));const [end,setEnd]=useState(offset(1));const [rr,setRR]=useState('1.5');const [maxTrades,setMaxTrades]=useState('30');const [cost,setCost]=useState('10');
 const [running,setRunning]=useState(false);const [error,setError]=useState<string|null>(null);const [result,setResult]=useState<MarketRegimeResponse|null>(null);
 const symbols=useMemo(()=>symbolsText.split(',').map(x=>x.trim().toUpperCase()).filter(Boolean).slice(0,20),[symbolsText]);
 async function run(){if(!symbols.length||!start||!end){setError('Enter symbols and dates.');return}if(end<start){setError('End date must be on or after start date.');return}setRunning(true);setError(null);setResult(null);try{setResult(await runMarketRegimeResearch({symbols,start_date:start,end_date:end,premium_min_risk_reward:Number(rr)||1.5,max_trades_per_model:Math.max(1,Math.min(Number(maxTrades)||30,50)),round_trip_cost_bps:Math.max(0,Number(cost)||0)}))}catch(e){setError(e instanceof Error?e.message:'Market Brain research failed.')}finally{setRunning(false)}}
 return <Card><CardHeader title="Market Brain — Regime Research v1" subtitle="Annotates real option-premium research trades with NIFTY/stock trend, relative strength, VWAP/EMA, volatility and volume regime." action={<BrainCircuit size={18} className="text-violet-500"/>}/><CardBody className="space-y-4">
 <div className="flex gap-2 flex-wrap"><Badge variant="blue">MARKET BRAIN</Badge><Badge variant="default">RESEARCH ONLY</Badge><Badge variant="default">FROZEN DEFINITIONS</Badge><Badge variant="default">PRODUCTION UNCHANGED</Badge></div>
 <div className="grid grid-cols-1 md:grid-cols-6 gap-2 items-end"><Input label="Symbols" value={symbolsText} onChange={setSymbolsText}/><Input label="Start date" type="date" value={start} onChange={setStart}/><Input label="End date" type="date" value={end} onChange={setEnd}/><Input label="Premium Min R:R" type="number" value={rr} onChange={setRR}/><Input label="Max trades / model" type="number" value={maxTrades} onChange={setMaxTrades}/><Input label="Round-trip cost (bps)" type="number" value={cost} onChange={setCost}/></div>
 <div className="flex justify-end"><Button variant="primary" onClick={run} disabled={running}><Play size={14} className="inline mr-1"/>{running?'Classifying market regimes…':'Run Market Brain Research'}</Button></div>
 <p className="text-[11px] text-slate-500">V1 classifies each Phase-2 premium signal as TREND_LONG, TREND_SHORT, RANGE or CHOP using only information available at the signal time. Positive cells are diagnostics, not live filters.</p>
 {error&&<div className="rounded-lg border border-red-200 p-3 text-sm text-red-600">{error}</div>}
 {result&&<><div><p className="text-sm font-semibold mb-2">Strategy × Market Regime</p><div className="overflow-x-auto rounded-lg border border-slate-200 dark:border-slate-800"><table className="w-full text-xs"><thead className="bg-slate-50 dark:bg-slate-900"><tr><th className="p-2 text-left">Model</th><th>Regime</th><th>Trades</th><th>Win %</th><th>Avg R</th><th>Total R</th><th>PF</th></tr></thead><tbody>{(result.strategy_regime_matrix??[]).map((r,i)=><tr key={`${r.model}-${r.regime}-${i}`} className="border-t border-slate-200 dark:border-slate-800"><td className="p-2 font-semibold">{modelName(r.model)}</td><td className="text-center font-semibold">{r.regime}</td><td className="text-center">{r.trades??0}</td><td className="text-center">{fmt(r.win_rate,1)}%</td><td className={`text-center font-semibold ${Number(r.average_r)>0?'text-emerald-600':Number(r.average_r)<0?'text-red-600':''}`}>{Number(r.average_r)>0?'+':''}{fmt(r.average_r)}R</td><td className="text-center">{Number(r.total_r)>0?'+':''}{fmt(r.total_r)}R</td><td className="text-center">{fmt(r.profit_factor)}</td></tr>)}</tbody></table></div></div>
 <div><p className="text-sm font-semibold mb-2">Research Trade Permission Diagnostic</p><div className="overflow-x-auto rounded-lg border border-slate-200 dark:border-slate-800"><table className="w-full text-xs"><thead className="bg-slate-50 dark:bg-slate-900"><tr><th className="p-2 text-left">Model</th><th>Brain Permission</th><th>Trades</th><th>Avg R</th><th>Total R</th></tr></thead><tbody>{(result.strategy_permission_matrix??[]).map((r,i)=><tr key={`${r.model}-${r.permission}-${i}`} className="border-t border-slate-200 dark:border-slate-800"><td className="p-2 font-semibold">{modelName(r.model)}</td><td className="text-center">{r.permission}</td><td className="text-center">{r.trades??0}</td><td className="text-center">{Number(r.average_r)>0?'+':''}{fmt(r.average_r)}R</td><td className="text-center">{Number(r.total_r)>0?'+':''}{fmt(r.total_r)}R</td></tr>)}</tbody></table></div></div>
 {(result.errors?.length??0)>0&&<div className="rounded-lg border border-amber-200 p-3 text-xs text-amber-700">{result.errors!.length} data/contract errors were excluded rather than fabricated.</div>}
 <p className="text-xs text-slate-500">Do not convert a positive regime cell into a live trading rule. Repeat it on untouched symbols and dates first.</p></>}
 </CardBody></Card>
}
