import { useMemo, useState } from 'react';
import { Activity, Play } from 'lucide-react';
import { Badge, Button, Card, CardBody, CardHeader, Input } from '@/components/ui';
import { runOptionNativePhase2, type OptionNativePhase2Response } from '@/lib/optionNativePhase2Api';

function offset(days:number){const d=new Date();d.setDate(d.getDate()-days);return d.toISOString().slice(0,10)}
function fmt(v:unknown,d=2){const n=Number(v);return Number.isFinite(n)?n.toFixed(d):'—'}
function name(v:unknown){const s=String(v??'—');return s==='CE_PREMIUM_MOMENTUM'?'CE Premium Momentum':s==='PE_PREMIUM_MOMENTUM'?'PE Premium Momentum':s==='CE_PE_RELATIVE_STRENGTH'?'CE vs PE Relative Strength':s}

export function OptionNativePhase2(){
  const [symbolsText,setSymbolsText]=useState('RELIANCE,SBIN,AXISBANK,HDFCBANK,ICICIBANK,TATASTEEL,HINDALCO,ONGC,INFY,TCS');
  const [start,setStart]=useState(offset(10)); const [end,setEnd]=useState(offset(1));
  const [rr,setRR]=useState('1.5'); const [maxTrades,setMaxTrades]=useState('30'); const [cost,setCost]=useState('10');
  const [running,setRunning]=useState(false); const [error,setError]=useState<string|null>(null); const [result,setResult]=useState<OptionNativePhase2Response|null>(null);
  const symbols=useMemo(()=>symbolsText.split(',').map(x=>x.trim().toUpperCase()).filter(Boolean).slice(0,20),[symbolsText]);
  async function run(){if(!symbols.length||!start||!end){setError('Enter symbols and dates.');return}if(end<start){setError('End date must be on or after start date.');return}setRunning(true);setError(null);setResult(null);try{setResult(await runOptionNativePhase2({symbols,start_date:start,end_date:end,premium_min_risk_reward:Number(rr)||1.5,max_trades_per_model:Math.max(1,Math.min(Number(maxTrades)||30,50)),round_trip_cost_bps:Math.max(0,Number(cost)||0)}))}catch(e){setError(e instanceof Error?e.message:'Phase 2 research failed.')}finally{setRunning(false)}}
  return <Card><CardHeader title="Strategy Research v3 — Phase 2 Premium Signals" subtitle="Actual ATM option-premium candles generate the research signal. CE and PE are tested separately, plus direct CE-vs-PE relative strength." action={<Activity size={18} className="text-cyan-500"/>}/><CardBody className="space-y-4">
    <div className="flex gap-2 flex-wrap"><Badge variant="blue">OPTION-NATIVE</Badge><Badge variant="default">RESEARCH ONLY</Badge><Badge variant="default">PRODUCTION UNCHANGED</Badge></div>
    <div className="grid grid-cols-1 md:grid-cols-6 gap-2 items-end"><Input label="Symbols" value={symbolsText} onChange={setSymbolsText}/><Input label="Start date" type="date" value={start} onChange={setStart}/><Input label="End date" type="date" value={end} onChange={setEnd}/><Input label="Premium Min R:R" type="number" value={rr} onChange={setRR}/><Input label="Max trades / model" type="number" value={maxTrades} onChange={setMaxTrades}/><Input label="Round-trip cost (bps)" type="number" value={cost} onChange={setCost}/></div>
    <div className="flex justify-end"><Button variant="primary" onClick={run} disabled={running}><Play size={14} className="inline mr-1"/>{running?'Scanning actual option premiums…':'Run Premium Signal Discovery'}</Button></div>
    <p className="text-[11px] text-slate-500">ATM CE/PE contracts are resolved from the real instrument master using the 09:45 underlying reference. Signals then come from option-premium EMA/VWAP/momentum behaviour itself. Entry is the next 5-minute premium candle, avoiding look-ahead.</p>
    {error&&<div className="rounded-lg border border-red-200 p-3 text-sm text-red-600">{error}</div>}
    {result&&<><div className="overflow-x-auto rounded-lg border border-slate-200 dark:border-slate-800"><table className="w-full text-xs"><thead className="bg-slate-50 dark:bg-slate-900"><tr><th className="p-2 text-left">Rank</th><th className="text-left">Model</th><th>Trades</th><th>Win %</th><th>Avg R</th><th>Total R</th><th>Profit Factor</th><th>Max DD</th><th>MFE</th><th>MAE</th><th>Status</th></tr></thead><tbody>{(result.leaderboard??[]).map((r,i)=>{const st=String(r.classification??'FAIL');return <tr key={String(r.model)} className="border-t border-slate-200 dark:border-slate-800"><td className="p-2 font-semibold">#{r.rank??i+1}</td><td className="font-semibold">{name(r.model)}</td><td className="text-center">{r.trades??0}</td><td className="text-center">{fmt(r.win_rate,1)}%</td><td className={`text-center font-semibold ${Number(r.average_r)>0?'text-emerald-600':Number(r.average_r)<0?'text-red-600':''}`}>{Number(r.average_r)>0?'+':''}{fmt(r.average_r)}R</td><td className="text-center">{Number(r.total_r)>0?'+':''}{fmt(r.total_r)}R</td><td className="text-center">{fmt(r.profit_factor)}</td><td className="text-center">{fmt(r.max_drawdown_r)}R</td><td className="text-center">{fmt(r.avg_mfe_r)}R</td><td className="text-center">{fmt(r.avg_mae_r)}R</td><td className="text-center"><Badge variant={st==='PASS'?'green':st==='WATCH'?'amber':'red'}>{st}</Badge></td></tr>})}</tbody></table></div>
    <div className="grid grid-cols-1 md:grid-cols-3 gap-2">{(result.leaderboard??[]).map(r=><div key={`reg-${String(r.model)}`} className="rounded-lg border border-slate-200 dark:border-slate-800 p-3"><p className="text-sm font-semibold">{name(r.model)}</p><p className="text-[11px] text-slate-500 mt-1">NIFTY regime diagnostic</p><div className="mt-2 space-y-1 text-xs">{Object.entries(r.by_regime??{}).map(([reg,s])=><div className="flex justify-between gap-3" key={reg}><span>{reg}</span><span>{s.trades??0} · {Number(s.average_r)>0?'+':''}{fmt(s.average_r)}R avg</span></div>)}</div></div>)}</div>
    {(result.errors?.length??0)>0&&<div className="rounded-lg border border-amber-200 p-3 text-xs text-amber-700">{result.errors!.length} contract/data errors occurred. They were excluded rather than fabricated.</div>}
    <p className="text-xs text-slate-500">Do not promote a model from one run. A positive model must survive a larger development sample and an untouched time/symbol sample.</p></>}
  </CardBody></Card>
}
