import { useEffect, useMemo, useState } from 'react';
import { AlertTriangle, Play, RotateCcw } from 'lucide-react';
import { Button, Card, CardBody, CardHeader } from '@/components/ui';
import { runHistoricalBacktest, type BacktestResponse } from '@/lib/alphaPilotApi';
import type { StoredMultiValidation } from '@/lib/backtestStorage';

type Trade = BacktestResponse['trades'][number];
type PeriodResult = { label:string; startDate:string; endDate:string; allDay:BacktestResponse; before1030:BacktestResponse; before1200:BacktestResponse };
type SavedValidation = StoredMultiValidation<PeriodResult>;
type Coverage = { requested:number; succeeded:number; failed:number; errors:{symbol:string;error:string}[]; valid:boolean; reason?:string };
type OosPeriod = { label:string; startDate:string; endDate:string; response:BacktestResponse; coverage:Coverage };
type OosState = { id:string; createdAt:string; periods:OosPeriod[] };

const FNO_UNIVERSE = ['RELIANCE','TCS','INFY','HDFCBANK','ICICIBANK','SBIN','AXISBANK','KOTAKBANK','INDUSINDBK','BAJFINANCE','BAJAJFINSV','LT','BHARTIARTL','ITC','HINDUNILVR','MARUTI','M&M','TATAMOTORS','SUNPHARMA','DRREDDY','CIPLA','DIVISLAB','APOLLOHOSP','WIPRO','HCLTECH','TECHM','LTIM','TITAN','ASIANPAINT','ULTRACEMCO','TATASTEEL','JSWSTEEL','HINDALCO','COALINDIA','ONGC','NTPC','POWERGRID','ADANIENT','ADANIPORTS','GRASIM','NESTLEIND','BRITANNIA','EICHERMOT','HEROMOTOCO'];
const FROZEN_EXCLUDED = new Set(['ADANIENT','ADANIPORTS','BAJAJFINSV','BAJFINANCE','ICICIBANK','ONGC','TECHM','WIPRO']);
const BATCH_SIZE=5;
function shiftDate(v:string,d:number){const x=new Date(`${v}T00:00:00Z`);x.setUTCDate(x.getUTCDate()+d);return x.toISOString().slice(0,10)}
function minutes(ts:string){const d=new Date(ts);return d.getHours()*60+d.getMinutes()}
function maxDD(ts:Trade[]){let e=0,p=0,m=0;for(const t of [...ts].sort((a,b)=>a.timestamp.localeCompare(b.timestamp))){e+=t.r_multiple;p=Math.max(p,e);m=Math.max(m,p-e)}return m}
function metrics(ts:Trade[]){const wins=ts.filter(t=>t.r_multiple>0).length,losses=ts.filter(t=>t.r_multiple<0).length,totalR=ts.reduce((s,t)=>s+t.r_multiple,0);return{trades:ts.length,wins,losses,winRate:ts.length?wins/ts.length*100:0,totalR,avgR:ts.length?totalR/ts.length:0,maxDD:maxDD(ts)}}
function fmtR(v:number){return`${v>0?'+':''}${v.toFixed(2)}R`} function tone(v:number){return v>0?'text-emerald-600':v<0?'text-red-600':''}
function storageKey(id:string){return`alphapilot.oosValidation.v2.${id}`}
function parseSymbols(v:SavedValidation){return v.universeMode==='FNO44'?FNO_UNIVERSE:v.symbolsText.split(',').map(x=>x.trim().toUpperCase()).filter(Boolean)}
function combine(parts:BacktestResponse[],startDate:string,endDate:string,minRR:number){const trades=parts.flatMap(x=>x.trades??[]).sort((a,b)=>a.timestamp.localeCompare(b.timestamp));const wins=trades.filter(t=>t.r_multiple>0).length,losses=trades.filter(t=>t.r_multiple<0).length,totalR=trades.reduce((s,t)=>s+t.r_multiple,0);return{mode:'HISTORICAL_UNDERLYING_BACKTEST_BATCHED',start_date:startDate,end_date:endDate,min_risk_reward:minRR,entry_before:null,summary:{trades:trades.length,wins,losses,win_rate:trades.length?wins/trades.length*100:0,total_r:totalR,average_r:trades.length?totalR/trades.length:0,max_drawdown_r:maxDD(trades)},trades,errors:parts.flatMap(x=>x.errors??[]),limitations:parts[0]?.limitations??[]} as BacktestResponse}

export function OutOfSampleValidation({validation}:{validation:SavedValidation}){
 const[running,setRunning]=useState(false),[progress,setProgress]=useState('');const[error,setError]=useState<string|null>(null),[saved,setSaved]=useState<OosState|null>(null);const symbols=useMemo(()=>parseSymbols(validation),[validation]);
 const specs=useMemo(()=>{const s=new Date(`${validation.startDate}T00:00:00Z`).getTime(),e=new Date(`${validation.endDate}T00:00:00Z`).getTime(),span=Math.max(1,Math.round((e-s)/86400000)+1);return[3,4,5].map((n,i)=>({label:`OOS Period ${i+1}`,startDate:shiftDate(validation.startDate,-n*span),endDate:shiftDate(validation.endDate,-n*span)}))},[validation.startDate,validation.endDate]);
 useEffect(()=>{try{const raw=localStorage.getItem(storageKey(validation.id));setSaved(raw?JSON.parse(raw):null)}catch{setSaved(null)}},[validation.id]);
 async function run(){setRunning(true);setError(null);setProgress('Starting out-of-sample validation...');try{const periods:OosPeriod[]=[];const rr=Number(validation.minRR)||1.5;for(let p=0;p<specs.length;p++){const spec=specs[p],parts:BacktestResponse[]=[];let succeeded=0;const requestErrors:{symbol:string;error:string}[]=[];for(let i=0;i<symbols.length;i+=BATCH_SIZE){const batch=symbols.slice(i,i+BATCH_SIZE);setProgress(`${spec.label}: stocks ${i+1}–${Math.min(i+BATCH_SIZE,symbols.length)} of ${symbols.length}`);try{const r=await runHistoricalBacktest(batch,spec.startDate,spec.endDate,rr,null);parts.push(r);const backendErrors=r.errors??[];requestErrors.push(...backendErrors);const failedSet=new Set(backendErrors.map(x=>x.symbol));succeeded+=batch.filter(x=>!failedSet.has(x)).length}catch(e){const msg=e instanceof Error?e.message:'Backend request failed';batch.forEach(symbol=>requestErrors.push({symbol,error:msg}))}}
 const response=combine(parts,spec.startDate,spec.endDate,rr);const failedSymbols=new Set(requestErrors.map(x=>x.symbol));succeeded=Math.min(symbols.length,Math.max(0,succeeded));const failed=Math.max(failedSymbols.size,symbols.length-succeeded);const coverageRatio=symbols.length?succeeded/symbols.length:0;let valid=coverageRatio>=0.8;let reason=valid?undefined:`Only ${succeeded}/${symbols.length} symbols returned usable backend coverage.`;if(response.trades.length===0){valid=false;reason=failed?`${reason??''} No historical trades were returned; backend/data errors are shown below.`:'Backend returned zero historical trades for the entire requested universe. Treat this period as unavailable/insufficient data, not a zero-performance strategy result.'}
 const period={...spec,response,coverage:{requested:symbols.length,succeeded,failed,errors:requestErrors,valid,reason}};periods.push(period);const cp={id:validation.id,createdAt:new Date().toISOString(),periods};setSaved(cp);try{localStorage.setItem(storageKey(validation.id),JSON.stringify(cp))}catch{}}
 const validCount=periods.filter(x=>x.coverage.valid).length;setProgress(validCount===periods.length?'Out-of-sample validation complete.':`OOS run finished, but only ${validCount}/${periods.length} periods are valid. Invalid periods are excluded from performance comparison.`)}catch(e){setError(e instanceof Error?e.message:'Out-of-sample validation failed.')}finally{setRunning(false)}}
 function clear(){try{localStorage.removeItem(storageKey(validation.id))}catch{}setSaved(null);setProgress('');setError(null)}
 const analysis=useMemo(()=>{if(!saved)return null;const valid=saved.periods.filter(p=>p.coverage?.valid);const rows=valid.flatMap(period=>{const ce=period.response.trades.filter(t=>t.action==='BUY CE'&&minutes(t.timestamp)>=630&&minutes(t.timestamp)<720);return[{period,key:'A',...metrics(ce)},{period,key:'B',...metrics(ce.filter(t=>!FROZEN_EXCLUDED.has(t.symbol)))}]});const combined=['A','B'].map(key=>{const ts=valid.flatMap(p=>p.response.trades.filter(t=>t.action==='BUY CE'&&minutes(t.timestamp)>=630&&minutes(t.timestamp)<720&&(key==='A'||!FROZEN_EXCLUDED.has(t.symbol))));return{key,...metrics(ts)}});return{rows,combined,validCount:valid.length}},[saved]);
 return <Card><CardHeader title="Out-of-Sample Strategy Validation" subtitle="Tests frozen BUY CE hypotheses on earlier periods, with explicit backend/data coverage diagnostics."/><CardBody className="space-y-5"><div className="rounded-lg border border-blue-200 bg-blue-50/60 dark:border-blue-900 dark:bg-blue-950/20 p-3 text-xs"><b>Rules are frozen.</b> Candidate A = BUY CE 10:30–12:00. Candidate B = same rule excluding exactly: {[...FROZEN_EXCLUDED].join(', ')}.</div><div className="text-xs text-slate-500"><b>OOS periods:</b> {specs.map(x=>`${x.startDate} → ${x.endDate}`).join(' · ')}</div><div className="flex gap-2"><Button onClick={run} disabled={running}><Play size={15}/>{running?'Running...':saved?'Rerun OOS Validation':'Run OOS Validation'}</Button>{saved&&<Button variant="ghost" onClick={clear} disabled={running}><RotateCcw size={15}/>Clear saved OOS result</Button>}</div>{progress&&<p className="text-xs font-medium text-blue-600">{progress}</p>}{error&&<p className="text-xs font-medium text-red-600">{error}</p>}
 {saved&&<div><h3 className="text-sm font-semibold mb-2">Historical data coverage</h3><div className="space-y-2">{saved.periods.map(p=><div key={p.label} className={`rounded-lg border p-3 text-xs ${p.coverage.valid?'border-emerald-200':'border-amber-300 bg-amber-50/50 dark:bg-amber-950/20'}`}><div className="flex items-center gap-2 font-semibold">{!p.coverage.valid&&<AlertTriangle size={14}/>} {p.label} · {p.startDate} → {p.endDate} · {p.coverage.valid?'VALID':'INVALID / INSUFFICIENT DATA'}</div><div className="mt-1">Requested {p.coverage.requested} · Successfully processed {p.coverage.succeeded} · Failed {p.coverage.failed} · Historical trades returned {p.response.trades.length}</div>{p.coverage.reason&&<div className="mt-1 font-medium">{p.coverage.reason}</div>}{p.coverage.errors.length>0&&<details className="mt-2"><summary className="cursor-pointer">Backend errors ({p.coverage.errors.length})</summary><div className="mt-1 max-h-40 overflow-auto space-y-1">{p.coverage.errors.map((e,i)=><div key={i}><b>{e.symbol}:</b> {e.error}</div>)}</div></details>}</div>)}</div></div>}
 {analysis&&analysis.validCount>0&&<><div><h3 className="text-sm font-semibold mb-2">Combined out-of-sample comparison <span className="text-xs font-normal text-slate-500">({analysis.validCount} valid period{analysis.validCount===1?'':'s'} only)</span></h3><div className="overflow-x-auto rounded-lg border"><table className="w-full text-xs"><thead><tr><th className="text-left p-2">Candidate</th><th className="text-right p-2">Trades</th><th className="text-right p-2">W/L</th><th className="text-right p-2">Win %</th><th className="text-right p-2">Total R</th><th className="text-right p-2">Avg R</th><th className="text-right p-2">Max DD</th></tr></thead><tbody>{analysis.combined.map(r=><tr key={r.key} className="border-t"><td className="p-2 font-semibold">Candidate {r.key}</td><td className="p-2 text-right">{r.trades}</td><td className="p-2 text-right">{r.wins}/{r.losses}</td><td className="p-2 text-right">{r.winRate.toFixed(1)}%</td><td className={`p-2 text-right font-semibold ${tone(r.totalR)}`}>{fmtR(r.totalR)}</td><td className="p-2 text-right">{fmtR(r.avgR)}</td><td className="p-2 text-right">{r.maxDD.toFixed(2)}R</td></tr>)}</tbody></table></div></div><div><h3 className="text-sm font-semibold mb-2">Period-by-period OOS robustness</h3><div className="overflow-x-auto rounded-lg border"><table className="w-full text-xs"><thead><tr><th className="text-left p-2">Period</th><th className="p-2">Candidate</th><th className="text-right p-2">Trades</th><th className="text-right p-2">Win %</th><th className="text-right p-2">Total R</th></tr></thead><tbody>{analysis.rows.map((r,i)=><tr key={i} className="border-t"><td className="p-2 font-semibold">{r.period.label}</td><td className="p-2 text-center">{r.key}</td><td className="p-2 text-right">{r.trades}</td><td className="p-2 text-right">{r.winRate.toFixed(1)}%</td><td className={`p-2 text-right font-semibold ${tone(r.totalR)}`}>{fmtR(r.totalR)}</td></tr>)}</tbody></table></div></div></>}{analysis&&analysis.validCount===0&&<div className="rounded-lg border border-amber-300 bg-amber-50/60 dark:bg-amber-950/20 p-3 text-xs font-medium"><AlertTriangle className="inline mr-1" size={14}/>No valid OOS periods are available, so Candidate A/B performance is intentionally not calculated. Review the coverage/errors above.</div>}<p className="text-xs text-slate-500">Checkpoint-saved after each period. Invalid periods are never presented as legitimate 0R strategy results.</p></CardBody></Card>;
}
