import { useState } from 'react';
import { StoreProvider } from '@/store/StoreContext';
import { Sidebar, type PageKey } from '@/components/Sidebar';
import { Topbar, ChatPanel } from '@/components/Topbar';
import { LiveValidationRecorder } from '@/components/LiveValidationRecorder';
import { DataQualityRecorder } from '@/components/DataQualityRecorder';
import { FnoHistoryProbe } from '@/components/FnoHistoryProbe';
import { FnoPremiumBacktest } from '@/components/FnoPremiumBacktest';
import { StrategyResearchPanel } from '@/components/StrategyResearchPanel';
import { StrategyPremiumReplay } from '@/components/StrategyPremiumReplay';
import { OptionNativeResearchV3 } from '@/components/OptionNativeResearchV3';
import { OptionNativePhase2 } from '@/components/OptionNativePhase2';
import { MarketRegimeResearch } from '@/components/MarketRegimeResearch';
import { GlobalIntelligence } from '@/components/GlobalIntelligence';
import { MarketBrainV2 } from '@/components/MarketBrainV2';
import { MarketBrainInteractionResearch } from '@/components/MarketBrainInteractionResearch';
import { MarketBrainReplicationResearch } from '@/components/MarketBrainReplicationResearch';
import { MarketBrainTransitionResearch } from '@/components/MarketBrainTransitionResearch';
import { MarketBrainSetupExpectancyResearch } from '@/components/MarketBrainSetupExpectancyResearch';
import { EdgeDiscoveryLab } from '@/components/EdgeDiscoveryLab';
import { EdgeInteractionDiscovery } from '@/components/EdgeInteractionDiscovery';
import { EdgeTransitionDiscovery } from '@/components/EdgeTransitionDiscovery';
import { CandidateValidator } from '@/components/CandidateValidator';
import { CandidateBValidator } from '@/components/CandidateBValidator';
import { Dashboard } from '@/pages/Dashboard';
import { Portfolio } from '@/pages/Portfolio';
import { Options } from '@/pages/Options';
import { PositionSizing } from '@/pages/PositionSizing';
import { TradeScannerWithGift } from '@/pages/TradeScannerWithGift';
import { MondayLiveTest } from '@/pages/MondayLiveTest';
import { FirstLiveSessionChecklist } from '@/pages/FirstLiveSessionChecklist';
import { CommodityDiagnostics } from '@/pages/CommodityDiagnostics';
import { CommodityBacktest } from '@/pages/CommodityBacktest';
import { LiveValidation } from '@/pages/LiveValidation';
import { SystemHealth } from '@/pages/SystemHealth';
import { DataQuality } from '@/pages/DataQuality';
import { Backtest } from '@/pages/Backtest';
import { DirectionDiagnosticsPage } from '@/pages/DirectionDiagnosticsPage';
import { TradeSetup } from '@/pages/TradeSetup';
import { Journal } from '@/pages/Journal';
import { RiskCenter } from '@/pages/RiskCenter';
import { AIAnalyst } from '@/pages/AIAnalyst';
import { News } from '@/pages/News';
import { Markets } from '@/pages/Markets';
import { Alerts } from '@/pages/Alerts';
import { Settings } from '@/pages/Settings';
function AppContent(){const[page,setPage]=useState<PageKey>('dashboard');const[chatOpen,setChatOpen]=useState(false);const renderPage=()=>{switch(page){case'dashboard':return <Dashboard onNavigate={setPage}/>;case'markets':return <Markets/>;case'portfolio':return <Portfolio/>;case'options':return <Options/>;case'ai-analyst':return <AIAnalyst/>;case'trade-scanner':return <div className="space-y-5"><FirstLiveSessionChecklist/><MondayLiveTest/><TradeScannerWithGift onNavigate={setPage}/></div>;case'commodity-diagnostics':return <CommodityDiagnostics/>;case'commodity-backtest':return <CommodityBacktest/>;case'live-validation':return <LiveValidation/>;case'system-health':return <SystemHealth/>;case'data-quality':return <DataQuality/>;case'backtest':return <div className="space-y-5"><MarketBrainV2/><MarketBrainSetupExpectancyResearch/><MarketBrainTransitionResearch/><MarketBrainReplicationResearch/><MarketBrainInteractionResearch/><GlobalIntelligence/><CandidateBValidator/><CandidateValidator/><EdgeTransitionDiscovery/><EdgeInteractionDiscovery/><EdgeDiscoveryLab/><MarketRegimeResearch/><OptionNativePhase2/><OptionNativeResearchV3/><StrategyResearchPanel/><StrategyPremiumReplay/><FnoHistoryProbe/><FnoPremiumBacktest/><Backtest/></div>;case'direction-diagnostics':return <DirectionDiagnosticsPage/>;case'trade-setup':return <TradeSetup/>;case'position-sizing':return <PositionSizing/>;case'journal':return <Journal/>;case'risk':return <RiskCenter/>;case'news':return <News/>;case'alerts':return <Alerts/>;case'settings':return <Settings/>;default:return <Dashboard onNavigate={setPage}/>}};return <div className="min-h-screen bg-slate-50 dark:bg-slate-950 flex"><LiveValidationRecorder/><DataQualityRecorder/><Sidebar page={page} onNavigate={setPage}/><div className="flex-1 flex flex-col min-w-0"><Topbar onNavigate={setPage} onOpenChat={()=>setChatOpen(true)}/><main className="flex-1 p-4 md:p-6 overflow-x-hidden">{renderPage()}</main></div><ChatPanel open={chatOpen} onClose={()=>setChatOpen(false)}/></div>}
export default function App(){return <StoreProvider><AppContent/></StoreProvider>}
